/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'secondary-fixed': '#ffdad7',
        background: '#f8f9fa',
        'surface-tint': '#3e54c1',
        'on-error': '#ffffff',
        'on-tertiary-fixed-variant': '#454747',
        'on-surface-variant': '#444653',
        'on-primary': '#ffffff',
        error: '#ba1a1a',
        'surface-container-low': '#f3f4f5',
        'surface-container-highest': '#e1e3e4',
        'error-container': '#ffdad6',
        'on-primary-fixed-variant': '#223aa8',
        'on-tertiary-container': '#9b9c9c',
        'on-tertiary': '#ffffff',
        'on-primary-fixed': '#001159',
        tertiary: '#1d1f1f',
        'on-background': '#191c1d',
        'surface-container': '#edeeef',
        'secondary-container': '#e32033',
        'surface-container-high': '#e7e8e9',
        'on-error-container': '#93000a',
        'surface-bright': '#f8f9fa',
        surface: '#f8f9fa',
        primary: '#001360',
        'on-surface': '#191c1d',
        'on-secondary-fixed': '#410005',
        'on-secondary': '#ffffff',
        outline: '#757684',
        'primary-container': '#002395',
        'on-secondary-fixed-variant': '#930018',
        'inverse-surface': '#2e3132',
        'tertiary-fixed': '#e2e2e2',
        'on-secondary-container': '#fffbff',
        secondary: '#bb0021',
        'on-primary-container': '#8094ff',
        'primary-fixed-dim': '#bac3ff',
        'tertiary-container': '#323434',
        'primary-fixed': '#dee1ff',
        'surface-container-lowest': '#ffffff',
        'outline-variant': '#c5c5d5',
        'secondary-fixed-dim': '#ffb3af',
        'inverse-on-surface': '#f0f1f2',
        'inverse-primary': '#bac3ff',
        'on-tertiary-fixed': '#1a1c1c',
        'surface-variant': '#e1e3e4',
        'tertiary-fixed-dim': '#c6c6c7',
        'surface-dim': '#d9dadb',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      spacing: {
        unit: '4px',
        'stack-lg': '32px',
        'stack-sm': '8px',
        gutter: '24px',
        'stack-md': '16px',
        'container-max': '1280px',
        'margin-mobile': '16px',
        'margin-desktop': '32px',
      },
      fontFamily: {
        'headline-md': ['Inter', 'sans-serif'],
        'body-md': ['Inter', 'sans-serif'],
        'body-lg': ['Inter', 'sans-serif'],
        'label-md': ['Inter', 'sans-serif'],
        display: ['Inter', 'sans-serif'],
        'headline-lg': ['Inter', 'sans-serif'],
        'body-sm': ['Inter', 'sans-serif'],
        'mono-code': ['Inter', 'sans-serif'],
      },
      fontSize: {
        'headline-md': ['22px', { lineHeight: '30px', fontWeight: '600' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'label-md': ['12px', { lineHeight: '16px', letterSpacing: '0', fontWeight: '600' }],
        display: ['36px', { lineHeight: '44px', letterSpacing: '0', fontWeight: '700' }],
        'headline-lg': ['28px', { lineHeight: '36px', fontWeight: '600' }],
        'body-sm': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'mono-code': ['14px', { lineHeight: '20px', fontWeight: '500' }],
      },
    },
  },
  plugins: [],
}
