import type { Question, SkillTopic } from './types'

type TopicRow = [
  id: string,
  area: string,
  titleEn: string,
  titleFr: string,
  explanationEn: string,
  explanationFr: string,
  examples: string[],
  prerequisites: string[],
]

type QuestionRow = [
  topicId: string,
  type: Question['type'],
  promptEn: string,
  promptFr: string,
  choices: string[] | undefined,
  correctAnswer: string,
  explanationEn: string,
  explanationFr: string,
]

export interface ReadingExercise {
  id: string
  level: SkillTopic['level']
  title: string
  theme: string
  text: string
  questions: Array<{
    id: string
    prompt: string
    choices: string[]
    correctAnswer: string
    explanation: string
  }>
}

export interface WritingPrompt {
  id: string
  level: SkillTopic['level']
  title: string
  task: string
  checklist: string[]
  starter: string
}

export const a2B1Topics: SkillTopic[] = ([
  [
    'futur-simple-irregular-b1',
    'Verbs Tenses & Conjugation',
    'Future Simple: Irregular Stems',
    'Futur simple : radicaux irréguliers',
    'At B1, learners need the high-frequency irregular future stems: ser-, aur-, ir-, fer-, viendr-, pourr-, voudr-, devr-, saur-, and verr-. The endings stay regular.',
    'Au niveau B1, il faut maîtriser les radicaux irréguliers fréquents du futur : ser-, aur-, ir-, fer-, viendr-, pourr-, voudr-, devr-, saur- et verr-. Les terminaisons restent régulières.',
    ['demain, je serai prêt', 'nous aurons le temps', 'elles pourront venir', 'tu verras la différence'],
    ['future-simple-intro-a2'],
  ],
  [
    'plus-que-parfait-b1',
    'Past Tenses',
    'Plus-que-parfait',
    'Plus-que-parfait',
    'The plus-que-parfait describes an action completed before another past action. It uses avoir or être in the imparfait plus the past participle.',
    'Le plus-que-parfait décrit une action terminée avant une autre action passée. Il utilise avoir ou être à l’imparfait plus le participe passé.',
    ['j’avais déjà mangé', 'elle était partie avant midi', 'nous avions réservé une table'],
    ['pc-imparfait-a2'],
  ],
  [
    'si-imparfait-conditional-b1',
    'Hypothesis',
    'Si + Imparfait, Conditional',
    'Si + imparfait, conditionnel',
    'Use si plus imparfait with the conditional to imagine an unreal or unlikely present/future situation. Do not use the conditional directly after si.',
    'On utilise si plus imparfait avec le conditionnel pour imaginer une situation présente ou future irréelle ou peu probable. On n’utilise pas le conditionnel directement après si.',
    ['si j’avais le temps, je voyagerais', 'si tu venais, nous dînerions ensemble', 'je changerais de travail si je pouvais'],
    ['conditional-politeness-a2', 'imparfait'],
  ],
  [
    'subjunctive-basic-b1',
    'Mood',
    'Subjunctive Triggers',
    'Déclencheurs du subjonctif',
    'B1 learners should recognize common subjunctive triggers after que: necessity, desire, emotion, doubt, and purpose. Start with fixed phrases before mastering every irregular form.',
    'Les apprenants B1 doivent reconnaître les déclencheurs courants du subjonctif après que : nécessité, volonté, émotion, doute et but. Commencez par les expressions fréquentes avant toutes les formes irrégulières.',
    ['il faut que tu sois prêt', 'je veux qu’elle vienne', 'bien qu’il soit tard', 'pour que nous comprenions'],
    ['relative-qui-que-ou-a2'],
  ],
  [
    'double-pronouns-b1',
    'Pronouns',
    'Two Object Pronouns',
    'Deux pronoms compléments',
    'When two object pronouns appear together, French follows a fixed order. Common B1 patterns include me/te/se/nous/vous before le/la/les, then lui/leur, then y, then en.',
    'Quand deux pronoms compléments apparaissent ensemble, le français suit un ordre fixe. Les modèles B1 fréquents placent me/te/se/nous/vous avant le/la/les, puis lui/leur, puis y, puis en.',
    ['je le lui donne', 'elle nous en parle', 'tu les y mets', 'ne me le dites pas'],
    ['pronoun-placement-a2', 'y-en-intro-a2'],
  ],
  [
    'dont-ce-qui-ce-que-b1',
    'Complex Sentences',
    'Dont, Ce qui, Ce que',
    'Dont, ce qui, ce que',
    'B1 relative clauses become more precise with dont for de phrases and ce qui/ce que for “what/which” when there is no specific noun before the clause.',
    'Les relatives B1 deviennent plus précises avec dont pour les groupes avec de, et ce qui/ce que pour “what/which” quand il n’y a pas de nom précis avant la proposition.',
    ['le sujet dont je parle', 'ce qui me plaît', 'ce que je veux dire', 'la chose dont j’ai besoin'],
    ['relative-qui-que-ou-a2'],
  ],
  [
    'advanced-negation-b1',
    'Negative Words & Constructions',
    'Advanced Negation',
    'Négation avancée',
    'Beyond ne...pas, B1 learners combine negatives such as ne...plus, ne...jamais, ne...rien, ne...personne, ne...que, aucun, and ni...ni.',
    'Au-delà de ne...pas, les apprenants B1 combinent des négations comme ne...plus, ne...jamais, ne...rien, ne...personne, ne...que, aucun et ni...ni.',
    ['je ne vois personne', 'nous n’avons plus rien', 'elle ne boit que de l’eau', 'ni Paul ni Marie ne vient'],
    ['negation-varied-a2'],
  ],
  [
    'connectors-cause-consequence-b1',
    'Prepositions & Conjunctions',
    'Cause, Consequence, Contrast',
    'Cause, conséquence, contraste',
    'B1 writing and speaking need connectors to explain reasons, results, and contrast: parce que, puisque, donc, c’est pourquoi, pourtant, cependant, and en revanche.',
    'L’écrit et l’oral B1 ont besoin de connecteurs pour expliquer les causes, les conséquences et le contraste : parce que, puisque, donc, c’est pourquoi, pourtant, cependant et en revanche.',
    ['je reste parce qu’il pleut', 'il pleut, donc je reste', 'c’est cher ; cependant, c’est utile', 'en revanche, cette option est rapide'],
    ['reported-speech-a2'],
  ],
  [
    'reported-speech-past-b1',
    'Communication',
    'Reported Speech in the Past',
    'Discours rapporté au passé',
    'Reported speech at B1 focuses on clear que clauses and basic tense shifts when reporting what someone said, thought, explained, or asked.',
    'Le discours rapporté B1 se concentre sur les propositions avec que et les changements de temps simples quand on rapporte ce que quelqu’un a dit, pensé, expliqué ou demandé.',
    ['elle a dit qu’elle était malade', 'il a expliqué qu’il avait perdu son billet', 'nous avons répondu que nous viendrions'],
    ['reported-speech-a2', 'pc-imparfait-a2'],
  ],
  [
    'opinion-argument-b1',
    'Idioms, Idiomatic Usage, and Structures',
    'Giving and Defending Opinions',
    'Donner et défendre son opinion',
    'B1 learners must organize opinions with a clear claim, reason, example, and conclusion. Use structures such as à mon avis, je pense que, selon moi, d’une part, and en conclusion.',
    'Les apprenants B1 doivent organiser leurs opinions avec une idée claire, une raison, un exemple et une conclusion. Utilisez à mon avis, je pense que, selon moi, d’une part et en conclusion.',
    ['à mon avis, c’est nécessaire', 'je pense que les transports publics sont importants', 'd’une part, c’est pratique', 'en conclusion, je suis pour cette idée'],
    ['reported-speech-a2', 'connectors-cause-consequence-b1'],
  ],
] satisfies TopicRow[]).map(([id, area, titleEn, titleFr, explanationEn, explanationFr, examples, prerequisites], index) => ({
  id,
  level: 'B1',
  area,
  titleEn,
  titleFr,
  explanationEn,
  explanationFr,
  examples,
  prerequisites,
  confidence: 0,
  difficulty: 4,
  estimatedMinutes: 16,
  sequence: 100 + index,
}))

const curatedRows: QuestionRow[] = [
  [
    'futur-simple-irregular-b1',
    'fill',
    'Complete: Demain, nous ___ très occupés. (être)',
    'Complétez : Demain, nous ___ très occupés. (être)',
    undefined,
    'serons',
    'Être uses the irregular future stem ser- plus -ons.',
    'Être utilise le radical irrégulier ser- plus -ons.',
  ],
  [
    'futur-simple-irregular-b1',
    'fill',
    'Complete: Tu ___ le temps de réfléchir. (avoir)',
    'Complétez : Tu ___ le temps de réfléchir. (avoir)',
    undefined,
    'auras',
    'Avoir uses the future stem aur- plus -as.',
    'Avoir utilise le radical futur aur- plus -as.',
  ],
  [
    'futur-simple-irregular-b1',
    'multiple-choice',
    'Choose the correct future form: Elles ___ nous voir.',
    'Choisissez la bonne forme au futur : Elles ___ nous voir.',
    ['viendront', 'veniront', 'viennent', 'venaient'],
    'viendront',
    'Venir becomes viendr- in the future: elles viendront.',
    'Venir devient viendr- au futur : elles viendront.',
  ],
  [
    'futur-simple-irregular-b1',
    'fill',
    'Complete: Je ___ attention la prochaine fois. (faire)',
    'Complétez : Je ___ attention la prochaine fois. (faire)',
    undefined,
    'ferai',
    'Faire uses the future stem fer-.',
    'Faire utilise le radical futur fer-.',
  ],
  [
    'futur-simple-irregular-b1',
    'multiple-choice',
    'Choose: We will be able to leave early.',
    'Choisissez : Nous pourrons partir tôt.',
    ['Nous pouvons partir tôt.', 'Nous pourrons partir tôt.', 'Nous pouvions partir tôt.', 'Nous pouvrrons partir tôt.'],
    'Nous pourrons partir tôt.',
    'Pouvoir uses pourr- in the future.',
    'Pouvoir utilise pourr- au futur.',
  ],
  [
    'futur-simple-irregular-b1',
    'fill',
    'Complete: Vous ___ la réponse demain. (savoir)',
    'Complétez : Vous ___ la réponse demain. (savoir)',
    undefined,
    'saurez',
    'Savoir uses saur- in the future.',
    'Savoir utilise saur- au futur.',
  ],
  [
    'futur-simple-irregular-b1',
    'multiple-choice',
    'Which sentence is correct?',
    'Quelle phrase est correcte ?',
    ['Je voudrai te parler demain.', 'Je voudrais te parler demain.', 'Je veux te parler hier.', 'Je voulais te parler demain sera.'],
    'Je voudrai te parler demain.',
    'Voudrai is the future of vouloir; voudrais is conditional.',
    'Voudrai est le futur de vouloir ; voudrais est le conditionnel.',
  ],
  [
    'futur-simple-irregular-b1',
    'fill',
    'Complete: Il ___ rendre le dossier lundi. (devoir)',
    'Complétez : Il ___ rendre le dossier lundi. (devoir)',
    undefined,
    'devra',
    'Devoir uses devr- in the future.',
    'Devoir utilise devr- au futur.',
  ],
  [
    'futur-simple-irregular-b1',
    'multiple-choice',
    'Choose the future stem for voir.',
    'Choisissez le radical futur de voir.',
    ['voir-', 'verr-', 'voy-', 'voier-'],
    'verr-',
    'Voir becomes verr- before future endings.',
    'Voir devient verr- avant les terminaisons du futur.',
  ],
  [
    'futur-simple-irregular-b1',
    'fill',
    'Complete: Quand tu arriveras, je te ___. (voir)',
    'Complétez : Quand tu arriveras, je te ___. (voir)',
    undefined,
    'verrai',
    'The future form of voir with je is verrai.',
    'La forme de voir au futur avec je est verrai.',
  ],
  [
    'plus-que-parfait-b1',
    'multiple-choice',
    'Choose the plus-que-parfait: I had already eaten.',
    'Choisissez le plus-que-parfait : J’avais déjà mangé.',
    ['J’ai déjà mangé.', 'Je mangeais déjà.', 'J’avais déjà mangé.', 'Je vais déjà manger.'],
    'J’avais déjà mangé.',
    'Plus-que-parfait uses imparfait of avoir/être plus past participle.',
    'Le plus-que-parfait utilise l’imparfait de avoir/être plus le participe passé.',
  ],
  [
    'plus-que-parfait-b1',
    'fill',
    'Complete: Elle ___ avant notre arrivée. (partir)',
    'Complétez : Elle ___ avant notre arrivée. (partir)',
    undefined,
    'était partie',
    'Partir uses être; elle requires agreement: partie.',
    'Partir utilise être ; avec elle, on accorde : partie.',
  ],
  [
    'plus-que-parfait-b1',
    'fill',
    'Complete: Nous ___ une table avant de sortir. (réserver)',
    'Complétez : Nous ___ une table avant de sortir. (réserver)',
    undefined,
    'avions réservé',
    'Réserver uses avoir; nous avions réservé is plus-que-parfait.',
    'Réserver utilise avoir ; nous avions réservé est au plus-que-parfait.',
  ],
  [
    'plus-que-parfait-b1',
    'multiple-choice',
    'Which action happened first? Quand je suis arrivé, Paul avait fini.',
    'Quelle action s’est passée en premier ? Quand je suis arrivé, Paul avait fini.',
    ['Je suis arrivé.', 'Paul avait fini.', 'Both happened now.', 'Neither happened.'],
    'Paul avait fini.',
    'The plus-que-parfait marks the earlier past action.',
    'Le plus-que-parfait marque l’action passée la plus ancienne.',
  ],
  [
    'plus-que-parfait-b1',
    'fill',
    'Complete: Ils ___ leurs clés, donc ils ont appelé le voisin. (perdre)',
    'Complétez : Ils ___ leurs clés, donc ils ont appelé le voisin. (perdre)',
    undefined,
    'avaient perdu',
    'Avoir in the imparfait plus perdu gives avaient perdu.',
    'Avoir à l’imparfait plus perdu donne avaient perdu.',
  ],
  [
    'plus-que-parfait-b1',
    'multiple-choice',
    'Choose the correct sentence.',
    'Choisissez la phrase correcte.',
    ['J’avais allé au marché.', 'J’étais allé au marché.', 'J’ai étais allé au marché.', 'J’allais allé au marché.'],
    'J’étais allé au marché.',
    'Aller takes être in compound tenses.',
    'Aller prend être dans les temps composés.',
  ],
  [
    'plus-que-parfait-b1',
    'fill',
    'Complete: Tu ___ le film avant de lire le livre. (voir)',
    'Complétez : Tu ___ le film avant de lire le livre. (voir)',
    undefined,
    'avais vu',
    'Voir uses avoir; tu avais vu is correct.',
    'Voir utilise avoir ; tu avais vu est correct.',
  ],
  [
    'plus-que-parfait-b1',
    'multiple-choice',
    'Choose the best tense: Hier, je n’avais pas faim parce que je ___ trop à midi.',
    'Choisissez le meilleur temps : Hier, je n’avais pas faim parce que je ___ trop à midi.',
    ['mange', 'mangeais', 'avais mangé', 'mangerai'],
    'avais mangé',
    'The eating happened before the later past situation.',
    'Le repas a eu lieu avant la situation passée suivante.',
  ],
  [
    'plus-que-parfait-b1',
    'fill',
    'Complete: Vous ___ votre décision avant la réunion. (prendre)',
    'Complétez : Vous ___ votre décision avant la réunion. (prendre)',
    undefined,
    'aviez pris',
    'Prendre has the past participle pris.',
    'Le participe passé de prendre est pris.',
  ],
  [
    'plus-que-parfait-b1',
    'multiple-choice',
    'What is the auxiliary in “elles étaient sorties”?',
    'Quel est l’auxiliaire dans « elles étaient sorties » ?',
    ['avoir', 'être', 'aller', 'faire'],
    'être',
    'Étaient is the imparfait of être.',
    'Étaient est l’imparfait de être.',
  ],
  [
    'si-imparfait-conditional-b1',
    'multiple-choice',
    'Choose: If I had time, I would travel.',
    'Choisissez : Si j’avais le temps, je voyagerais.',
    ['Si j’aurais le temps, je voyagerais.', 'Si j’avais le temps, je voyagerais.', 'Si j’ai le temps, je voyagerais.', 'Si j’avais le temps, je voyagerai.'],
    'Si j’avais le temps, je voyagerais.',
    'Use si + imparfait, then conditional.',
    'On utilise si + imparfait, puis le conditionnel.',
  ],
  [
    'si-imparfait-conditional-b1',
    'fill',
    'Complete: Si tu venais, nous ___ ensemble. (dîner)',
    'Complétez : Si tu venais, nous ___ ensemble. (dîner)',
    undefined,
    'dînerions',
    'The result clause uses the conditional: nous dînerions.',
    'La conséquence utilise le conditionnel : nous dînerions.',
  ],
  [
    'si-imparfait-conditional-b1',
    'multiple-choice',
    'Which form should NOT follow si in this pattern?',
    'Quelle forme ne doit PAS suivre si dans ce modèle ?',
    ['imparfait', 'avais', 'aurais', 'pouvais'],
    'aurais',
    'Avoid conditional directly after si in this standard pattern.',
    'On évite le conditionnel directement après si dans ce modèle standard.',
  ],
  [
    'si-imparfait-conditional-b1',
    'fill',
    'Complete: Je changerais de travail si je ___. (pouvoir)',
    'Complétez : Je changerais de travail si je ___. (pouvoir)',
    undefined,
    'pouvais',
    'The si clause uses imparfait: je pouvais.',
    'La proposition avec si utilise l’imparfait : je pouvais.',
  ],
  [
    'si-imparfait-conditional-b1',
    'multiple-choice',
    'Choose the sentence with an unreal present hypothesis.',
    'Choisissez la phrase avec une hypothèse irréelle au présent.',
    ['Si elle étudie, elle réussira.', 'Si elle étudiait, elle réussirait.', 'Si elle a étudié, elle réussit.', 'Si elle étudiera, elle réussira.'],
    'Si elle étudiait, elle réussirait.',
    'Imparfait plus conditional imagines an unreal or unlikely situation.',
    'Imparfait plus conditionnel imagine une situation irréelle ou peu probable.',
  ],
  [
    'si-imparfait-conditional-b1',
    'fill',
    'Complete: Si nous avions plus d’argent, nous ___ une maison. (acheter)',
    'Complétez : Si nous avions plus d’argent, nous ___ une maison. (acheter)',
    undefined,
    'achèterions',
    'Acheter changes stem in the conditional: achèterions.',
    'Acheter change de radical au conditionnel : achèterions.',
  ],
  [
    'si-imparfait-conditional-b1',
    'multiple-choice',
    'Choose: If I were you, I would wait.',
    'Choisissez : Si j’étais toi, j’attendrais.',
    ['Si je suis toi, j’attendrais.', 'Si j’étais toi, j’attendrais.', 'Si j’aurais été toi, j’attends.', 'Si je serais toi, j’attendrais.'],
    'Si j’étais toi, j’attendrais.',
    'Use si j’étais toi for “if I were you”.',
    'On dit si j’étais toi pour “if I were you”.',
  ],
  [
    'si-imparfait-conditional-b1',
    'fill',
    'Complete: Elle nous aiderait si elle ___ libre. (être)',
    'Complétez : Elle nous aiderait si elle ___ libre. (être)',
    undefined,
    'était',
    'The si clause needs imparfait: elle était.',
    'La proposition avec si demande l’imparfait : elle était.',
  ],
  [
    'si-imparfait-conditional-b1',
    'multiple-choice',
    'Which verb is conditional?',
    'Quel verbe est au conditionnel ?',
    ['je pouvais', 'je peux', 'je pourrais', 'je pourrai'],
    'je pourrais',
    'Pourrais is conditional; pourrai is future.',
    'Pourrais est au conditionnel ; pourrai est au futur.',
  ],
  [
    'si-imparfait-conditional-b1',
    'fill',
    'Complete: Si vous saviez la vérité, vous ___ surpris. (être)',
    'Complétez : Si vous saviez la vérité, vous ___ surpris. (être)',
    undefined,
    'seriez',
    'The conditional of être with vous is seriez.',
    'Le conditionnel de être avec vous est seriez.',
  ],
  [
    'subjunctive-basic-b1',
    'fill',
    'Complete: Il faut que tu ___ à l’heure. (être)',
    'Complétez : Il faut que tu ___ à l’heure. (être)',
    undefined,
    'sois',
    'Il faut que triggers the subjunctive: tu sois.',
    'Il faut que déclenche le subjonctif : tu sois.',
  ],
  [
    'subjunctive-basic-b1',
    'multiple-choice',
    'Which expression usually triggers the subjunctive?',
    'Quelle expression déclenche généralement le subjonctif ?',
    ['je pense que', 'il faut que', 'il est vrai que', 'je sais que'],
    'il faut que',
    'Necessity expressions often trigger the subjunctive.',
    'Les expressions de nécessité déclenchent souvent le subjonctif.',
  ],
  [
    'subjunctive-basic-b1',
    'fill',
    'Complete: Je veux qu’elle ___ avec nous. (venir)',
    'Complétez : Je veux qu’elle ___ avec nous. (venir)',
    undefined,
    'vienne',
    'Vouloir que triggers the subjunctive: elle vienne.',
    'Vouloir que déclenche le subjonctif : elle vienne.',
  ],
  [
    'subjunctive-basic-b1',
    'multiple-choice',
    'Choose the correct sentence.',
    'Choisissez la phrase correcte.',
    ['Bien qu’il est tard, je continue.', 'Bien qu’il soit tard, je continue.', 'Bien que il est tard, je continue.', 'Bien qu’il sera tard, je continue.'],
    'Bien qu’il soit tard, je continue.',
    'Bien que is followed by the subjunctive.',
    'Bien que est suivi du subjonctif.',
  ],
  [
    'subjunctive-basic-b1',
    'fill',
    'Complete: Nous travaillons pour que tout ___ prêt. (être)',
    'Complétez : Nous travaillons pour que tout ___ prêt. (être)',
    undefined,
    'soit',
    'Pour que expresses purpose and usually takes the subjunctive.',
    'Pour que exprime le but et prend généralement le subjonctif.',
  ],
  [
    'subjunctive-basic-b1',
    'multiple-choice',
    'Which phrase does NOT normally require subjunctive?',
    'Quelle expression ne demande normalement PAS le subjonctif ?',
    ['je doute que', 'il est possible que', 'je sais que', 'il faut que'],
    'je sais que',
    'Certainty with savoir normally takes the indicative.',
    'La certitude avec savoir prend normalement l’indicatif.',
  ],
  [
    'subjunctive-basic-b1',
    'fill',
    'Complete: Il est important que nous ___ clairement. (parler)',
    'Complétez : Il est important que nous ___ clairement. (parler)',
    undefined,
    'parlions',
    'The nous subjunctive of parler is parlions.',
    'Le subjonctif de parler avec nous est parlions.',
  ],
  [
    'subjunctive-basic-b1',
    'multiple-choice',
    'Choose the subjunctive form of avoir with vous.',
    'Choisissez la forme du subjonctif de avoir avec vous.',
    ['avez', 'aviez', 'ayez', 'aurez'],
    'ayez',
    'Ayez is the subjunctive form with vous.',
    'Ayez est la forme du subjonctif avec vous.',
  ],
  [
    'subjunctive-basic-b1',
    'fill',
    'Complete: Je suis content que tu ___ réussi. (avoir)',
    'Complétez : Je suis content que tu ___ réussi. (avoir)',
    undefined,
    'aies',
    'Emotion plus que can trigger the subjunctive: tu aies.',
    'Une émotion plus que peut déclencher le subjonctif : tu aies.',
  ],
  [
    'subjunctive-basic-b1',
    'multiple-choice',
    'What is the main clue for subjunctive here: “Je veux que tu partes”?',
    'Quel est l’indice principal du subjonctif ici : « Je veux que tu partes » ?',
    ['two subjects with desire', 'a future time marker', 'a definite article', 'a direct object'],
    'two subjects with desire',
    'A change of subject after a desire verb often triggers subjunctive.',
    'Un changement de sujet après un verbe de volonté déclenche souvent le subjonctif.',
  ],
  [
    'double-pronouns-b1',
    'multiple-choice',
    'Replace “le document à Marie”: Je donne le document à Marie.',
    'Remplacez « le document à Marie » : Je donne le document à Marie.',
    ['Je le lui donne.', 'Je lui le donne.', 'Je la lui donne.', 'Je lui en donne.'],
    'Je le lui donne.',
    'Le/la/les comes before lui/leur.',
    'Le/la/les se place avant lui/leur.',
  ],
  [
    'double-pronouns-b1',
    'fill',
    'Complete: Tu as les clés ? Donne-___-moi. (les)',
    'Complétez : Tu as les clés ? Donne-___-moi. (les)',
    undefined,
    'les',
    'In affirmative commands, the order is verb + direct object + moi/toi/lui.',
    'À l’impératif affirmatif, l’ordre est verbe + COD + moi/toi/lui.',
  ],
  [
    'double-pronouns-b1',
    'multiple-choice',
    'Choose the negative command: Do not give it to him.',
    'Choisissez l’ordre négatif : Ne le lui donne pas.',
    ['Ne donne-le-lui pas.', 'Ne le lui donne pas.', 'Ne lui le donne pas.', 'Ne donne pas le lui.'],
    'Ne le lui donne pas.',
    'In negative commands, pronouns come before the verb.',
    'À l’impératif négatif, les pronoms se placent avant le verbe.',
  ],
  [
    'double-pronouns-b1',
    'multiple-choice',
    'Replace “des nouvelles à nous”: Elle donne des nouvelles à nous.',
    'Remplacez « des nouvelles à nous » : Elle donne des nouvelles à nous.',
    ['Elle nous en donne.', 'Elle en nous donne.', 'Elle les nous donne.', 'Elle nous y donne.'],
    'Elle nous en donne.',
    'Me/te/nous/vous comes before en.',
    'Me/te/nous/vous se place avant en.',
  ],
  [
    'double-pronouns-b1',
    'fill',
    'Complete: Ce livre est utile ; je vais ___ donner à Paul. (le)',
    'Complétez : Ce livre est utile ; je vais ___ donner à Paul. (le)',
    undefined,
    'le lui',
    'With an infinitive, the pronouns go before the infinitive: le lui donner.',
    'Avec un infinitif, les pronoms se placent avant l’infinitif : le lui donner.',
  ],
  [
    'double-pronouns-b1',
    'multiple-choice',
    'Which order is correct before a conjugated verb?',
    'Quel ordre est correct avant un verbe conjugué ?',
    ['lui le', 'en y', 'le lui', 'y nous'],
    'le lui',
    'Direct object pronouns come before lui/leur.',
    'Les pronoms COD se placent avant lui/leur.',
  ],
  [
    'double-pronouns-b1',
    'fill',
    'Complete: Des croissants ? J’___ achète deux.',
    'Complétez : Des croissants ? J’___ achète deux.',
    undefined,
    'en',
    'En replaces a quantity phrase.',
    'En remplace un groupe de quantité.',
  ],
  [
    'double-pronouns-b1',
    'multiple-choice',
    'Choose: I am taking her there.',
    'Choisissez : Je l’y emmène.',
    ['Je lui y emmène.', 'Je l’y emmène.', 'J’y la emmène.', 'Je l’en emmène.'],
    'Je l’y emmène.',
    'Le/la/les comes before y.',
    'Le/la/les se place avant y.',
  ],
  [
    'double-pronouns-b1',
    'fill',
    'Complete: Ne ___ parle pas ! (me + en)',
    'Complétez : Ne ___ parle pas ! (me + en)',
    undefined,
    'm’en',
    'Me becomes m’ before en.',
    'Me devient m’ devant en.',
  ],
  [
    'double-pronouns-b1',
    'multiple-choice',
    'Choose the correct affirmative command.',
    'Choisissez l’impératif affirmatif correct.',
    ['Parles-m’en.', 'Parle-m’en.', 'M’en parle.', 'Parle-en-moi.'],
    'Parle-m’en.',
    'The affirmative command uses moi/toi before en, contracted to m’en/t’en.',
    'L’impératif affirmatif utilise moi/toi avant en, contracté en m’en/t’en.',
  ],
  [
    'dont-ce-qui-ce-que-b1',
    'multiple-choice',
    'Choose: The subject ___ I am speaking.',
    'Choisissez : Le sujet ___ je parle.',
    ['qui', 'que', 'dont', 'où'],
    'dont',
    'Parler de requires dont in a relative clause.',
    'Parler de demande dont dans une proposition relative.',
  ],
  [
    'dont-ce-qui-ce-que-b1',
    'fill',
    'Complete: ___ me plaît, c’est la musique.',
    'Complétez : ___ me plaît, c’est la musique.',
    undefined,
    'Ce qui',
    'Ce qui is the subject of plaît.',
    'Ce qui est le sujet de plaît.',
  ],
  [
    'dont-ce-qui-ce-que-b1',
    'fill',
    'Complete: ___ je veux dire est simple.',
    'Complétez : ___ je veux dire est simple.',
    undefined,
    'Ce que',
    'Ce que is the direct object of veux dire.',
    'Ce que est le complément d’objet direct de veux dire.',
  ],
  [
    'dont-ce-qui-ce-que-b1',
    'multiple-choice',
    'Choose: The woman whose son is here.',
    'Choisissez : La femme dont le fils est ici.',
    ['La femme que le fils est ici.', 'La femme dont le fils est ici.', 'La femme qui le fils est ici.', 'La femme où le fils est ici.'],
    'La femme dont le fils est ici.',
    'Dont can express possession with de.',
    'Dont peut exprimer la possession avec de.',
  ],
  [
    'dont-ce-qui-ce-que-b1',
    'multiple-choice',
    'Which pronoun replaces “de cette chose”?',
    'Quel pronom remplace « de cette chose » ?',
    ['qui', 'que', 'dont', 'où'],
    'dont',
    'Dont replaces de plus a noun or phrase.',
    'Dont remplace de plus un nom ou un groupe.',
  ],
  [
    'dont-ce-qui-ce-que-b1',
    'fill',
    'Complete: Je ne comprends pas ___ il veut.',
    'Complétez : Je ne comprends pas ___ il veut.',
    undefined,
    'ce qu’',
    'Ce que becomes ce qu’ before a vowel sound.',
    'Ce que devient ce qu’ devant un son voyelle.',
  ],
  [
    'dont-ce-qui-ce-que-b1',
    'multiple-choice',
    'Choose: What worries me is the price.',
    'Choisissez : Ce qui m’inquiète, c’est le prix.',
    ['Ce que m’inquiète, c’est le prix.', 'Ce qui m’inquiète, c’est le prix.', 'Dont m’inquiète, c’est le prix.', 'Ce où m’inquiète, c’est le prix.'],
    'Ce qui m’inquiète, c’est le prix.',
    'Ce qui is subject of inquiète.',
    'Ce qui est sujet de inquiète.',
  ],
  [
    'dont-ce-qui-ce-que-b1',
    'fill',
    'Complete: Voilà le livre ___ j’ai besoin.',
    'Complétez : Voilà le livre ___ j’ai besoin.',
    undefined,
    'dont',
    'Avoir besoin de takes dont in a relative clause.',
    'Avoir besoin de prend dont dans une relative.',
  ],
  [
    'dont-ce-qui-ce-que-b1',
    'multiple-choice',
    'Choose the direct object relative pronoun.',
    'Choisissez le pronom relatif COD.',
    ['qui', 'que', 'dont', 'où'],
    'que',
    'Que is the direct object relative pronoun.',
    'Que est le pronom relatif complément d’objet direct.',
  ],
  [
    'dont-ce-qui-ce-que-b1',
    'fill',
    'Complete: Dis-moi ___ tu as vu.',
    'Complétez : Dis-moi ___ tu as vu.',
    undefined,
    'ce que',
    'Ce que means “what” as a direct object.',
    'Ce que signifie “what” comme complément d’objet direct.',
  ],
  [
    'advanced-negation-b1',
    'multiple-choice',
    'Choose: I no longer have anything.',
    'Choisissez : Je n’ai plus rien.',
    ['Je n’ai plus rien.', 'Je n’ai rien plus.', 'Je ne plus ai rien.', 'Je n’ai pas plus rien.'],
    'Je n’ai plus rien.',
    'Multiple negatives can combine after the verb.',
    'Plusieurs négations peuvent se combiner après le verbe.',
  ],
  [
    'advanced-negation-b1',
    'fill',
    'Complete: Elle ne boit ___ de l’eau. (only)',
    'Complétez : Elle ne boit ___ de l’eau. (seulement)',
    undefined,
    'que',
    'Ne...que means only.',
    'Ne...que signifie seulement.',
  ],
  [
    'advanced-negation-b1',
    'multiple-choice',
    'Choose: Nobody came.',
    'Choisissez : Personne n’est venu.',
    ['Personne est venu.', 'Personne n’est venu.', 'Ne personne est venu.', 'Personne ne venu.'],
    'Personne n’est venu.',
    'Personne can be the subject, followed by ne.',
    'Personne peut être sujet, suivi de ne.',
  ],
  [
    'advanced-negation-b1',
    'fill',
    'Complete: Je n’ai vu ___ dans la rue. (nobody)',
    'Complétez : Je n’ai vu ___ dans la rue. (personne)',
    undefined,
    'personne',
    'Ne...personne means nobody/not anybody.',
    'Ne...personne signifie nobody/not anybody.',
  ],
  [
    'advanced-negation-b1',
    'multiple-choice',
    'Choose: Neither Paul nor Marie is coming.',
    'Choisissez : Ni Paul ni Marie ne vient.',
    ['Ni Paul ni Marie ne vient.', 'Paul ni Marie ne vient.', 'Ni Paul ni Marie vient.', 'Ne Paul ni Marie vient.'],
    'Ni Paul ni Marie ne vient.',
    'Ni...ni pairs with ne before the verb.',
    'Ni...ni s’emploie avec ne avant le verbe.',
  ],
  [
    'advanced-negation-b1',
    'fill',
    'Complete: ___ étudiant n’a réussi l’exercice. (no)',
    'Complétez : ___ étudiant n’a réussi l’exercice. (aucun)',
    undefined,
    'Aucun',
    'Aucun means no/none and pairs with ne.',
    'Aucun signifie no/none et s’emploie avec ne.',
  ],
  [
    'advanced-negation-b1',
    'multiple-choice',
    'Which sentence means “I only have ten euros”?',
    'Quelle phrase signifie « Je n’ai que dix euros » ?',
    ['Je n’ai pas dix euros.', 'Je n’ai que dix euros.', 'Je n’ai plus dix euros.', 'Je n’ai rien dix euros.'],
    'Je n’ai que dix euros.',
    'Ne...que restricts the meaning to only.',
    'Ne...que limite le sens à seulement.',
  ],
  [
    'advanced-negation-b1',
    'fill',
    'Complete: Rien ne ___ facile. (être)',
    'Complétez : Rien ne ___ facile. (être)',
    undefined,
    'sera',
    'Rien can be the subject; ne stays before the verb.',
    'Rien peut être sujet ; ne reste avant le verbe.',
  ],
  [
    'advanced-negation-b1',
    'multiple-choice',
    'Choose the formal written negative.',
    'Choisissez la négation écrite formelle.',
    ['Je sais pas.', 'Je ne sais pas.', 'Je pas sais.', 'Sais pas je.'],
    'Je ne sais pas.',
    'Written standard French keeps ne.',
    'Le français écrit standard garde ne.',
  ],
  [
    'advanced-negation-b1',
    'fill',
    'Complete: Nous ne voulons ___ sortir ___ parler. (neither/nor)',
    'Complétez : Nous ne voulons ___ sortir ___ parler. (ni/ni)',
    undefined,
    'ni/ni',
    'Ni...ni links two negative options.',
    'Ni...ni relie deux options négatives.',
  ],
  [
    'connectors-cause-consequence-b1',
    'multiple-choice',
    'Choose the connector of consequence.',
    'Choisissez le connecteur de conséquence.',
    ['parce que', 'donc', 'bien que', 'malgré'],
    'donc',
    'Donc introduces a result or consequence.',
    'Donc introduit un résultat ou une conséquence.',
  ],
  [
    'connectors-cause-consequence-b1',
    'fill',
    'Complete: Je reste à la maison ___ il pleut.',
    'Complétez : Je reste à la maison ___ il pleut.',
    undefined,
    'parce qu’',
    'Parce que becomes parce qu’ before a vowel sound.',
    'Parce que devient parce qu’ devant un son voyelle.',
  ],
  [
    'connectors-cause-consequence-b1',
    'multiple-choice',
    'Choose the contrast connector.',
    'Choisissez le connecteur de contraste.',
    ['c’est pourquoi', 'par conséquent', 'cependant', 'donc'],
    'cependant',
    'Cependant introduces contrast.',
    'Cependant introduit un contraste.',
  ],
  [
    'connectors-cause-consequence-b1',
    'fill',
    'Complete: Il a raté son train ; ___, il est arrivé tard.',
    'Complétez : Il a raté son train ; ___, il est arrivé tard.',
    undefined,
    'c’est pourquoi',
    'C’est pourquoi introduces the result of the previous idea.',
    'C’est pourquoi introduit le résultat de l’idée précédente.',
  ],
  [
    'connectors-cause-consequence-b1',
    'multiple-choice',
    'Which connector gives a reason already known to the listener?',
    'Quel connecteur donne une raison déjà connue de l’interlocuteur ?',
    ['puisque', 'pourtant', 'en revanche', 'donc'],
    'puisque',
    'Puisque often means since/as when the reason is known.',
    'Puisque signifie souvent since/as quand la raison est connue.',
  ],
  [
    'connectors-cause-consequence-b1',
    'fill',
    'Complete: C’est cher ; ___, la qualité est excellente.',
    'Complétez : C’est cher ; ___, la qualité est excellente.',
    undefined,
    'cependant',
    'Cependant fits a contrast between price and quality.',
    'Cependant convient pour opposer le prix et la qualité.',
  ],
  [
    'connectors-cause-consequence-b1',
    'multiple-choice',
    'Choose: On the other hand, this option is faster.',
    'Choisissez : En revanche, cette option est plus rapide.',
    ['Par conséquent, cette option est plus rapide.', 'En revanche, cette option est plus rapide.', 'Parce que cette option est plus rapide.', 'Puisque cette option est plus rapide.'],
    'En revanche, cette option est plus rapide.',
    'En revanche introduces an opposing point.',
    'En revanche introduit un point opposé.',
  ],
  [
    'connectors-cause-consequence-b1',
    'fill',
    'Complete: Le dossier est incomplet ; ___ il faut le refaire.',
    'Complétez : Le dossier est incomplet ; ___ il faut le refaire.',
    undefined,
    'donc',
    'Donc introduces a logical consequence.',
    'Donc introduit une conséquence logique.',
  ],
  [
    'connectors-cause-consequence-b1',
    'multiple-choice',
    'Which connector means “nevertheless/however”?',
    'Quel connecteur signifie « however/nevertheless » ?',
    ['cependant', 'parce que', 'alors', 'puisque'],
    'cependant',
    'Cependant is used to qualify or contrast an idea.',
    'Cependant sert à nuancer ou opposer une idée.',
  ],
  [
    'connectors-cause-consequence-b1',
    'fill',
    'Complete: ___ tu es malade, appelle le médecin.',
    'Complétez : ___ tu es malade, appelle le médecin.',
    undefined,
    'Puisque',
    'Puisque can introduce a known cause before advice.',
    'Puisque peut introduire une cause connue avant un conseil.',
  ],
  [
    'reported-speech-past-b1',
    'multiple-choice',
    'Choose: She said that she was sick.',
    'Choisissez : Elle a dit qu’elle était malade.',
    ['Elle a dit elle était malade.', 'Elle a dit qu’elle était malade.', 'Elle disait qu’elle est malade.', 'Elle a dit que malade.'],
    'Elle a dit qu’elle était malade.',
    'Reported speech uses que before the reported clause.',
    'Le discours rapporté utilise que avant la proposition rapportée.',
  ],
  [
    'reported-speech-past-b1',
    'fill',
    'Complete: Il a expliqué qu’il ___ son billet. (perdre)',
    'Complétez : Il a expliqué qu’il ___ son billet. (perdre)',
    undefined,
    'avait perdu',
    'A past event before another past report can use plus-que-parfait.',
    'Un événement passé avant un autre passé peut utiliser le plus-que-parfait.',
  ],
  [
    'reported-speech-past-b1',
    'multiple-choice',
    'Choose the reporting verb phrase.',
    'Choisissez le groupe verbal introducteur.',
    ['qu’il était', 'il a expliqué que', 'son billet', 'malade'],
    'il a expliqué que',
    'The reporting verb introduces what someone said or explained.',
    'Le verbe introducteur présente ce que quelqu’un a dit ou expliqué.',
  ],
  [
    'reported-speech-past-b1',
    'fill',
    'Complete: Nous avons répondu que nous ___ demain. (venir, conditional)',
    'Complétez : Nous avons répondu que nous ___ demain. (venir, conditionnel)',
    undefined,
    'viendrions',
    'Future-in-the-past is often expressed with the conditional.',
    'Le futur dans le passé s’exprime souvent avec le conditionnel.',
  ],
  [
    'reported-speech-past-b1',
    'multiple-choice',
    'Choose: He asked if I was ready.',
    'Choisissez : Il a demandé si j’étais prêt.',
    ['Il a demandé que j’étais prêt.', 'Il a demandé si j’étais prêt.', 'Il a demandé je suis prêt.', 'Il a demandé est-ce que j’étais prêt.'],
    'Il a demandé si j’étais prêt.',
    'Indirect yes/no questions use si.',
    'Les questions indirectes oui/non utilisent si.',
  ],
  [
    'reported-speech-past-b1',
    'fill',
    'Complete: Elle a dit qu’elle ___ plus tard. (appeler, conditional)',
    'Complétez : Elle a dit qu’elle ___ plus tard. (appeler, conditionnel)',
    undefined,
    'appellerait',
    'Future from a past viewpoint often uses conditional.',
    'Le futur vu depuis le passé utilise souvent le conditionnel.',
  ],
  [
    'reported-speech-past-b1',
    'multiple-choice',
    'Which sentence reports a statement correctly?',
    'Quelle phrase rapporte correctement une affirmation ?',
    ['Il dit que le train est en retard.', 'Il dit si le train est en retard.', 'Il dit est-ce que le train est en retard.', 'Il dit le train être en retard.'],
    'Il dit que le train est en retard.',
    'Statements are introduced with que.',
    'Les affirmations sont introduites avec que.',
  ],
  [
    'reported-speech-past-b1',
    'fill',
    'Complete: Le professeur a annoncé que l’examen ___ difficile. (être, imparfait)',
    'Complétez : Le professeur a annoncé que l’examen ___ difficile. (être, imparfait)',
    undefined,
    'était',
    'In past reporting, the reported state often shifts to imparfait.',
    'Dans le discours rapporté au passé, l’état rapporté passe souvent à l’imparfait.',
  ],
  [
    'reported-speech-past-b1',
    'multiple-choice',
    'Choose the indirect question.',
    'Choisissez la question indirecte.',
    ['Je demande où est la gare ?', 'Je demande où la gare est.', 'Je demande où est la gare.', 'Je demande où se trouve la gare.'],
    'Je demande où se trouve la gare.',
    'Indirect questions usually avoid direct inversion punctuation.',
    'Les questions indirectes évitent généralement l’inversion directe et le point d’interrogation.',
  ],
  [
    'reported-speech-past-b1',
    'fill',
    'Complete: Il m’a demandé ce que je ___. (vouloir, imparfait)',
    'Complétez : Il m’a demandé ce que je ___. (vouloir, imparfait)',
    undefined,
    'voulais',
    'After a past reporting verb, vouloir often shifts to imparfait.',
    'Après un verbe introducteur au passé, vouloir passe souvent à l’imparfait.',
  ],
  [
    'opinion-argument-b1',
    'multiple-choice',
    'Choose a good B1 opinion opener.',
    'Choisissez une bonne introduction d’opinion B1.',
    ['À mon avis,', 'Hier soir,', 'Sous la table,', 'Trente-deux,'],
    'À mon avis,',
    'À mon avis introduces an opinion clearly.',
    'À mon avis introduit clairement une opinion.',
  ],
  [
    'opinion-argument-b1',
    'fill',
    'Complete: Je pense ___ les transports publics sont importants.',
    'Complétez : Je pense ___ les transports publics sont importants.',
    undefined,
    'que',
    'Penser que introduces a clause.',
    'Penser que introduit une proposition.',
  ],
  [
    'opinion-argument-b1',
    'multiple-choice',
    'Which connector introduces a first argument?',
    'Quel connecteur introduit un premier argument ?',
    ['d’une part', 'en conclusion', 'pourtant', 'avant-hier'],
    'd’une part',
    'D’une part begins a structured argument.',
    'D’une part commence un argument structuré.',
  ],
  [
    'opinion-argument-b1',
    'fill',
    'Complete: ___ conclusion, je suis pour cette idée.',
    'Complétez : ___ conclusion, je suis pour cette idée.',
    undefined,
    'En',
    'En conclusion introduces the final point.',
    'En conclusion introduit le point final.',
  ],
  [
    'opinion-argument-b1',
    'multiple-choice',
    'Choose the strongest B1 sentence.',
    'Choisissez la phrase B1 la plus solide.',
    ['C’est bien.', 'Je suis pour cette mesure parce qu’elle réduit les coûts.', 'Moi, bon.', 'La mesure oui.'],
    'Je suis pour cette mesure parce qu’elle réduit les coûts.',
    'B1 opinions need a reason, not just a short reaction.',
    'Les opinions B1 ont besoin d’une raison, pas seulement d’une réaction courte.',
  ],
  [
    'opinion-argument-b1',
    'fill',
    'Complete: Selon ___, cette solution est plus juste.',
    'Complétez : Selon ___, cette solution est plus juste.',
    undefined,
    'moi',
    'Selon moi is a fixed opinion phrase.',
    'Selon moi est une expression fixe d’opinion.',
  ],
  [
    'opinion-argument-b1',
    'multiple-choice',
    'Which phrase adds an example?',
    'Quelle expression ajoute un exemple ?',
    ['par exemple', 'cependant', 'malgré', 'donc'],
    'par exemple',
    'Par exemple introduces evidence or illustration.',
    'Par exemple introduit une preuve ou une illustration.',
  ],
  [
    'opinion-argument-b1',
    'fill',
    'Complete: Je ne suis pas d’accord ___ cette proposition.',
    'Complétez : Je ne suis pas d’accord ___ cette proposition.',
    undefined,
    'avec',
    'Être d’accord takes avec.',
    'Être d’accord se construit avec avec.',
  ],
  [
    'opinion-argument-b1',
    'multiple-choice',
    'Choose the phrase that softens an opinion.',
    'Choisissez l’expression qui nuance une opinion.',
    ['Il me semble que', 'Fermez la porte', 'Il y a deux ans', 'Sous le lit'],
    'Il me semble que',
    'Il me semble que presents an opinion with nuance.',
    'Il me semble que présente une opinion avec nuance.',
  ],
  [
    'opinion-argument-b1',
    'fill',
    'Complete: D’autre ___, cette option coûte moins cher.',
    'Complétez : D’autre ___, cette option coûte moins cher.',
    undefined,
    'part',
    'D’autre part introduces another argument.',
    'D’autre part introduit un autre argument.',
  ],
]

export const a2B1QuestionBank: Question[] = curatedRows.map(
  ([topicId, type, promptEn, promptFr, choices, correctAnswer, explanationEn, explanationFr], index) => ({
    id: `a2b1-${topicId}-${index + 1}`,
    topicId,
    type,
    promptEn,
    promptFr,
    choices,
    correctAnswer,
    explanationEn,
    explanationFr,
  }),
)

export function completeQuestionSets(topics: SkillTopic[], questions: Question[], targetSize = 10): Question[] {
  const generated: Question[] = []
  const existingIds = new Set(questions.map((question) => question.id))
  const examples = topics.flatMap((topic) =>
    topic.examples.map((example) => ({
      topicId: topic.id,
      example,
      titleEn: topic.titleEn,
      titleFr: topic.titleFr,
    })),
  )

  topics.forEach((topic, topicIndex) => {
    let count =
      questions.filter((question) => question.topicId === topic.id).length +
      generated.filter((question) => question.topicId === topic.id).length

    while (count < targetSize) {
      const ownExample = topic.examples[count % Math.max(1, topic.examples.length)] ?? topic.titleFr
      const distractors = examples
        .filter((item) => item.topicId !== topic.id)
        .slice(topicIndex + count, topicIndex + count + 8)
        .map((item) => item.example)
      const choices = uniqueChoices([ownExample, ...distractors]).slice(0, 4)
      const id = `q-${topic.id}-set-${count + 1}`

      if (!existingIds.has(id)) {
        generated.push({
          id,
          topicId: topic.id,
          type: 'multiple-choice',
          promptEn: [
            `Choose the sentence that best illustrates “${topic.titleEn}”.`,
            `Which example uses the rule “${topic.titleEn}” correctly?`,
            `Select the best model sentence for “${topic.titleEn}”.`,
            `Which sentence should you keep as a correct example of “${topic.titleEn}”?`,
          ][count % 4],
          promptFr: [
            `Choisissez la phrase qui illustre le mieux « ${topic.titleFr} ».`,
            `Quel exemple utilise correctement la règle « ${topic.titleFr} » ?`,
            `Sélectionnez la meilleure phrase modèle pour « ${topic.titleFr} ».`,
            `Quelle phrase faut-il retenir comme exemple correct de « ${topic.titleFr} » ?`,
          ][count % 4],
          choices,
          correctAnswer: ownExample,
          explanationEn: `This example belongs to ${topic.titleEn}. Review the rule and say the example aloud before moving on.`,
          explanationFr: `Cet exemple appartient à ${topic.titleFr}. Révisez la règle et dites l’exemple à voix haute avant de continuer.`,
        })
      }
      count += 1
    }
  })

  return generated
}

export const readingExercises: ReadingExercise[] = [
  {
    id: 'b1-reading-work-remote',
    level: 'B1',
    title: 'Travailler à distance',
    theme: 'Work & Society',
    text:
      'Depuis quelques années, le télétravail est devenu plus courant dans beaucoup d’entreprises. Certains employés apprécient cette organisation parce qu’ils gagnent du temps et évitent les transports. Cependant, d’autres regrettent les discussions spontanées avec leurs collègues. Selon plusieurs responsables, la meilleure solution est souvent hybride : deux ou trois jours au bureau, puis le reste à la maison. Ainsi, chacun peut garder un lien avec l’équipe tout en travaillant dans un environnement plus calme.',
    questions: [
      {
        id: 'remote-main',
        prompt: 'Quelle est l’idée principale du texte ?',
        choices: ['Le télétravail doit disparaître.', 'Le travail hybride peut équilibrer plusieurs besoins.', 'Les employés refusent les transports.', 'Les entreprises ferment leurs bureaux.'],
        correctAnswer: 'Le travail hybride peut équilibrer plusieurs besoins.',
        explanation: 'Le texte présente avantages, limites, puis une solution hybride.',
      },
      {
        id: 'remote-advantage',
        prompt: 'Quel avantage du télétravail est mentionné ?',
        choices: ['Gagner du temps', 'Voyager gratuitement', 'Changer de métier', 'Apprendre une langue'],
        correctAnswer: 'Gagner du temps',
        explanation: 'Le texte dit que certains employés gagnent du temps et évitent les transports.',
      },
      {
        id: 'remote-connector',
        prompt: 'Que marque le mot “Cependant” ?',
        choices: ['Une cause', 'Une opposition', 'Une date', 'Une quantité'],
        correctAnswer: 'Une opposition',
        explanation: 'Cependant introduit un contraste avec l’idée précédente.',
      },
    ],
  },
  {
    id: 'b1-reading-city-transport',
    level: 'B1',
    title: 'Une ville plus calme',
    theme: 'Environment & Transport',
    text:
      'La mairie veut réduire la circulation dans le centre-ville. À partir du mois prochain, certaines rues seront réservées aux bus, aux vélos et aux piétons. Les commerçants sont partagés : quelques-uns craignent de perdre des clients, tandis que d’autres pensent que les rues plus calmes attireront davantage de visiteurs. La mairie promet aussi d’ajouter des parkings près des stations de tramway. Si le projet réussit, la ville créera de nouvelles zones sans voiture l’année prochaine.',
    questions: [
      {
        id: 'city-goal',
        prompt: 'Quel est l’objectif principal de la mairie ?',
        choices: ['Augmenter les voitures', 'Réduire la circulation', 'Fermer les commerces', 'Supprimer les tramways'],
        correctAnswer: 'Réduire la circulation',
        explanation: 'La première phrase donne l’objectif : réduire la circulation.',
      },
      {
        id: 'city-reaction',
        prompt: 'Comment réagissent les commerçants ?',
        choices: ['Ils sont tous d’accord.', 'Ils sont partagés.', 'Ils quittent la ville.', 'Ils refusent les visiteurs.'],
        correctAnswer: 'Ils sont partagés.',
        explanation: 'Le texte indique deux réactions différentes chez les commerçants.',
      },
      {
        id: 'city-condition',
        prompt: 'Quelle structure exprime une condition ?',
        choices: ['À partir du mois prochain', 'tandis que', 'Si le projet réussit', 'près des stations'],
        correctAnswer: 'Si le projet réussit',
        explanation: 'Si introduit la condition.',
      },
    ],
  },
  {
    id: 'a2-reading-neighbour',
    level: 'A2',
    title: 'Un nouveau voisin',
    theme: 'Daily Life',
    text:
      'La semaine dernière, Amira a rencontré son nouveau voisin dans l’escalier. Il s’appelle Julien et il vient de Lyon. Comme il ne connaît pas encore le quartier, Amira lui a montré la boulangerie, la pharmacie et l’arrêt de bus. Julien était content parce qu’il avait besoin d’acheter du pain et de trouver un médecin. Le soir, il a envoyé un message à Amira pour la remercier.',
    questions: [
      {
        id: 'neighbor-when',
        prompt: 'Quand Amira a-t-elle rencontré Julien ?',
        choices: ['Hier soir', 'La semaine dernière', 'Demain matin', 'Il y a un an'],
        correctAnswer: 'La semaine dernière',
        explanation: 'Le texte commence par “La semaine dernière”.',
      },
      {
        id: 'neighbor-origin',
        prompt: 'D’où vient Julien ?',
        choices: ['De Paris', 'De Lyon', 'De Marseille', 'De Lille'],
        correctAnswer: 'De Lyon',
        explanation: 'Le texte dit : “il vient de Lyon”.',
      },
      {
        id: 'neighbor-thanks',
        prompt: 'Pourquoi Julien envoie-t-il un message ?',
        choices: ['Pour demander un billet', 'Pour remercier Amira', 'Pour annuler un rendez-vous', 'Pour vendre du pain'],
        correctAnswer: 'Pour remercier Amira',
        explanation: 'La dernière phrase indique qu’il remercie Amira.',
      },
    ],
  },
]

export const writingPrompts: WritingPrompt[] = [
  {
    id: 'b1-writing-opinion-transport',
    level: 'B1',
    title: 'Opinion: public transport',
    task: 'Write 120-160 words. Give your opinion about making public transport cheaper in big cities. Include one reason, one example, and one contrast.',
    checklist: ['Use à mon avis or selon moi', 'Use parce que or puisque', 'Use cependant or en revanche', 'End with a clear conclusion'],
    starter: 'À mon avis, les transports publics devraient être moins chers parce que...',
  },
  {
    id: 'b1-writing-past-story',
    level: 'B1',
    title: 'Past story: a problem solved',
    task: 'Write 120-160 words about a problem you had during a trip or appointment. Use passé composé for events and imparfait for background.',
    checklist: ['Use at least three passé composé verbs', 'Use at least two imparfait verbs', 'Use quand or pendant que', 'Explain the solution'],
    starter: 'La semaine dernière, je devais aller à un rendez-vous important. Il faisait...',
  },
  {
    id: 'a2-writing-email',
    level: 'A2',
    title: 'Practical email',
    task: 'Write 80-120 words to ask for information about a French course. Ask about the price, schedule, level, and registration.',
    checklist: ['Open politely', 'Ask three clear questions', 'Use je voudrais or pourriez-vous', 'Close politely'],
    starter: 'Bonjour, je voudrais avoir des informations sur vos cours de français...',
  },
]

function uniqueChoices(values: string[]) {
  const seen = new Set<string>()
  return values.filter((value) => {
    const normalized = value.toLocaleLowerCase('fr-FR')
    if (seen.has(normalized)) return false
    seen.add(normalized)
    return true
  })
}
