import type { Question, SkillTopic, VocabCard, VocabDeck, VerbEntry } from './types'

const today = new Date().toISOString()

export const bookB1Topics: SkillTopic[] = [
  {
    id: 'articles-adjectives-b1',
    level: 'B1',
    area: 'Description',
    titleEn: 'Articles, Plurals, and Adjective Agreement',
    titleFr: 'Les articles, le pluriel et l accord de l adjectif',
    explanationEn:
      'At B1, learners refine article choice, plural endings, adjective position, and adjective agreement in gender and number.',
    explanationFr:
      'Au niveau B1, on affine le choix des articles, les marques du pluriel, la place de l adjectif et son accord en genre et en nombre.',
    examples: ['un bel objet', 'des evenements mondiaux', 'une experience unique'],
    confidence: 6,
    difficulty: 3,
    estimatedMinutes: 10,
    sequence: 301,
    source: 'seed',
  },
  {
    id: 'nominalisation-b1',
    level: 'B1',
    area: 'Academic French',
    titleEn: 'Nominalisation',
    titleFr: 'La nominalisation',
    explanationEn:
      'Nominalisation condenses an idea by turning a verb or adjective into a noun, especially in formal or written French.',
    explanationFr:
      'La nominalisation permet de condenser une idee en transformant un verbe ou un adjectif en nom, surtout a l ecrit.',
    examples: ['douter -> le doute', 'contradictoire -> une contradiction', 'sceptique -> le scepticisme'],
    confidence: 6,
    difficulty: 3,
    estimatedMinutes: 10,
    sequence: 302,
    source: 'seed',
  },
  {
    id: 'truncation-b1',
    level: 'B1',
    area: 'Vocabulary',
    titleEn: 'Word Shortening in Everyday Speech',
    titleFr: 'La troncation',
    explanationEn: 'French often shortens common words in speech: ordinateur -> ordi, professeur -> prof, autocar -> car.',
    explanationFr: 'Le francais oral raccourcit souvent des mots courants : ordinateur -> ordi, professeur -> prof, autocar -> car.',
    examples: ['ordi', 'cine', 'prof', 'car'],
    confidence: 6,
    difficulty: 3,
    estimatedMinutes: 8,
    sequence: 303,
    source: 'seed',
  },
  {
    id: 'negation-b1',
    level: 'B1',
    area: 'Negation',
    titleEn: 'Extended Negation',
    titleFr: 'La negation',
    explanationEn:
      'B1 uses ne...pas, ne...rien, ne...personne, ne...jamais, and ne...plus with simple, compound, and imperative forms.',
    explanationFr:
      'Au niveau B1, on utilise ne...pas, ne...rien, ne...personne, ne...jamais et ne...plus avec les temps simples, composes et l imperatif.',
    examples: ['Je ne comprends pas.', 'Il n aime rien.', 'Ne lisez pas.'],
    confidence: 6,
    difficulty: 3,
    estimatedMinutes: 10,
    sequence: 304,
    source: 'seed',
  },
  {
    id: 'prepositions-b1',
    level: 'B1',
    area: 'Prepositions',
    titleEn: 'Prepositions of Place, Means, and Verb Patterns',
    titleFr: 'Les prepositions',
    explanationEn:
      'B1 learners need precise prepositions for place, transport, material, and verb constructions such as profiter de or ouvrir a.',
    explanationFr:
      'Au niveau B1, on a besoin de prepositions precises pour le lieu, le moyen, la matiere et certaines constructions verbales comme profiter de ou ouvrir a.',
    examples: ['au bord de la Seine', 'a velo', 'en metal', 'profiter de quelque chose'],
    confidence: 6,
    difficulty: 3,
    estimatedMinutes: 10,
    sequence: 305,
    source: 'seed',
  },
  {
    id: 'relative-simple-b1',
    level: 'B1',
    area: 'Complex Sentences',
    titleEn: 'Simple Relative Pronouns',
    titleFr: 'Les pronoms relatifs simples',
    explanationEn: 'Use qui for the subject, que for the direct object, ou for place or time, and dont after de.',
    explanationFr: 'On utilise qui pour le sujet, que pour le COD, ou pour le lieu ou le temps, et dont apres de.',
    examples: ['la femme qui parle', 'le livre que j ai lu', 'la ville ou j habite', 'le sujet dont on parle'],
    confidence: 6,
    difficulty: 3,
    estimatedMinutes: 10,
    sequence: 306,
    source: 'seed',
  },
  {
    id: 'relative-complex-b1',
    level: 'B1',
    area: 'Complex Sentences',
    titleEn: 'Compound Relative Pronouns',
    titleFr: 'Les pronoms relatifs composes',
    explanationEn:
      'Lequel, laquelle, lesquels, lesquelles and their forms with a/de are used after prepositions to refer back clearly.',
    explanationFr:
      'Lequel, laquelle, lesquels, lesquelles et leurs formes avec a/de s emploient apres une preposition pour reprendre un element avec precision.',
    examples: ['la montre avec laquelle tu lis tes SMS', 'les capteurs grace auxquels les mouvements sont analyses'],
    confidence: 6,
    difficulty: 3,
    estimatedMinutes: 10,
    sequence: 307,
    source: 'seed',
  },
  {
    id: 'focus-cleft-b1',
    level: 'B1',
    area: 'Sentence Patterns',
    titleEn: 'Emphasis with ce qui / ce que / ce dont / ce a quoi',
    titleFr: 'La mise en relief',
    explanationEn:
      'Use c est ce qui / ce que / ce dont / ce a quoi or the reversed pattern to highlight an idea strongly.',
    explanationFr:
      'On utilise c est ce qui / ce que / ce dont / ce a quoi, ou la structure inverse, pour mettre une idee en relief.',
    examples: ['Ce que j aime, c est le cinema.', 'Le charme, c est ce a quoi je pense.'],
    confidence: 6,
    difficulty: 3,
    estimatedMinutes: 8,
    sequence: 308,
    source: 'seed',
  },
  {
    id: 'object-pronouns-b1',
    level: 'B1',
    area: 'Pronouns',
    titleEn: 'Direct and Indirect Object Pronouns',
    titleFr: 'Les pronoms complements',
    explanationEn:
      'Object pronouns replace nouns and usually come before the verb, before the infinitive, or between a conjugated verb and an infinitive.',
    explanationFr:
      'Les pronoms remplacent un nom et se placent generalement avant le verbe, avant l infinitif ou entre un verbe conjugue et un infinitif.',
    examples: ['Je le vois.', 'Impossible de le voir.', 'Je peux le faire.', 'Je lui telephone.'],
    confidence: 6,
    difficulty: 3,
    estimatedMinutes: 10,
    sequence: 309,
    source: 'seed',
  },
  {
    id: 'y-en-b1',
    level: 'B1',
    area: 'Pronouns',
    titleEn: 'Y and En',
    titleFr: 'Les pronoms y et en',
    explanationEn:
      'Y replaces a place or a complement with a, while en replaces quantities and complements introduced by de.',
    explanationFr:
      'Y remplace un lieu ou un complement introduit par a, tandis que en remplace une quantite ou un complement introduit par de.',
    examples: ["J y vais.", "J y pense.", "On en parle.", "J en veux deux."],
    confidence: 6,
    difficulty: 3,
    estimatedMinutes: 10,
    sequence: 310,
    source: 'seed',
  },
  {
    id: 'double-pronouns-b1',
    level: 'B1',
    area: 'Pronouns',
    titleEn: 'Double Pronoun Order',
    titleFr: 'La place des doubles pronoms',
    explanationEn:
      'When two object pronouns appear together, French follows a fixed order. In the affirmative imperative, pronouns come after the verb.',
    explanationFr:
      'Quand deux pronoms apparaissent ensemble, le francais suit un ordre fixe. A l imperatif affirmatif, ils se placent apres le verbe.',
    examples: ['Je la lui prete.', 'Vous vous y interessez ?', 'Montrez-la-moi.'],
    confidence: 6,
    difficulty: 3,
    estimatedMinutes: 10,
    sequence: 311,
    source: 'seed',
  },
  {
    id: 'indefinites-b1',
    level: 'B1',
    area: 'Pronouns',
    titleEn: 'Indefinite Words and Pronouns',
    titleFr: 'Les indefinis',
    explanationEn:
      'Use indefinites like chacun, quelques, quelqu un, personne, rien, partout, ailleurs, and n importe ou to generalize.',
    explanationFr:
      'On utilise des indefinis comme chacun, quelques, quelqu un, personne, rien, partout, ailleurs et n importe ou pour generaliser.',
    examples: ['Chacun est libre.', 'Je ne veux rien.', 'Comme partout dans le monde...'],
    confidence: 6,
    difficulty: 3,
    estimatedMinutes: 8,
    sequence: 312,
    source: 'seed',
  },
  {
    id: 'interrogative-pronouns-b1',
    level: 'B1',
    area: 'Questions',
    titleEn: 'Interrogative Pronouns',
    titleFr: 'Les pronoms interrogatifs',
    explanationEn: 'Simple and compound interrogative pronouns help ask which one inside a set: qui, lequel, laquelle, lesquels, lesquelles.',
    explanationFr: 'Les pronoms interrogatifs simples ou composes servent a demander lequel dans un ensemble : qui, lequel, laquelle, lesquels, lesquelles.',
    examples: ['Lequel de ces tableaux te plait ?', 'Laquelle vas-tu mettre ?'],
    confidence: 6,
    difficulty: 3,
    estimatedMinutes: 8,
    sequence: 313,
    source: 'seed',
  },
  {
    id: 'demonstrative-pronouns-b1',
    level: 'B1',
    area: 'Pronouns',
    titleEn: 'Demonstrative Pronouns',
    titleFr: 'Les pronoms demonstratifs',
    explanationEn:
      'Celui, celle, ceux, celles and the -ci / -la forms replace a noun you want to identify, contrast, or describe.',
    explanationFr:
      'Celui, celle, ceux, celles et les formes en -ci / -la remplacent un nom que l on veut identifier, opposer ou decrire.',
    examples: ['Lequel ? Celui-la.', 'Celle-ci est vraiment belle.', 'Celui qui ronfle.'],
    confidence: 6,
    difficulty: 3,
    estimatedMinutes: 8,
    sequence: 314,
    source: 'seed',
  },
  {
    id: 'adverbs-modalization-b1',
    level: 'B1',
    area: 'Adverbs',
    titleEn: 'Adverbs and Modalisation',
    titleFr: 'Les adverbes et la modalisation',
    explanationEn:
      'B1 uses adverbs to nuance meaning and modalisers to express certainty, doubt, appreciation, or attenuation.',
    explanationFr:
      'Au niveau B1, les adverbes servent a nuancer le sens et les modalisateurs a exprimer la certitude, le doute, l appreciation ou l attenuation.',
    examples: ['vraiment', 'franchement', 'evidemment', 'peut-etre', 'plutot interessant'],
    confidence: 6,
    difficulty: 3,
    estimatedMinutes: 8,
    sequence: 315,
    source: 'seed',
  },
  {
    id: 'gerund-b1',
    level: 'B1',
    area: 'Verbs',
    titleEn: 'Gerund for Manner and Simultaneity',
    titleFr: 'Le gerondif',
    explanationEn:
      'The gerund with en + present participle can express manner or simultaneity, and the subject stays the same as the main clause.',
    explanationFr:
      'Le gerondif avec en + participe present peut exprimer la maniere ou la simultaneite, et le sujet reste le meme que dans la proposition principale.',
    examples: ['en regardant la tele', 'en presentant les rapports', 'en le regardant dans les yeux'],
    confidence: 6,
    difficulty: 3,
    estimatedMinutes: 8,
    sequence: 316,
    source: 'seed',
  },
  {
    id: 'plus-que-parfait-b1',
    level: 'B1',
    area: 'Past',
    titleEn: 'Plus-que-parfait and Narrative Sequencing',
    titleFr: 'Le plus-que-parfait',
    explanationEn:
      'Use the plus-que-parfait to show that one past action happened before another past action.',
    explanationFr:
      'On utilise le plus-que-parfait pour montrer qu une action passee est anterieure a une autre action passee.',
    examples: ['Il avait passe une annee avec son pere.', 'Quand il etait arrive, tout avait change.'],
    confidence: 6,
    difficulty: 3,
    estimatedMinutes: 10,
    sequence: 317,
    source: 'seed',
  },
  {
    id: 'passe-simple-b1',
    level: 'B1',
    area: 'Past',
    titleEn: 'Passe Simple Recognition',
    titleFr: 'Le passe simple',
    explanationEn:
      'The passe simple is mainly a reading tense found in biographies, literature, and historical texts, often with il/elle/on and ils/elles.',
    explanationFr:
      'Le passe simple est surtout un temps de lecture present dans les biographies, les romans et les textes historiques, souvent avec il/elle/on et ils/elles.',
    examples: ['il quitta', 'ils allerent', 'il fut', 'ils vinrent'],
    confidence: 6,
    difficulty: 3,
    estimatedMinutes: 10,
    sequence: 318,
    source: 'seed',
  },
  {
    id: 'passive-b1',
    level: 'B1',
    area: 'Sentence Patterns',
    titleEn: 'Passive Voice',
    titleFr: 'La forme passive',
    explanationEn:
      'In the passive voice, the direct object becomes the subject and the old subject can appear as the agent with par.',
    explanationFr:
      'Dans la forme passive, l ancien COD devient sujet et l ancien sujet peut apparaitre comme complement d agent avec par.',
    examples: ['Des calories ont ete brulees.', 'Toutes ces informations sont partagees par tous.'],
    confidence: 6,
    difficulty: 3,
    estimatedMinutes: 10,
    sequence: 319,
    source: 'seed',
  },
  {
    id: 'time-connectors-b1',
    level: 'B1',
    area: 'Time',
    titleEn: 'Narrative Time Markers',
    titleFr: 'Les reperes du temps',
    explanationEn:
      'Narration at B1 relies on time markers to show chronology, anteriority, and duration across events.',
    explanationFr:
      'Le recit au niveau B1 s appuie sur des reperes temporels pour marquer la chronologie, l anteriorite et la duree.',
    examples: ['quand il avait cinq ans', 'x ans plus tard', 'a l age de 24 ans'],
    confidence: 6,
    difficulty: 3,
    estimatedMinutes: 8,
    sequence: 320,
    source: 'seed',
  },
  {
    id: 'future-conditional-b1',
    level: 'B1',
    area: 'Future and Mood',
    titleEn: 'Future and Conditional Patterns',
    titleFr: 'Le futur et le conditionnel',
    explanationEn:
      'B1 strengthens future simple, conditional present, and conditional past for plans, hypotheses, and politeness.',
    explanationFr:
      'Au niveau B1, on renforce le futur simple, le conditionnel present et le conditionnel passe pour parler de projets, d hypotheses et de politesse.',
    examples: ['je vivrai', 'je voudrais', 'j aurais vecu'],
    confidence: 6,
    difficulty: 3,
    estimatedMinutes: 10,
    sequence: 321,
    source: 'seed',
  },
  {
    id: 'hypothesis-obligation-b1',
    level: 'B1',
    area: 'Complex Sentences',
    titleEn: 'Hypothesis, Obligation, and Judgement',
    titleFr: 'L hypothese, l obligation et le jugement',
    explanationEn:
      'B1 combines structures for condition, necessity, and judgement to argue more precisely in speech and writing.',
    explanationFr:
      'Le niveau B1 combine des structures de condition, de necessite et de jugement pour argumenter avec plus de precision a l oral et a l ecrit.',
    examples: ['Si tu venais, ce serait plus simple.', 'Il faut que tu viennes.', 'C est vraiment interessant.'],
    confidence: 6,
    difficulty: 3,
    estimatedMinutes: 10,
    sequence: 322,
    source: 'seed',
  },
]

export const bookB1Questions: Question[] = [
  {
    id: 'q-articles-adjectives-b1-1',
    topicId: 'articles-adjectives-b1',
    type: 'multiple-choice',
    promptEn: 'Choose the correct form: un ___ objet',
    promptFr: 'Choisissez la forme correcte : un ___ objet',
    choices: ['beau', 'bel', 'belle', 'beaux'],
    correctAnswer: 'bel',
    explanationEn: 'Bel is used before a masculine singular noun beginning with a vowel.',
    explanationFr: 'Bel s emploie devant un nom masculin singulier commencant par une voyelle.',
  },
  {
    id: 'q-nominalisation-b1-1',
    topicId: 'nominalisation-b1',
    type: 'multiple-choice',
    promptEn: 'Which noun comes from the verb douter ?',
    promptFr: 'Quel nom vient du verbe douter ?',
    choices: ['le doute', 'le douter', 'la douterie', 'le doutement'],
    correctAnswer: 'le doute',
    explanationEn: 'Le doute is the noun formed from douter.',
    explanationFr: 'Le doute est le nom forme a partir de douter.',
  },
  {
    id: 'q-truncation-b1-1',
    topicId: 'truncation-b1',
    type: 'multiple-choice',
    promptEn: 'Which shortened form matches ordinateur ?',
    promptFr: 'Quelle forme raccourcie correspond a ordinateur ?',
    choices: ['ordi', 'ord', 'dinat', 'teur'],
    correctAnswer: 'ordi',
    explanationEn: 'Ordi is the common truncation of ordinateur.',
    explanationFr: 'Ordi est la troncation courante de ordinateur.',
  },
  {
    id: 'q-negation-b1-1',
    topicId: 'negation-b1',
    type: 'multiple-choice',
    promptEn: 'Choose the correct sentence with a negative indefinite.',
    promptFr: 'Choisissez la phrase correcte avec un indefini negatif.',
    choices: ['On ne connait personne.', 'On connait ne personne.', 'On personne connait.', 'On ne personne connait.'],
    correctAnswer: 'On ne connait personne.',
    explanationEn: 'Personne completes the negation around the verb.',
    explanationFr: 'Personne complete la negation autour du verbe.',
  },
  {
    id: 'q-prepositions-b1-1',
    topicId: 'prepositions-b1',
    type: 'multiple-choice',
    promptEn: 'Choose the preposition of means: Françoise va travailler ___ velo.',
    promptFr: 'Choisissez la preposition de moyen : Francoise va travailler ___ velo.',
    choices: ['a', 'en', 'de', 'sur'],
    correctAnswer: 'a',
    explanationEn: 'A velo is the correct expression for means of transport here.',
    explanationFr: 'A velo est l expression correcte pour exprimer le moyen de transport ici.',
  },
  {
    id: 'q-relative-simple-b1-1',
    topicId: 'relative-simple-b1',
    type: 'multiple-choice',
    promptEn: 'Choose: Le sujet ___ on parle est delicat.',
    promptFr: 'Choisissez : Le sujet ___ on parle est delicat.',
    choices: ['qui', 'que', 'dont', 'ou'],
    correctAnswer: 'dont',
    explanationEn: 'Parler de takes dont in a relative clause.',
    explanationFr: 'Parler de appelle dont dans une relative.',
  },
  {
    id: 'q-relative-complex-b1-1',
    topicId: 'relative-complex-b1',
    type: 'multiple-choice',
    promptEn: 'Complete: La montre avec ___ tu peux lire tes SMS.',
    promptFr: 'Completez : La montre avec ___ tu peux lire tes SMS.',
    choices: ['qui', 'que', 'laquelle', 'dont'],
    correctAnswer: 'laquelle',
    explanationEn: 'After a preposition, a compound relative pronoun is needed here.',
    explanationFr: 'Apres une preposition, on emploie ici un pronom relatif compose.',
  },
  {
    id: 'q-focus-cleft-b1-1',
    topicId: 'focus-cleft-b1',
    type: 'multiple-choice',
    promptEn: 'Choose the sentence that highlights an idea with ce que... c est.',
    promptFr: 'Choisissez la phrase qui met une idee en relief avec ce que... c est.',
    choices: ['Ce que j aime, c est lire.', 'Je aime lire ce que.', 'C est aime je lire.', 'Lire ce que j aime.'],
    correctAnswer: 'Ce que j aime, c est lire.',
    explanationEn: 'This pattern foregrounds the idea clearly.',
    explanationFr: 'Cette structure met clairement l idee en relief.',
  },
  {
    id: 'q-object-pronouns-b1-1',
    topicId: 'object-pronouns-b1',
    type: 'multiple-choice',
    promptEn: 'Replace a Charlotte: Je telephone a Charlotte.',
    promptFr: 'Remplacez a Charlotte : Je telephone a Charlotte.',
    choices: ['Je la telephone.', 'Je lui telephone.', 'Je le telephone.', 'J en telephone.'],
    correctAnswer: 'Je lui telephone.',
    explanationEn: 'Telephone a takes the indirect object pronoun lui.',
    explanationFr: 'Telephoner a appelle le pronom COI lui.',
  },
  {
    id: 'q-y-en-b1-1',
    topicId: 'y-en-b1',
    type: 'multiple-choice',
    promptEn: 'Replace a acheter un bracelet connecte ? in Oui, je pense parfois a acheter un bracelet connecte.',
    promptFr: 'Remplacez a acheter un bracelet connecte dans Oui, je pense parfois a acheter un bracelet connecte.',
    choices: ['j en pense parfois', 'j y pense parfois', 'je le pense parfois', 'je lui pense parfois'],
    correctAnswer: 'j y pense parfois',
    explanationEn: 'Penser a takes y when replaced.',
    explanationFr: 'Penser a se remplace par y.',
  },
  {
    id: 'q-double-pronouns-b1-1',
    topicId: 'double-pronouns-b1',
    type: 'multiple-choice',
    promptEn: 'Choose the correct order.',
    promptFr: 'Choisissez le bon ordre.',
    choices: ['Je la lui prete.', 'Je lui la prete.', 'Je prete la lui.', 'Je la prete lui.'],
    correctAnswer: 'Je la lui prete.',
    explanationEn: 'COD comes before lui/leur in this pattern.',
    explanationFr: 'Le COD se place avant lui/leur dans cette structure.',
  },
  {
    id: 'q-indefinites-b1-1',
    topicId: 'indefinites-b1',
    type: 'multiple-choice',
    promptEn: 'Which word refers only to things in a negative sentence?',
    promptFr: 'Quel mot renvoie seulement aux choses dans une phrase negative ?',
    choices: ['quelqu un', 'partout', 'rien', 'chacun'],
    correctAnswer: 'rien',
    explanationEn: 'Rien refers to things and is used in negative meaning.',
    explanationFr: 'Rien renvoie aux choses avec une valeur negative.',
  },
  {
    id: 'q-interrogative-pronouns-b1-1',
    topicId: 'interrogative-pronouns-b1',
    type: 'multiple-choice',
    promptEn: 'Choose the correct pronoun: Tu as trois vestes. ___ vas-tu mettre ?',
    promptFr: 'Choisissez le bon pronom : Tu as trois vestes. ___ vas-tu mettre ?',
    choices: ['Qui', 'Lequel', 'Laquelle', 'Lesquels'],
    correctAnswer: 'Laquelle',
    explanationEn: 'Laquelle agrees with veste, which is feminine singular.',
    explanationFr: 'Laquelle s accorde avec veste, feminin singulier.',
  },
  {
    id: 'q-demonstrative-pronouns-b1-1',
    topicId: 'demonstrative-pronouns-b1',
    type: 'multiple-choice',
    promptEn: 'Complete: Lequel ? ___-la.',
    promptFr: 'Completez : Lequel ? ___-la.',
    choices: ['Celui', 'Ce', 'Le', 'Quel'],
    correctAnswer: 'Celui',
    explanationEn: 'Celui-la points to one masculine singular item.',
    explanationFr: 'Celui-la designe un element masculin singulier.',
  },
  {
    id: 'q-adverbs-modalization-b1-1',
    topicId: 'adverbs-modalization-b1',
    type: 'multiple-choice',
    promptEn: 'Which adverb expresses uncertainty?',
    promptFr: 'Quel adverbe exprime l incertitude ?',
    choices: ['certainement', 'peut-etre', 'vraiment', 'franchement'],
    correctAnswer: 'peut-etre',
    explanationEn: 'Peut-etre marks uncertainty.',
    explanationFr: 'Peut-etre marque l incertitude.',
  },
  {
    id: 'q-gerund-b1-1',
    topicId: 'gerund-b1',
    type: 'multiple-choice',
    promptEn: 'Choose the sentence where the gerund expresses simultaneity.',
    promptFr: 'Choisissez la phrase ou le gerondif exprime la simultaneite.',
    choices: ['Il s est endormi en regardant la tele.', 'Il adore regarder la tele.', 'Il regardera la tele demain.', 'Il a regarde la tele hier.'],
    correctAnswer: 'Il s est endormi en regardant la tele.',
    explanationEn: 'The falling asleep and watching happen at the same time.',
    explanationFr: 'L action de s endormir et celle de regarder se passent en meme temps.',
  },
  {
    id: 'q-plus-que-parfait-b1-1',
    topicId: 'plus-que-parfait-b1',
    type: 'fill',
    promptEn: 'Complete: Quand il est revenu, il ___ deja ___ une annee a Paris. (avoir / passer)',
    promptFr: 'Completez : Quand il est revenu, il ___ deja ___ une annee a Paris. (avoir / passer)',
    correctAnswer: 'avait deja passe',
    explanationEn: 'The earlier past action uses the plus-que-parfait.',
    explanationFr: 'L action anterieure se met au plus-que-parfait.',
  },
  {
    id: 'q-passe-simple-b1-1',
    topicId: 'passe-simple-b1',
    type: 'multiple-choice',
    promptEn: 'Which form is in the passe simple?',
    promptFr: 'Quelle forme est au passe simple ?',
    choices: ['il quitta', 'il a quitte', 'il quittait', 'il va quitter'],
    correctAnswer: 'il quitta',
    explanationEn: 'Il quitta is a passe simple form used in written narration.',
    explanationFr: 'Il quitta est une forme de passe simple employee dans le recit ecrit.',
  },
  {
    id: 'q-passive-b1-1',
    topicId: 'passive-b1',
    type: 'multiple-choice',
    promptEn: 'Choose the passive sentence.',
    promptFr: 'Choisissez la phrase passive.',
    choices: ['Des calories ont ete brulees.', 'Alice a brule des calories.', 'Alice brule des calories.', 'Alice brulera des calories.'],
    correctAnswer: 'Des calories ont ete brulees.',
    explanationEn: 'The old direct object becomes the passive subject.',
    explanationFr: 'L ancien COD devient le sujet de la phrase passive.',
  },
  {
    id: 'q-time-connectors-b1-1',
    topicId: 'time-connectors-b1',
    type: 'multiple-choice',
    promptEn: 'Which expression marks posteriority in a narrative?',
    promptFr: 'Quelle expression marque la posteriorite dans un recit ?',
    choices: ['x ans plus tard', 'quand il avait cinq ans', 'au moment ou', 'depuis six mois'],
    correctAnswer: 'x ans plus tard',
    explanationEn: 'X years later clearly pushes the story forward in time.',
    explanationFr: 'X ans plus tard fait avancer clairement le recit dans le temps.',
  },
  {
    id: 'q-future-conditional-b1-1',
    topicId: 'future-conditional-b1',
    type: 'multiple-choice',
    promptEn: 'Choose the polite conditional sentence.',
    promptFr: 'Choisissez la phrase polie au conditionnel.',
    choices: ['Je voudrais plus de temps.', 'Je veux plus de temps.', 'J ai voulu plus de temps.', 'Je vais vouloir plus de temps.'],
    correctAnswer: 'Je voudrais plus de temps.',
    explanationEn: 'Je voudrais is the polite conditional form.',
    explanationFr: 'Je voudrais est la forme polie du conditionnel.',
  },
  {
    id: 'q-hypothesis-obligation-b1-1',
    topicId: 'hypothesis-obligation-b1',
    type: 'multiple-choice',
    promptEn: 'Choose the sentence of obligation with a subject change.',
    promptFr: 'Choisissez la phrase d obligation avec changement de sujet.',
    choices: ['Il faut que tu viennes.', 'Il faut venir.', 'Tu viens demain.', 'Je viendrai demain.'],
    correctAnswer: 'Il faut que tu viennes.',
    explanationEn: 'Il faut que + subjunctive is used when the subject changes.',
    explanationFr: 'Il faut que + subjonctif s emploie quand le sujet change.',
  },
]

const deckRows: Array<[string, string, string, string[]]> = [
  ['book-b1-work-society', 'B1 Work and Society', 'Totem 3 vocabulary for work, employment, responsibility, and public life.', ['book', 'b1', 'work']],
  ['book-b1-beliefs-debate', 'B1 Beliefs and Debate', 'Totem 3 vocabulary for beliefs, judgement, criticism, and debate.', ['book', 'b1', 'debate']],
  ['book-b1-technology-objects', 'B1 Technology and Objects', 'Totem 3 vocabulary for connected objects, design, and technical tools.', ['book', 'b1', 'technology']],
  ['book-b1-health-body', 'B1 Health and the Body', 'Totem 3 words for health, body, wellbeing, and physical state.', ['book', 'b1', 'health']],
  ['book-b1-relationships-lifestyle', 'B1 Relationships and Lifestyle', 'Totem 3 vocabulary for family, relationships, daily roles, and personal life.', ['book', 'b1', 'relationships']],
]

export const bookB1Decks: VocabDeck[] = deckRows.map(([id, title, description, tags], index) => ({
  id,
  title,
  description,
  level: 'B1',
  tags,
  difficulty: 3,
  estimatedMinutes: 20,
  sequence: 400 + index,
  source: 'seed',
}))

const cardRows: Array<[string, string, string, VocabCard['gender'] | undefined, string, string, string]> = [
  ['book-b1-work-society', 'la creation d emploi', 'job creation', 'f', 'La creation d emploi reste une priorite.', 'Job creation remains a priority.', 'work'],
  ['book-b1-work-society', 'la crise economique', 'economic crisis', 'f', 'La crise economique a change le marche du travail.', 'The economic crisis changed the labour market.', 'society'],
  ['book-b1-work-society', 'le marche du travail', 'labour market', 'm', 'Le marche du travail devient plus competitif.', 'The labour market is becoming more competitive.', 'work'],
  ['book-b1-work-society', 'les metiers administratifs', 'administrative jobs', undefined, 'Les metiers administratifs demandent de la rigueur.', 'Administrative jobs require precision.', 'work'],
  ['book-b1-work-society', 'un salarie / une salariee', 'employee', 'm/f', 'Chaque salarie a des droits.', 'Every employee has rights.', 'work'],
  ['book-b1-work-society', 'responsable', 'responsible', undefined, 'Elle est responsable de son equipe.', 'She is responsible for her team.', 'work'],
  ['book-b1-work-society', 'le revenu', 'income', 'm', 'Le revenu varie selon le secteur.', 'Income varies according to the sector.', 'society'],
  ['book-b1-work-society', 'remunerer', 'to pay / remunerate', undefined, 'Il faut mieux remunerer certains metiers.', 'Some jobs need to be paid better.', 'work'],
  ['book-b1-work-society', 'la retraite', 'retirement', 'f', 'Il pense deja a la retraite.', 'He is already thinking about retirement.', 'society'],
  ['book-b1-work-society', 'le secteur', 'sector', 'm', 'Le secteur public recrute encore.', 'The public sector is still hiring.', 'work'],
  ['book-b1-work-society', 'les services', 'services', undefined, 'Le secteur des services se developpe.', 'The service sector is growing.', 'work'],
  ['book-b1-work-society', 's engager', 'to commit oneself', undefined, 'De plus en plus de jeunes veulent s engager.', 'More and more young people want to get involved.', 'society'],

  ['book-b1-beliefs-debate', 'la croyance populaire', 'popular belief', 'f', 'Cette croyance populaire existe encore.', 'That popular belief still exists.', 'beliefs'],
  ['book-b1-beliefs-debate', 'la critique', 'criticism', 'f', 'La critique etait severe mais utile.', 'The criticism was harsh but useful.', 'debate'],
  ['book-b1-beliefs-debate', 'un debat', 'debate', 'm', 'Le debat a dure toute la soiree.', 'The debate lasted all evening.', 'debate'],
  ['book-b1-beliefs-debate', 'debattre', 'to debate', undefined, 'Ils aiment debattre de questions de societe.', 'They like debating social issues.', 'debate'],
  ['book-b1-beliefs-debate', 'le doute', 'doubt', 'm', 'Le doute reste present.', 'Doubt remains present.', 'beliefs'],
  ['book-b1-beliefs-debate', 'le scepticisme', 'skepticism', 'm', 'Le scepticisme augmente face aux rumeurs.', 'Skepticism is increasing in the face of rumours.', 'beliefs'],
  ['book-b1-beliefs-debate', 'la liberte d expression', 'freedom of expression', 'f', 'La liberte d expression est essentielle.', 'Freedom of expression is essential.', 'society'],
  ['book-b1-beliefs-debate', 'la liberte de parole', 'freedom of speech', 'f', 'La liberte de parole doit etre defendue.', 'Freedom of speech must be defended.', 'society'],
  ['book-b1-beliefs-debate', 'representer', 'to represent', undefined, 'Ce symbole represente une epoque.', 'That symbol represents an era.', 'debate'],
  ['book-b1-beliefs-debate', 'la reputation', 'reputation', 'f', 'La marque a une bonne reputation.', 'The brand has a good reputation.', 'debate'],
  ['book-b1-beliefs-debate', 'la contradiction', 'contradiction', 'f', 'Cette contradiction saute aux yeux.', 'That contradiction is obvious.', 'debate'],
  ['book-b1-beliefs-debate', 'donner un sens a sa vie', 'to give meaning to one s life', undefined, 'Le travail peut donner un sens a sa vie.', 'Work can give meaning to one s life.', 'beliefs'],

  ['book-b1-technology-objects', 'la coque de telephone', 'phone case', 'f', 'La coque de telephone est abimee.', 'The phone case is damaged.', 'technology'],
  ['book-b1-technology-objects', 'le design', 'design', 'm', 'Le design de cette montre est elegant.', 'The design of this watch is elegant.', 'technology'],
  ['book-b1-technology-objects', 'le dispositif', 'device / mechanism', 'm', 'Ce dispositif mesure les mouvements.', 'This device measures movements.', 'technology'],
  ['book-b1-technology-objects', 'les donnees', 'data', undefined, 'Les donnees sont stockees en ligne.', 'The data is stored online.', 'technology'],
  ['book-b1-technology-objects', 'la domotique', 'home automation', 'f', 'La domotique transforme la maison.', 'Home automation is transforming the home.', 'technology'],
  ['book-b1-technology-objects', 'le localisateur GPS', 'GPS locator', 'm', 'Le localisateur GPS aide a retrouver l objet.', 'The GPS locator helps find the object.', 'technology'],
  ['book-b1-technology-objects', 'localiser', 'to locate', undefined, 'On peut localiser le vehicule a distance.', 'You can locate the vehicle remotely.', 'technology'],
  ['book-b1-technology-objects', 'modifier', 'to modify', undefined, 'Il faut modifier les reglages.', 'The settings need to be changed.', 'technology'],
  ['book-b1-technology-objects', 'la montre', 'watch', 'f', 'Cette montre est connectee.', 'This watch is connected.', 'technology'],
  ['book-b1-technology-objects', 'le thermostat', 'thermostat', 'm', 'Le thermostat regle la temperature.', 'The thermostat controls the temperature.', 'technology'],
  ['book-b1-technology-objects', 'robotique', 'robotics', 'f', 'La robotique entre dans le quotidien.', 'Robotics is entering everyday life.', 'technology'],
  ['book-b1-technology-objects', 'synchronise', 'synchronised', undefined, 'Tous les appareils sont synchronises.', 'All the devices are synchronised.', 'technology'],

  ['book-b1-health-body', 'le coup de soleil', 'sun stroke / sunburn', 'm', 'Il a attrape un coup de soleil a la plage.', 'He got sunstroke at the beach.', 'health'],
  ['book-b1-health-body', 'la douleur', 'pain', 'f', 'La douleur a disparu rapidement.', 'The pain disappeared quickly.', 'health'],
  ['book-b1-health-body', 'la sante', 'health', 'f', 'La sante passe avant le reste.', 'Health comes before everything else.', 'health'],
  ['book-b1-health-body', 'les mineraux', 'minerals', undefined, 'Cette eau est riche en mineraux.', 'This water is rich in minerals.', 'health'],
  ['book-b1-health-body', 'la minceur', 'thinness', 'f', 'La publicite vend souvent la minceur comme ideal.', 'Advertising often sells thinness as an ideal.', 'body'],
  ['book-b1-health-body', 'le rein', 'kidney', 'm', 'Le medecin a verifie le rein gauche.', 'The doctor checked the left kidney.', 'body'],
  ['book-b1-health-body', 'le stethoscope', 'stethoscope', 'm', 'Le stethoscope est sur le bureau du medecin.', 'The stethoscope is on the doctor s desk.', 'health'],
  ['book-b1-health-body', 'la vitalite', 'vitality', 'f', 'Le sport redonne de la vitalite.', 'Exercise gives vitality back.', 'health'],
  ['book-b1-health-body', 'se sentir soutenu', 'to feel supported', undefined, 'On apprend mieux quand on se sent soutenu.', 'You learn better when you feel supported.', 'wellbeing'],
  ['book-b1-health-body', 'se sculpter son corps', 'to sculpt one s body', undefined, 'Il veut se sculpter son corps avant l ete.', 'He wants to sculpt his body before summer.', 'body'],
  ['book-b1-health-body', 'se baigner', 'to bathe / swim', undefined, 'On aime se baigner dans la riviere.', 'We like swimming in the river.', 'body'],
  ['book-b1-health-body', 'sentir mauvais', 'to smell bad', undefined, 'Ces chaussures sentent mauvais.', 'These shoes smell bad.', 'body'],

  ['book-b1-relationships-lifestyle', 'le couple', 'couple', 'm', 'Ce couple vit ensemble depuis dix ans.', 'This couple has lived together for ten years.', 'relationships'],
  ['book-b1-relationships-lifestyle', 'developper une amitie', 'to develop a friendship', undefined, 'Ils ont developpe une amitie durable.', 'They developed a lasting friendship.', 'relationships'],
  ['book-b1-relationships-lifestyle', 'divorcer', 'to divorce', undefined, 'Ils ont decide de divorcer.', 'They decided to divorce.', 'relationships'],
  ['book-b1-relationships-lifestyle', 'se marier', 'to get married', undefined, 'Ils vont se marier en juin.', 'They are getting married in June.', 'relationships'],
  ['book-b1-relationships-lifestyle', 's installer', 'to settle down', undefined, 'Ils veulent s installer a Lyon.', 'They want to settle in Lyon.', 'lifestyle'],
  ['book-b1-relationships-lifestyle', 's occuper de', 'to take care of', undefined, 'Elle s occupe de ses grands-parents.', 'She takes care of her grandparents.', 'lifestyle'],
  ['book-b1-relationships-lifestyle', 'se vetir', 'to get dressed', undefined, 'Il faut se vetir chaudement en hiver.', 'You need to get dressed warmly in winter.', 'lifestyle'],
  ['book-b1-relationships-lifestyle', 'la joie', 'joy', 'f', 'La nouvelle a ete accueillie avec joie.', 'The news was welcomed with joy.', 'feelings'],
  ['book-b1-relationships-lifestyle', 'la maman', 'mum', 'f', 'Sa maman habite encore pres de chez lui.', 'His mum still lives near him.', 'family'],
  ['book-b1-relationships-lifestyle', 'la mere', 'mother', 'f', 'Sa mere lui telephone tous les jours.', 'His mother calls him every day.', 'family'],
  ['book-b1-relationships-lifestyle', 'la rencontre', 'meeting', 'f', 'Leur rencontre a tout change.', 'Their meeting changed everything.', 'relationships'],
  ['book-b1-relationships-lifestyle', 'romantique', 'romantic', undefined, 'Le film est tres romantique.', 'The film is very romantic.', 'relationships'],
]

export const bookB1Cards: VocabCard[] = cardRows.map(
  ([deckId, frontFr, backEn, gender, exampleFr, exampleEn, tag], index) => ({
    id: `book-b1-card-${index + 1}`,
    deckId,
    frontFr,
    backEn,
    gender,
    exampleFr,
    exampleEn,
    tags: ['book-b1', tag],
    notes: 'Curated from Totem 3 pages 180 to 190.',
    confidence: 0,
    dueAt: today,
    intervalDays: 1,
    difficulty: 3,
    source: 'seed',
  }),
)

const bookVerbOrder = ['croire', 'recevoir', 'choisir', 'attendre', 'comprendre', 'vivre', 'courir', 'appartenir', 'devenir', 's interesser', 's occuper']

const normalized = (value: string) =>
  value
    .toLocaleLowerCase('fr-FR')
    .normalize('NFD')
    .replace(/\p{Diacritic}/gu, '')
    .replace(/[’']/g, ' ')
    .replace(/\s+/g, ' ')
    .trim()

export function applyBookB1VerbOverrides(verbs: VerbEntry[]) {
  const orderMap = new Map(bookVerbOrder.map((infinitive, index) => [normalized(infinitive), index]))
  verbs.forEach((verb) => {
    const order = orderMap.get(normalized(verb.infinitive))
    if (order !== undefined) {
      verb.sequence = 90 + order
      verb.level = 'B1'
      verb.difficulty = 3
      verb.estimatedMinutes = 14
      verb.source = 'seed'
    }
  })
}
