/**
 * Enriched Quiz Questions
 * Inspired by FrancaisFacile.com, Lingua.com, and other French-learning resources.
 * Questions use real-life contexts (restaurant, travel, daily routine, work, etc.)
 * and include more distractor traps, transformation tasks, and nuanced choices
 * to reduce predictability.
 */
import type { Question } from './types'

type QuestionRow = [
  topicId: string,
  type: Question['type'],
  promptEn: string,
  promptFr: string,
  choices: string[] | undefined,
  correctAnswer: string,
  explanationEn: string,
  explanationFr: string,
]

export const enrichedQuestions: Question[] = (
  [
    // ── ARTICLES AND GENDER ──────────────────────────────────────────────────
    [
      'articles-gender',
      'multiple-choice',
      'At a café, the waiter asks: "Vous prenez ___ café ou ___ thé ?" Choose the correct articles.',
      'Au café, le serveur demande : « Vous prenez ___ café ou ___ thé ? » Choisissez les bons articles.',
      ['le / le', 'un / un', 'la / le', 'un / la'],
      'un / un',
      'Both café and thé are masculine singular nouns introduced for the first time, so use un.',
      'Café et thé sont des noms masculins singuliers introduits pour la première fois, donc on utilise un.',
    ],
    [
      'articles-gender',
      'multiple-choice',
      'Which noun is feminine? (Think of its article in French.)',
      'Quel nom est féminin ? (Pensez à son article en français.)',
      ['le problème', 'la solution', 'le résultat', 'le numéro'],
      'la solution',
      'La solution is feminine; problème, résultat, and numéro are masculine.',
      'La solution est féminin ; problème, résultat et numéro sont masculins.',
    ],
    [
      'articles-gender',
      'fill',
      'Complete: Je prends ___ eau minérale, s\'il vous plaît. (use the correct definite article)',
      'Complétez : Je prends ___ eau minérale, s\'il vous plaît.',
      undefined,
      'l\'',
      'Eau begins with a vowel, so the article elides to l\'.',
      'Eau commence par une voyelle, donc l\'article s\'élide en l\'.',
    ],
    [
      'articles-gender',
      'multiple-choice',
      'You are reading a menu. Which phrase uses the article correctly?',
      'Vous lisez un menu. Quelle phrase utilise l\'article correctement ?',
      ['Je voudrais le soupe du jour.', 'Je voudrais la soupe du jour.', 'Je voudrais un soupe du jour.', 'Je voudrais des soupe du jour.'],
      'Je voudrais la soupe du jour.',
      'Soupe is feminine, so la soupe is correct.',
      'Soupe est féminin, donc la soupe est correct.',
    ],

    // ── DEFINITE ARTICLES ────────────────────────────────────────────────────
    [
      'definite-articles-a1',
      'multiple-choice',
      'Your friend says she loves cheese. Choose the correct sentence in French.',
      'Votre amie dit qu\'elle adore le fromage. Choisissez la bonne phrase en français.',
      ['Elle adore du fromage.', 'Elle adore un fromage.', 'Elle adore le fromage.', 'Elle adore de fromage.'],
      'Elle adore le fromage.',
      'For general likes and preferences in French, use the definite article: le fromage.',
      'Pour exprimer des goûts en français, on utilise l\'article défini : le fromage.',
    ],
    [
      'definite-articles-a1',
      'fill',
      'Complete: ___ vacances en France sont magnifiques !',
      'Complétez : ___ vacances en France sont magnifiques !',
      undefined,
      'Les',
      'Vacances is a plural noun; use les.',
      'Vacances est un nom pluriel ; on utilise les.',
    ],
    [
      'definite-articles-a1',
      'multiple-choice',
      'Which sentence correctly states a general fact?',
      'Quelle phrase exprime correctement un fait général ?',
      ['Les chats sont des animaux indépendants.', 'Des chats sont des animaux indépendants.', 'Un chat est des animaux indépendants.', 'De chats sont des animaux indépendants.'],
      'Les chats sont des animaux indépendants.',
      'General statements about a whole category use les.',
      'Les énoncés généraux sur une catégorie entière utilisent les.',
    ],

    // ── INDEFINITE ARTICLES ──────────────────────────────────────────────────
    [
      'indefinite-articles-a1',
      'multiple-choice',
      'You are describing your apartment for the first time. Choose the correct sentence.',
      'Vous décrivez votre appartement pour la première fois. Choisissez la bonne phrase.',
      ['Il y a le balcon.', 'Il y a un balcon.', 'Il y a balcon.', 'Il y a du balcon.'],
      'Il y a un balcon.',
      'When introducing something for the first time, use the indefinite article un.',
      'Quand on présente quelque chose pour la première fois, on utilise l\'article indéfini un.',
    ],
    [
      'indefinite-articles-a1',
      'multiple-choice',
      'In the negative, what happens to "un" and "une"? → Je n\'ai pas ___ voiture.',
      'À la forme négative, que devient « un » et « une » ? → Je n\'ai pas ___ voiture.',
      ['un', 'une', 'de', 'la'],
      'de',
      'After a negation, un/une/des become de or d\'.',
      'Après la négation, un/une/des deviennent de ou d\'.',
    ],

    // ── CONTRACTED ARTICLES ──────────────────────────────────────────────────
    [
      'contracted-articles-a1',
      'multiple-choice',
      'You want to go to the market. Which is correct?',
      'Vous voulez aller au marché. Laquelle est correcte ?',
      ['Je vais à le marché.', 'Je vais au marché.', 'Je vais à la marché.', 'Je vais du marché.'],
      'Je vais au marché.',
      'À + le = au. "À le" is never used in French.',
      'À + le = au. « À le » ne s\'utilise jamais en français.',
    ],
    [
      'contracted-articles-a1',
      'fill',
      'Complete: Le professeur parle ___ étudiants. (à + les)',
      'Complétez : Le professeur parle ___ étudiants. (à + les)',
      undefined,
      'aux',
      'À + les contracts to aux.',
      'À + les se contracte en aux.',
    ],
    [
      'contracted-articles-a1',
      'multiple-choice',
      'Choose: I am coming back from the cinema.',
      'Choisissez : Je reviens ___ cinéma.',
      ['de le cinéma', 'du cinéma', 'de la cinéma', 'des cinéma'],
      'du cinéma',
      'De + le = du. Cinéma is masculine.',
      'De + le = du. Cinéma est masculin.',
    ],

    // ── PLURAL NOUNS ─────────────────────────────────────────────────────────
    [
      'plural-nouns-a1',
      'multiple-choice',
      'What is the plural of "un journal" (newspaper)?',
      'Quel est le pluriel de « un journal » (un journal) ?',
      ['des journaux', 'des journals', 'des journales', 'des journalx'],
      'des journaux',
      'Nouns ending in -al change to -aux in the plural: journal → journaux.',
      'Les noms en -al deviennent -aux au pluriel : journal → journaux.',
    ],
    [
      'plural-nouns-a1',
      'fill',
      'Make plural: un château → des ___',
      'Mettez au pluriel : un château → des ___',
      undefined,
      'châteaux',
      'Nouns ending in -eau add -x: château → châteaux.',
      'Les noms en -eau prennent -x : château → châteaux.',
    ],
    [
      'plural-nouns-a1',
      'multiple-choice',
      'Which noun does NOT change in the plural?',
      'Quel nom ne change PAS au pluriel ?',
      ['un chat', 'un bras', 'un arbre', 'un livre'],
      'un bras',
      'Bras already ends in -s, so the plural form is identical: des bras.',
      'Bras se termine déjà par -s, donc le pluriel est identique : des bras.',
    ],

    // ── ADJECTIVE AGREEMENT ──────────────────────────────────────────────────
    [
      'adjective-agreement-a1',
      'multiple-choice',
      'Describe the house: "La maison est ___." (new)',
      'Décrivez la maison : « La maison est ___ ». (nouvelle)',
      ['neuf', 'neuve', 'nouvelle', 'novelle'],
      'nouvelle',
      'Nouveau / nouvelle is the correct feminine form for "new".',
      'Nouveau / nouvelle est la forme féminine correcte pour « new ».',
    ],
    [
      'adjective-agreement-a1',
      'fill',
      'Complete: Ces étudiantes sont très ___ (sérieux).',
      'Complétez : Ces étudiantes sont très ___ (sérieux).',
      undefined,
      'sérieuses',
      'Feminine plural of sérieux is sérieuses.',
      'Le féminin pluriel de sérieux est sérieuses.',
    ],
    [
      'adjective-agreement-a1',
      'multiple-choice',
      'Which sentence has a correctly agreed adjective?',
      'Quelle phrase a un adjectif correctement accordé ?',
      [
        'Les garçons sont contente.',
        'Les filles sont contents.',
        'Les filles sont contentes.',
        'Le garçon sont content.',
      ],
      'Les filles sont contentes.',
      'Filles is feminine plural, so the adjective takes -es: contentes.',
      'Filles est féminin pluriel, donc l\'adjectif prend -es : contentes.',
    ],
    [
      'adjective-agreement-a1',
      'multiple-choice',
      'What is the feminine form of "bon" ?',
      'Quelle est la forme féminine de « bon » ?',
      ['bone', 'bonne', 'bons', 'bonnes'],
      'bonne',
      'Bon → bonne (doubles the final consonant before adding -e).',
      'Bon → bonne (on double la consonne finale avant d\'ajouter -e).',
    ],

    // ── ADJECTIVE POSITION ───────────────────────────────────────────────────
    [
      'adjective-position-a1',
      'multiple-choice',
      'A friend recommends a restaurant. Choose the most natural sentence.',
      'Un ami recommande un restaurant. Choisissez la phrase la plus naturelle.',
      [
        'C\'est un bon restaurant.',
        'C\'est un restaurant bon.',
        'C\'est bon un restaurant.',
        'C\'est restaurant bon un.',
      ],
      'C\'est un bon restaurant.',
      'Bon is one of the short frequent adjectives that comes before the noun.',
      'Bon est l\'un des adjectifs courts fréquents qui se place avant le nom.',
    ],
    [
      'adjective-position-a1',
      'multiple-choice',
      'Which adjective normally comes BEFORE the noun?',
      'Quel adjectif se place normalement AVANT le nom ?',
      ['rouge', 'français', 'vieux', 'médical'],
      'vieux',
      'Vieux is a BAGS adjective (Beauty, Age, Goodness, Size) and typically precedes the noun.',
      'Vieux est un adjectif BAGS (Beauté, Âge, Bonté, Taille) et précède généralement le nom.',
    ],

    // ── SUBJECT PRONOUNS ─────────────────────────────────────────────────────
    [
      'subject-pronouns-a1',
      'multiple-choice',
      'In spoken French, what pronoun do people often use instead of "nous"?',
      'En français oral, quel pronom utilise-t-on souvent à la place de « nous » ?',
      ['vous', 'ils', 'on', 'elles'],
      'on',
      'On is very common in spoken French to replace nous (we).',
      'On est très courant en français oral pour remplacer nous (we).',
    ],
    [
      'subject-pronouns-a1',
      'fill',
      'Complete: ___ mangeons ensemble ce soir. (we)',
      'Complétez : ___ mangeons ensemble ce soir. (nous)',
      undefined,
      'Nous',
      'Nous (or on) is used for "we".',
      'Nous (ou on) s\'utilise pour « we ».',
    ],
    [
      'subject-pronouns-a1',
      'multiple-choice',
      'Which pronoun refers to a group of men and women together?',
      'Quel pronom désigne un groupe d\'hommes et de femmes ensemble ?',
      ['elles', 'ils', 'eux', 'on'],
      'ils',
      'A mixed-gender group uses ils in French.',
      'Un groupe mixte utilise ils en français.',
    ],

    // ── TU VS VOUS ───────────────────────────────────────────────────────────
    [
      'tu-vous-a1',
      'multiple-choice',
      'You meet your boss for the first time. Which form do you use?',
      'Vous rencontrez votre patron pour la première fois. Quelle forme utilisez-vous ?',
      ['Tu', 'Vous', 'On', 'Ils'],
      'Vous',
      'Vous is the polite / formal form used with strangers, bosses, and people older than you.',
      'Vous est la forme polie / formelle utilisée avec les inconnus, les supérieurs et les personnes plus âgées.',
    ],
    [
      'tu-vous-a1',
      'multiple-choice',
      'A French child speaks to you at the playground. Which form would they naturally use?',
      'Un enfant français vous parle dans un parc. Quelle forme utiliserait-il naturellement ?',
      ['vous', 'tu', 'ils', 'on'],
      'tu',
      'Children typically use tu with adults they just met in informal contexts.',
      'Les enfants utilisent généralement tu avec les adultes qu\'ils viennent de rencontrer dans des contextes informels.',
    ],

    // ── ÊTRE AND AVOIR ───────────────────────────────────────────────────────
    [
      'etre-avoir',
      'multiple-choice',
      'Choose the correct form: Mon frère ___ trente ans.',
      'Choisissez la bonne forme : Mon frère ___ trente ans.',
      ['est', 'a', 'sont', 'ont'],
      'a',
      'Age in French uses avoir: il a trente ans.',
      'L\'âge en français s\'exprime avec avoir : il a trente ans.',
    ],
    [
      'etre-avoir',
      'fill',
      'Complete: Nous ___ faim après la randonnée. (avoir)',
      'Complétez : Nous ___ faim après la randonnée. (avoir)',
      undefined,
      'avons',
      'Hunger uses avoir: nous avons faim.',
      'La faim s\'exprime avec avoir : nous avons faim.',
    ],
    [
      'etre-avoir',
      'multiple-choice',
      'Which sentence is correct for "It is cold" (weather)?',
      'Quelle phrase est correcte pour « il fait froid » (météo) ?',
      ['Il est froid.', 'Il a froid.', 'Il fait froid.', 'Il froid.'],
      'Il fait froid.',
      'Weather expressions use faire: il fait froid/chaud/beau.',
      'Les expressions météorologiques utilisent faire : il fait froid/chaud/beau.',
    ],
    [
      'etre-avoir',
      'multiple-choice',
      'You feel sick. Which sentence do you say?',
      'Vous êtes malade. Quelle phrase dites-vous ?',
      ['Je suis mal.', 'J\'ai mal.', 'Je fait mal.', 'J\'ai maladie.'],
      'J\'ai mal.',
      'Avoir mal means to be in pain / to feel sick.',
      'Avoir mal signifie avoir de la douleur.',
    ],

    // ── PRESENT -ER VERBS ────────────────────────────────────────────────────
    [
      'present-er',
      'multiple-choice',
      'At the market, a vendor calls out: "Regardez ___ tomates fraîches !" What does he then say to you?',
      'Au marché, un vendeur crie : « Regardez ces tomates fraîches ! » Que vous dit-il ensuite ?',
      ['Tu cherche quoi ?', 'Vous cherchez quoi ?', 'Vous chercheZ quoi ?', 'Vous cherchons quoi ?'],
      'Vous cherchez quoi ?',
      'Vous + -er verbs: drop -er and add -ez. Chercher → cherchez.',
      'Avec vous + verbes en -er : supprimer -er et ajouter -ez. Chercher → cherchez.',
    ],
    [
      'present-er',
      'fill',
      'Complete the blog post: "Chaque matin, je ___ mon café lentement." (savourer)',
      'Complétez le billet de blog : « Chaque matin, je ___ mon café lentement. » (savourer)',
      undefined,
      'savoure',
      'Je + savourer: drop -er → savoure.',
      'Je + savourer : supprimer -er → savoure.',
    ],
    [
      'present-er',
      'multiple-choice',
      'Choose the correct conjugation: Ils ___ le week-end à la campagne. (passer)',
      'Choisissez la bonne conjugaison : Ils ___ le week-end à la campagne. (passer)',
      ['passons', 'passez', 'passent', 'passe'],
      'passent',
      'Ils + -er verbs take -ent (usually silent): ils passent.',
      'Ils + verbes en -er prennent -ent (souvent muet) : ils passent.',
    ],
    [
      'present-er',
      'fill',
      'Complete: Nous ___ nos amis ce soir. (inviter)',
      'Complétez : Nous ___ nos amis ce soir. (inviter)',
      undefined,
      'invitons',
      'Nous + -er verbs: add -ons. Inviter → invitons.',
      'Nous + verbes en -er : ajouter -ons. Inviter → invitons.',
    ],

    // ── ALLER AND FAIRE ──────────────────────────────────────────────────────
    [
      'present-aller-faire-a1',
      'multiple-choice',
      'Your friend asks how you are. What is the most natural reply?',
      'Votre ami demande comment vous allez. Quelle est la réponse la plus naturelle ?',
      ['Je fais bien, merci.', 'Je vais bien, merci.', 'Je suis bien, merci.', 'J\'ai bien, merci.'],
      'Je vais bien, merci.',
      'Aller is used in greetings: comment ça va ? Je vais bien.',
      'Aller s\'utilise dans les salutations : comment ça va ? Je vais bien.',
    ],
    [
      'present-aller-faire-a1',
      'fill',
      'Complete: Qu\'est-ce que vous ___ ce week-end ? (faire)',
      'Complétez : Qu\'est-ce que vous ___ ce week-end ? (faire)',
      undefined,
      'faites',
      'Vous + faire = faites.',
      'Vous + faire = faites.',
    ],
    [
      'present-aller-faire-a1',
      'multiple-choice',
      'Which phrase uses "faire" for an activity?',
      'Quelle phrase utilise « faire » pour une activité ?',
      [
        'Il va au foot.',
        'Il joue au foot.',
        'Il fait du foot.',
        'Il est au foot.',
      ],
      'Il fait du foot.',
      'Faire + du/de la + activity is a common pattern: faire du foot.',
      'Faire + du/de la + activité est un modèle courant : faire du foot.',
    ],

    // ── NEGATION NE…PAS ──────────────────────────────────────────────────────
    [
      'negation-ne-pas-a1',
      'multiple-choice',
      'Your friend asks if you drink coffee. You don\'t. Choose the correct answer.',
      'Votre ami demande si vous buvez du café. Vous n\'en buvez pas. Choisissez la bonne réponse.',
      ['Je bois pas du café.', 'Je ne bois pas de café.', 'Je ne bois pas du café.', 'Je pas bois du café.'],
      'Je ne bois pas de café.',
      'After a negation, du/de la/des become de/d\'.',
      'Après la négation, du/de la/des deviennent de/d\'.',
    ],
    [
      'negation-ne-pas-a1',
      'fill',
      'Make negative: Elle comprend l\'anglais. → Elle ___ ___ l\'anglais.',
      'Mettez à la forme négative : Elle comprend l\'anglais. → Elle ___ ___ l\'anglais.',
      undefined,
      'ne comprend pas',
      'Ne goes before the verb, pas goes after: elle ne comprend pas.',
      'Ne se place avant le verbe, pas après : elle ne comprend pas.',
    ],
    [
      'negation-ne-pas-a1',
      'multiple-choice',
      'In spoken French, which part of the negation is often dropped?',
      'En français oral, quelle partie de la négation est souvent supprimée ?',
      ['pas', 'ne', 'le verbe', 'le sujet'],
      'ne',
      'In casual speech, ne is often omitted: "Je sais pas" instead of "Je ne sais pas".',
      'Dans la langue familière, ne est souvent omis : « Je sais pas » au lieu de « Je ne sais pas ».',
    ],

    // ── QUESTIONS ────────────────────────────────────────────────────────────
    [
      'questions',
      'multiple-choice',
      'A tourist asks politely for directions. Which question is most formal?',
      'Un touriste demande poliment son chemin. Quelle question est la plus formelle ?',
      [
        'La gare est où ?',
        'Où est-ce que la gare est ?',
        'Où est la gare ?',
        'La gare c\'est où ?',
      ],
      'Où est la gare ?',
      'Inversion (Où est la gare ?) is the most formal style.',
      'L\'inversion (Où est la gare ?) est le style le plus formel.',
    ],
    [
      'questions',
      'fill',
      'Transform to a question using est-ce que: Tu aimes le cinéma. → ___',
      'Transformez en question avec est-ce que : Tu aimes le cinéma. → ___',
      undefined,
      'Est-ce que tu aimes le cinéma ?',
      'Est-ce que comes before the normal subject-verb order.',
      'Est-ce que se place avant l\'ordre normal sujet-verbe.',
    ],
    [
      'questions',
      'multiple-choice',
      'Which question word asks "how many/much"?',
      'Quel mot interrogatif demande « combien » ?',
      ['Comment', 'Pourquoi', 'Combien', 'Lequel'],
      'Combien',
      'Combien means how many or how much.',
      'Combien signifie how many ou how much.',
    ],
    [
      'questions',
      'multiple-choice',
      'Which sentence correctly uses inversion to ask a question?',
      'Quelle phrase utilise correctement l\'inversion pour poser une question ?',
      [
        'Tu parle-t-il français ?',
        'Parlez-vous français ?',
        'Est parlez-vous français ?',
        'Vous parlez français ?',
      ],
      'Parlez-vous français ?',
      'Inversion places the verb before the subject pronoun: parlez-vous.',
      'L\'inversion place le verbe avant le pronom sujet : parlez-vous.',
    ],

    // ── C'EST VS IL EST ───────────────────────────────────────────────────────
    [
      'c-est-il-est-a1',
      'multiple-choice',
      'You are introducing your sister to a friend. Which sentence do you use?',
      'Vous présentez votre sœur à un ami. Quelle phrase utilisez-vous ?',
      ['Elle est ma sœur.', 'C\'est ma sœur.', 'Il est ma sœur.', 'C\'est une ma sœur.'],
      'C\'est ma sœur.',
      'C\'est is used to identify or introduce a person: c\'est ma sœur.',
      'C\'est sert à identifier ou présenter une personne : c\'est ma sœur.',
    ],
    [
      'c-est-il-est-a1',
      'multiple-choice',
      'How do you describe someone\'s job in French? (He is a teacher)',
      'Comment décrit-on le métier de quelqu\'un en français ? (Il est professeur)',
      ['C\'est professeur.', 'Il est un professeur.', 'Il est professeur.', 'C\'est il professeur.'],
      'Il est professeur.',
      'With professions after il/elle est, no article is used: il est professeur.',
      'Avec les professions après il/elle est, on n\'utilise pas d\'article : il est professeur.',
    ],

    // ── POSSESSIVE ADJECTIVES ────────────────────────────────────────────────
    [
      'possessive-adjectives-a1',
      'multiple-choice',
      'Your colleague says: "J\'ai oublié ___ portable !" (her phone – she is female)',
      'Votre collègue dit : « J\'ai oublié ___ portable ! » (son téléphone – elle est une femme)',
      ['ma', 'sa', 'son', 'ses'],
      'son',
      'Portable begins with a vowel, so use son (even for a feminine owner).',
      'Portable commence par une voyelle, donc on utilise son (même pour un propriétaire féminin).',
    ],
    [
      'possessive-adjectives-a1',
      'fill',
      'Complete: Nous avons oublié ___ parapluies chez toi. (nos)',
      'Complétez : Nous avons oublié ___ parapluies chez toi. (nos)',
      undefined,
      'nos',
      'Nos is the plural possessive adjective for nous.',
      'Nos est l\'adjectif possessif pluriel de nous.',
    ],
    [
      'possessive-adjectives-a1',
      'multiple-choice',
      'A French friend asks: "C\'est ___ idée de faire une fête ?" (your idea – informal)',
      'Un ami français demande : « C\'est ___ idée de faire une fête ? » (ta ou votre idée)',
      ['ma', 'ta', 'sa', 'leur'],
      'ta',
      'Informal "your" + feminine noun idée = ta.',
      '« Your » informel + nom féminin idée = ta.',
    ],

    // ── DEMONSTRATIVE ADJECTIVES ─────────────────────────────────────────────
    [
      'demonstrative-adjectives-a1',
      'multiple-choice',
      'You point to a dress in a shop window: "___ robe est magnifique !"',
      'Vous montrez une robe dans une vitrine : « ___ robe est magnifique ! »',
      ['Ce', 'Cet', 'Cette', 'Ces'],
      'Cette',
      'Robe is feminine singular: cette robe.',
      'Robe est féminin singulier : cette robe.',
    ],
    [
      'demonstrative-adjectives-a1',
      'fill',
      'Complete: ___ été, je vais en vacances au Portugal. (this summer)',
      'Complétez : ___ été, je vais en vacances au Portugal. (cet été)',
      undefined,
      'Cet',
      'Été begins with a vowel sound, so cet is used (masculine singular).',
      'Été commence par un son voyelle, donc on utilise cet (masculin singulier).',
    ],
    [
      'demonstrative-adjectives-a1',
      'multiple-choice',
      'Which form is used before a masculine singular noun starting with a consonant?',
      'Quelle forme utilise-t-on avant un nom masculin singulier commençant par une consonne ?',
      ['cette', 'cet', 'ces', 'ce'],
      'ce',
      'Ce is used before a masculine singular noun starting with a consonant: ce livre.',
      'Ce s\'utilise avant un nom masculin singulier qui commence par une consonne : ce livre.',
    ],

    // ── NUMBERS, TIME, DATES ─────────────────────────────────────────────────
    [
      'numbers-time-a1',
      'multiple-choice',
      'Your flight is at 14:30. How do you say this in French?',
      'Votre vol est à 14 h 30. Comment le dites-vous en français ?',
      [
        'Il est deux heures et demie de l\'après-midi.',
        'Il est quatorze heures trente.',
        'Il est deux heures trente.',
        'Il est le quatorze heure trente.',
      ],
      'Il est quatorze heures trente.',
      'In formal / 24-hour contexts, French uses quatorze heures trente.',
      'Dans les contextes formels / 24 h, le français utilise quatorze heures trente.',
    ],
    [
      'numbers-time-a1',
      'fill',
      'Write in French: The meeting is on the 15th of March. → La réunion est ___ mars.',
      'Écrivez en français : La réunion est le 15 mars. → La réunion est ___ mars.',
      undefined,
      'le 15',
      'Dates in French use le + number + month: le 15 mars.',
      'Les dates en français utilisent le + nombre + mois : le 15 mars.',
    ],
    [
      'numbers-time-a1',
      'multiple-choice',
      'How do you ask someone\'s age in French?',
      'Comment demande-t-on l\'âge de quelqu\'un en français ?',
      [
        'Tu es combien d\'années ?',
        'Tu as quel âge ?',
        'Tu es quel âge ?',
        'Tu fais quel âge ?',
      ],
      'Tu as quel âge ?',
      'Age in French uses avoir: tu as quel âge ? / quel âge as-tu ?',
      'L\'âge en français utilise avoir : tu as quel âge ? / quel âge as-tu ?',
    ],

    // ── PREPOSITIONS OF PLACE ────────────────────────────────────────────────
    [
      'prepositions-place-a1',
      'multiple-choice',
      'The keys are not on the table. They are ___ the sofa.',
      'Les clés ne sont pas sur la table. Elles sont ___ le canapé.',
      ['sur', 'dans', 'sous', 'devant'],
      'sous',
      'Sous means under / beneath: les clés sont sous le canapé.',
      'Sous signifie under / beneath : les clés sont sous le canapé.',
    ],
    [
      'prepositions-place-a1',
      'fill',
      'Complete the directions: La pharmacie est ___ côté de la boulangerie.',
      'Complétez les indications : La pharmacie est ___ côté de la boulangerie.',
      undefined,
      'à',
      'À côté de means next to.',
      'À côté de signifie next to.',
    ],
    [
      'prepositions-place-a1',
      'multiple-choice',
      'Where is the ATM? Choose the correct preposition.',
      'Où est le distributeur de billets ? Choisissez la bonne préposition.',
      [
        'Il est au face de la banque.',
        'Il est en face de la banque.',
        'Il est face de la banque.',
        'Il est devant de la banque.',
      ],
      'Il est en face de la banque.',
      'En face de means opposite / across from.',
      'En face de signifie opposite / across from.',
    ],

    // ── IL Y A ───────────────────────────────────────────────────────────────
    [
      'il-y-a-a1',
      'multiple-choice',
      'How do you say "There is no more milk" in French?',
      'Comment dit-on « Il n\'y a plus de lait » en français ?',
      [
        'Il n\'y a pas de lait.',
        'Il n\'y a plus de lait.',
        'Il y a plus du lait.',
        'Il n\'y est plus de lait.',
      ],
      'Il n\'y a plus de lait.',
      'Il n\'y a plus de = there is no more / no longer any.',
      'Il n\'y a plus de = there is no more / no longer any.',
    ],
    [
      'il-y-a-a1',
      'fill',
      'Complete: ___ un problème avec la connexion internet.',
      'Complétez : ___ un problème avec la connexion internet.',
      undefined,
      'Il y a',
      'Il y a introduces the existence of something.',
      'Il y a indique l\'existence de quelque chose.',
    ],

    // ── FUTUR PROCHE ─────────────────────────────────────────────────────────
    [
      'futur-proche-a1',
      'multiple-choice',
      'Your train leaves in two minutes! Which sentence expresses this urgency?',
      'Votre train part dans deux minutes ! Quelle phrase exprime cette urgence ?',
      [
        'Le train part dans deux minutes.',
        'Le train va partir dans deux minutes.',
        'Le train partait dans deux minutes.',
        'Le train partirait dans deux minutes.',
      ],
      'Le train va partir dans deux minutes.',
      'Futur proche (aller + infinitive) is especially natural for imminent events.',
      'Le futur proche (aller + infinitif) est particulièrement naturel pour les événements imminents.',
    ],
    [
      'futur-proche-a1',
      'fill',
      'Complete: Ils ___ visiter Paris la semaine prochaine. (aller)',
      'Complétez : Ils ___ visiter Paris la semaine prochaine. (aller)',
      undefined,
      'vont',
      'Ils + aller = vont: ils vont visiter.',
      'Ils + aller = vont : ils vont visiter.',
    ],
    [
      'futur-proche-a1',
      'multiple-choice',
      'Make the futur proche negative: Je vais sortir. → ___',
      'Mettez le futur proche à la forme négative : Je vais sortir. → ___',
      [
        'Je vais ne pas sortir.',
        'Je ne vais pas sortir.',
        'Je ne pas vais sortir.',
        'Je vais pas ne sortir.',
      ],
      'Je ne vais pas sortir.',
      'In futur proche, ne…pas surrounds aller: je ne vais pas sortir.',
      'Au futur proche, ne…pas entoure aller : je ne vais pas sortir.',
    ],

    // ── IMPERATIVE ───────────────────────────────────────────────────────────
    [
      'imperative-a1',
      'multiple-choice',
      'A recipe says: "___ la farine avec les œufs." (mélanger – vous form)',
      'Une recette dit : « ___ la farine avec les œufs. » (mélanger – forme vous)',
      ['Mélangez', 'Mélange', 'Mélangeons', 'Mélanges'],
      'Mélangez',
      'Vous imperative of mélanger: mélangez.',
      'L\'impératif vous de mélanger : mélangez.',
    ],
    [
      'imperative-a1',
      'fill',
      'Complete the command (tu): ___ la porte, s\'il te plaît ! (fermer)',
      'Complétez l\'ordre (tu) : ___ la porte, s\'il te plaît ! (fermer)',
      undefined,
      'Ferme',
      'Tu imperative of -er verbs drops final -s: ferme.',
      'L\'impératif tu des verbes en -er perd le -s final : ferme.',
    ],
    [
      'imperative-a1',
      'multiple-choice',
      'How do you say "Let\'s go to the cinema!" in French?',
      'Comment dit-on « Allons au cinéma ! » en français ?',
      ['Allez au cinéma !', 'Allons au cinéma !', 'Va au cinéma !', 'Vais au cinéma !'],
      'Allons au cinéma !',
      'The nous imperative of aller is allons.',
      'L\'impératif nous de aller est allons.',
    ],

    // ── PARTITIVE ARTICLES ───────────────────────────────────────────────────
    [
      'partitive-articles-a2',
      'multiple-choice',
      'You order in a French restaurant: "Je voudrais ___ poulet et ___ eau, s\'il vous plaît."',
      'Vous commandez dans un restaurant : « Je voudrais ___ poulet et ___ eau, s\'il vous plaît. »',
      ['le / l\'', 'du / de l\'', 'un / une', 'du / une'],
      'du / de l\'',
      'Partitive articles express an unspecified portion: du poulet, de l\'eau.',
      'Les articles partitifs expriment une quantité non précisée : du poulet, de l\'eau.',
    ],
    [
      'partitive-articles-a2',
      'fill',
      'Complete: Tu veux ___ soupe ? Non, merci, je ne veux pas ___ soupe. (de la / de)',
      'Complétez : Tu veux ___ soupe ? Non, merci, je ne veux pas ___ soupe.',
      undefined,
      'de la / de',
      'De la in positive sentences; de after negation.',
      'De la dans les phrases positives ; de après la négation.',
    ],
    [
      'partitive-articles-a2',
      'multiple-choice',
      'Which sentence correctly uses a partitive article?',
      'Quelle phrase utilise correctement un article partitif ?',
      [
        'Je fais de la musique.',
        'Je fais la musique.',
        'Je fais une musique.',
        'Je fais des la musique.',
      ],
      'Je fais de la musique.',
      'Faire de la musique: partitive de la is standard here.',
      'Faire de la musique : l\'article partitif de la est standard ici.',
    ],

    // ── QUANTITIES WITH DE ───────────────────────────────────────────────────
    [
      'quantities-a2',
      'multiple-choice',
      'Choose the correct sentence: "I have a lot of friends."',
      'Choisissez la bonne phrase : « J\'ai beaucoup d\'amis. »',
      [
        'J\'ai beaucoup des amis.',
        'J\'ai beaucoup d\'amis.',
        'J\'ai beaucoup de des amis.',
        'J\'ai beaucoup les amis.',
      ],
      'J\'ai beaucoup d\'amis.',
      'Beaucoup de (d\' before a vowel) is followed directly by the noun.',
      'Beaucoup de (d\' devant une voyelle) est suivi directement du nom.',
    ],
    [
      'quantities-a2',
      'fill',
      'Complete: Elle boit ___ trop ___ café. (beaucoup / de)',
      'Complétez : Elle boit ___ trop ___ café.',
      undefined,
      'trop de',
      'Trop de means too much of.',
      'Trop de signifie too much of.',
    ],

    // ── REFLEXIVE VERBS ──────────────────────────────────────────────────────
    [
      'reflexive-verbs-a2',
      'multiple-choice',
      'Describe a morning routine: "Chaque matin, elle ___ à sept heures."',
      'Décrivez une routine matinale : « Chaque matin, elle ___ à sept heures. » (se lever)',
      ['se lève', 'se lever', 'se levé', 'se lèves'],
      'se lève',
      'Elle se lève: the reflexive pronoun se agrees with elle, verb takes -e.',
      'Elle se lève : le pronom réfléchi se s\'accorde avec elle, le verbe prend -e.',
    ],
    [
      'reflexive-verbs-a2',
      'fill',
      'Complete the negation: Je ne ___ pas avant minuit. (se coucher)',
      'Complétez la négation : Je ne ___ pas avant minuit. (se coucher)',
      undefined,
      'me couche',
      'The reflexive pronoun stays before the verb: je ne me couche pas.',
      'Le pronom réfléchi reste avant le verbe : je ne me couche pas.',
    ],
    [
      'reflexive-verbs-a2',
      'multiple-choice',
      'Which sentence correctly uses a reflexive verb in the passé composé?',
      'Quelle phrase utilise correctement un verbe pronominal au passé composé ?',
      [
        'Elle a levé à sept heures.',
        'Elle s\'est levée à sept heures.',
        'Elle était levée à sept heures.',
        'Elle s\'a levée à sept heures.',
      ],
      'Elle s\'est levée à sept heures.',
      'Reflexive verbs use être in the passé composé; the participle agrees with the subject.',
      'Les verbes pronominaux utilisent être au passé composé ; le participe s\'accorde avec le sujet.',
    ],

    // ── PASSÉ COMPOSÉ (AVOIR) ────────────────────────────────────────────────
    [
      'passe-compose-avoir-a2',
      'multiple-choice',
      'Tell a story about yesterday: "Hier soir, nous ___ un excellent repas au restaurant." (manger)',
      'Racontez une histoire sur hier : « Hier soir, nous ___ un excellent repas au restaurant. » (manger)',
      ['mangions', 'avons mangé', 'mangeons', 'mangerons'],
      'avons mangé',
      'A completed past event uses the passé composé: nous avons mangé.',
      'Un événement passé terminé utilise le passé composé : nous avons mangé.',
    ],
    [
      'passe-compose-avoir-a2',
      'fill',
      'Complete: Tu ___ tes clés dans le taxi. (oublier)',
      'Complétez : Tu ___ tes clés dans le taxi. (oublier)',
      undefined,
      'as oublié',
      'Tu + avoir (as) + past participle oublié.',
      'Tu + avoir (as) + participe passé oublié.',
    ],
    [
      'passe-compose-avoir-a2',
      'multiple-choice',
      'What is the past participle of "voir" (to see)?',
      'Quel est le participe passé de « voir » ?',
      ['voit', 'voyé', 'vu', 'voir'],
      'vu',
      'The irregular past participle of voir is vu.',
      'Le participe passé irrégulier de voir est vu.',
    ],
    [
      'passe-compose-avoir-a2',
      'fill',
      'Complete: Vous ___ ce film la semaine dernière ? (voir)',
      'Complétez : Vous ___ ce film la semaine dernière ? (voir)',
      undefined,
      'avez vu',
      'Vous + avoir (avez) + vu.',
      'Vous + avoir (avez) + vu.',
    ],

    // ── PASSÉ COMPOSÉ (ÊTRE) ─────────────────────────────────────────────────
    [
      'passe-compose-etre-a2',
      'multiple-choice',
      'Which verb takes ÊTRE as its auxiliary in the passé composé?',
      'Quel verbe utilise ÊTRE comme auxiliaire au passé composé ?',
      ['manger', 'voir', 'vendre', 'partir'],
      'partir',
      'Partir is one of the DR & MRS VANDERTRAMP verbs that use être.',
      'Partir est l\'un des verbes DR & MRS VANDERTRAMP qui utilisent être.',
    ],
    [
      'passe-compose-etre-a2',
      'fill',
      'Complete: Les enfants ___ dans le jardin ce matin. (sortir)',
      'Complétez : Les enfants ___ dans le jardin ce matin. (sortir)',
      undefined,
      'sont sortis',
      'Sortir uses être; les enfants (masculine plural) → sortis.',
      'Sortir utilise être ; les enfants (masculin pluriel) → sortis.',
    ],
    [
      'passe-compose-etre-a2',
      'multiple-choice',
      'Choose the correct passé composé sentence with agreement.',
      'Choisissez la phrase correcte au passé composé avec accord.',
      [
        'Mes sœurs sont parti ce matin.',
        'Mes sœurs sont partis ce matin.',
        'Mes sœurs sont parties ce matin.',
        'Mes sœurs ont parties ce matin.',
      ],
      'Mes sœurs sont parties ce matin.',
      'Sœurs is feminine plural; with être, the participle must agree: parties.',
      'Sœurs est féminin pluriel ; avec être, le participe doit s\'accorder : parties.',
    ],

    // ── IMPARFAIT ────────────────────────────────────────────────────────────
    [
      'imparfait',
      'multiple-choice',
      'Describe a childhood memory: "Quand j\'étais enfant, je ___ des bandes dessinées tous les soirs."',
      'Décrivez un souvenir d\'enfance : « Quand j\'étais enfant, je ___ des bandes dessinées tous les soirs. »',
      ['lisais', 'ai lu', 'lirais', 'lis'],
      'lisais',
      'Repeated past habits use imparfait: je lisais.',
      'Les habitudes passées répétées utilisent l\'imparfait : je lisais.',
    ],
    [
      'imparfait',
      'fill',
      'Complete: Il ___ très chaud cet été-là. (faire)',
      'Complétez : Il ___ très chaud cet été-là. (faire)',
      undefined,
      'faisait',
      'Weather descriptions in the past use imparfait: il faisait.',
      'Les descriptions météorologiques au passé utilisent l\'imparfait : il faisait.',
    ],
    [
      'imparfait',
      'multiple-choice',
      'Choose imparfait to complete: Quand il était jeune, il ___ du piano.',
      'Choisissez l\'imparfait : Quand il était jeune, il ___ du piano.',
      ['joue', 'jouait', 'a joué', 'jouera'],
      'jouait',
      'Childhood habits use imparfait: il jouait.',
      'Les habitudes d\'enfance utilisent l\'imparfait : il jouait.',
    ],

    // ── PC VS IMPARFAIT ──────────────────────────────────────────────────────
    [
      'pc-imparfait-a2',
      'multiple-choice',
      'Choose the correct tenses: "Je ___ (lire) quand le téléphone ___." (sonner)',
      'Choisissez les bons temps : « Je ___ (lire) quand le téléphone ___ (sonner). »',
      [
        'lisais / a sonné',
        'ai lu / sonnait',
        'lisais / sonnait',
        'ai lu / a sonné',
      ],
      'lisais / a sonné',
      'Background action (lire) = imparfait; interrupting completed event (sonner) = passé composé.',
      'L\'action de fond (lire) = imparfait ; l\'événement interrupteur terminé (sonner) = passé composé.',
    ],
    [
      'pc-imparfait-a2',
      'multiple-choice',
      'Which sentence correctly mixes both tenses?',
      'Quelle phrase mélange correctement les deux temps ?',
      [
        'Il pleuvait et j\'ai décidé de rester.',
        'Il a plu et j\'ai décidé de rester.',
        'Il pleuvait et je décidais de rester.',
        'Il plu et j\'ai décidé de rester.',
      ],
      'Il pleuvait et j\'ai décidé de rester.',
      'The background (rain) is imparfait; the decision is a completed event (passé composé).',
      'Le fond (pluie) est à l\'imparfait ; la décision est un événement terminé (passé composé).',
    ],
    [
      'pc-imparfait-a2',
      'fill',
      'Complete: Hier, j\'___ (avoir) faim alors j\'___ (manger) une pizza.',
      'Complétez : Hier, j\'___ (avoir) faim alors j\'___ (manger) une pizza.',
      undefined,
      'avais / ai mangé',
      'State of hunger = imparfait (avais); the eating action = passé composé (ai mangé).',
      'L\'état de faim = imparfait (avais) ; l\'action de manger = passé composé (ai mangé).',
    ],

    // ── OBJECT PRONOUNS ──────────────────────────────────────────────────────
    [
      'object-pronouns',
      'multiple-choice',
      'Replace "la lettre": Tu lis la lettre. → ___',
      'Remplacez « la lettre » : Tu lis la lettre. → ___',
      ['Tu lui lis.', 'Tu la lis.', 'Tu le lis.', 'Tu en lis.'],
      'Tu la lis.',
      'Lettre is feminine; the direct object pronoun is la.',
      'Lettre est féminin ; le pronom COD est la.',
    ],
    [
      'object-pronouns',
      'multiple-choice',
      'Replace "à mes parents": Je téléphone à mes parents. → ___',
      'Remplacez « à mes parents » : Je téléphone à mes parents. → ___',
      ['Je les téléphone.', 'Je leur téléphone.', 'Je leur téléphones.', 'Je lui téléphone.'],
      'Je leur téléphone.',
      'Téléphoner à someone → indirect object pronoun leur (plural).',
      'Téléphoner à quelqu\'un → pronom COI leur (pluriel).',
    ],
    [
      'object-pronouns',
      'fill',
      'Complete: Est-ce que tu aimes ce film ? Oui, je ___ aime beaucoup. (le)',
      'Complétez : Est-ce que tu aimes ce film ? Oui, je ___ aime beaucoup.',
      undefined,
      'l\'',
      'Le becomes l\' before aime (vowel): je l\'aime.',
      'Le devient l\' devant aime (voyelle) : je l\'aime.',
    ],

    // ── PRONOUN PLACEMENT ────────────────────────────────────────────────────
    [
      'pronoun-placement-a2',
      'multiple-choice',
      'Replace "les devoirs": Il veut faire les devoirs. → ___',
      'Remplacez « les devoirs » : Il veut faire les devoirs. → ___',
      [
        'Il les veut faire.',
        'Il veut les faire.',
        'Il les faire veut.',
        'Il faire les veut.',
      ],
      'Il veut les faire.',
      'With two verbs, the object pronoun goes before the infinitive it belongs to.',
      'Avec deux verbes, le pronom COD se place avant l\'infinitif auquel il appartient.',
    ],
    [
      'pronoun-placement-a2',
      'fill',
      'Complete negation: Je ne ___ vois pas. (le / before vowel)',
      'Complétez la négation : Je ne ___ vois pas.',
      undefined,
      'le',
      'Le goes between ne and the verb: je ne le vois pas.',
      'Le se place entre ne et le verbe : je ne le vois pas.',
    ],

    // ── Y AND EN ─────────────────────────────────────────────────────────────
    [
      'y-en-intro-a2',
      'multiple-choice',
      'Replace "à Paris": Tu vas à Paris ? → ___',
      'Remplacez « à Paris » : Tu vas à Paris ? → ___',
      ['Tu y vas ?', 'Tu en vas ?', 'Tu lui vas ?', 'Tu le vas ?'],
      'Tu y vas ?',
      'Y replaces à + place: tu y vas.',
      'Y remplace à + lieu : tu y vas.',
    ],
    [
      'y-en-intro-a2',
      'fill',
      'Replace "du café": Tu veux du café ? → Tu ___ veux ?',
      'Remplacez « du café » : Tu veux du café ? → Tu ___ veux ?',
      undefined,
      'en',
      'En replaces du/de la/des + noun or quantity.',
      'En remplace du/de la/des + nom ou quantité.',
    ],
    [
      'y-en-intro-a2',
      'multiple-choice',
      'Complete the answer: "Tu penses à ton examen ?" → "Oui, j\'___ pense tout le temps."',
      'Complétez : « Tu penses à ton examen ? » → « Oui, j\'___ pense tout le temps. »',
      ['en', 'y', 'lui', 'le'],
      'y',
      'Penser à + thing → replace with y.',
      'Penser à + chose → remplacer par y.',
    ],

    // ── COMPARATIVE ──────────────────────────────────────────────────────────
    [
      'comparative-a2',
      'multiple-choice',
      'Compare two cities: "Lyon est ___ grande que Paris."',
      'Comparez deux villes : « Lyon est ___ grande que Paris. »',
      ['plus', 'aussi', 'moins', 'autant'],
      'moins',
      'Lyon is smaller than Paris, so use moins... que.',
      'Lyon est plus petite que Paris, donc on utilise moins... que.',
    ],
    [
      'comparative-a2',
      'fill',
      'Complete: Ce restaurant est ___ bon ___ l\'autre. (as good as)',
      'Complétez : Ce restaurant est ___ bon ___ l\'autre. (aussi bon que)',
      undefined,
      'aussi / que',
      'Aussi...que expresses equality: aussi bon que.',
      'Aussi...que exprime l\'égalité : aussi bon que.',
    ],
    [
      'comparative-a2',
      'multiple-choice',
      'What is the irregular comparative of "bon" (good)?',
      'Quel est le comparatif irrégulier de « bon » ?',
      ['plus bon', 'meilleur', 'mieux', 'bon plus'],
      'meilleur',
      'Bon has the irregular comparative meilleur (better).',
      'Bon a le comparatif irrégulier meilleur (better).',
    ],

    // ── SUPERLATIVE ──────────────────────────────────────────────────────────
    [
      'superlative-a2',
      'multiple-choice',
      'Choose the correct superlative: "C\'est le restaurant ___ cher de la ville."',
      'Choisissez le bon superlatif : « C\'est le restaurant ___ cher de la ville. »',
      ['le plus', 'plus', 'le moins', 'moins'],
      'le plus',
      'Le plus + adjective = the most.',
      'Le plus + adjectif = the most.',
    ],
    [
      'superlative-a2',
      'fill',
      'Complete: C\'est ___ film que j\'ai jamais vu ! (the worst – masculine)',
      'Complétez : C\'est ___ film que j\'ai jamais vu ! (le pire)',
      undefined,
      'le pire',
      'Le pire is the irregular superlative of mauvais (the worst).',
      'Le pire est le superlatif irrégulier de mauvais (the worst).',
    ],

    // ── ADVERBS ──────────────────────────────────────────────────────────────
    [
      'adverbs-a2',
      'multiple-choice',
      'Form the adverb from "rapide" (quick).',
      'Formez l\'adverbe de « rapide » (rapide).',
      ['rapidément', 'rapidment', 'rapidement', 'rapide'],
      'rapidement',
      'Most adverbs are formed from the feminine adjective + -ment: rapide → rapidement.',
      'La plupart des adverbes se forment à partir de l\'adjectif féminin + -ment : rapide → rapidement.',
    ],
    [
      'adverbs-a2',
      'fill',
      'Complete: Il parle ___ vite qu\'elle. (as fast as)',
      'Complétez : Il parle ___ vite qu\'elle. (aussi vite que)',
      undefined,
      'aussi',
      'Aussi...que expresses equality with adverbs: aussi vite que.',
      'Aussi...que exprime l\'égalité avec les adverbes : aussi vite que.',
    ],

    // ── TIME EXPRESSIONS ─────────────────────────────────────────────────────
    [
      'time-expressions-a2',
      'multiple-choice',
      '"I have been learning French for two years." Which expression fits?',
      '« J\'apprends le français ___ deux ans. » Quelle expression convient ?',
      ['pendant', 'depuis', 'il y a', 'dans'],
      'depuis',
      'Depuis marks duration that continues to the present.',
      'Depuis marque une durée qui continue jusqu\'au présent.',
    ],
    [
      'time-expressions-a2',
      'multiple-choice',
      '"I studied for three hours." Which expression fits?',
      '« J\'ai étudié ___ trois heures. » Quelle expression convient ?',
      ['depuis', 'il y a', 'pendant', 'dans'],
      'pendant',
      'Pendant expresses a completed duration.',
      'Pendant exprime une durée terminée.',
    ],
    [
      'time-expressions-a2',
      'fill',
      'Complete: Je l\'ai rencontré ___ six mois. (six months ago)',
      'Complétez : Je l\'ai rencontré ___ six mois. (il y a six mois)',
      undefined,
      'il y a',
      'Il y a + duration tells how long ago something happened.',
      'Il y a + durée indique depuis combien de temps quelque chose s\'est passé.',
    ],

    // ── FUTURE SIMPLE ────────────────────────────────────────────────────────
    [
      'future-simple-intro-a2',
      'multiple-choice',
      'A weather forecast says it will rain tomorrow. Choose the correct sentence.',
      'La météo annonce de la pluie demain. Choisissez la bonne phrase.',
      [
        'Il pleut demain.',
        'Il va pleuvoir demain.',
        'Il pleuvra demain.',
        'Il pleuvait demain.',
      ],
      'Il pleuvra demain.',
      'The futur simple (pleuvra) is standard for forecasts.',
      'Le futur simple (pleuvra) est standard pour les prévisions.',
    ],
    [
      'future-simple-intro-a2',
      'fill',
      'Complete: Nous ___ à la réunion à neuf heures. (être)',
      'Complétez : Nous ___ à la réunion à neuf heures. (être)',
      undefined,
      'serons',
      'Être uses the irregular future stem ser-: nous serons.',
      'Être utilise le radical irrégulier ser- : nous serons.',
    ],

    // ── CONDITIONAL POLITENESS ───────────────────────────────────────────────
    [
      'conditional-politeness-a2',
      'multiple-choice',
      'You call a hotel to book a room. Which phrase is most polite?',
      'Vous appelez un hôtel pour réserver une chambre. Quelle phrase est la plus polie ?',
      [
        'Je veux une chambre pour deux nuits.',
        'Donnez-moi une chambre.',
        'Je voudrais réserver une chambre pour deux nuits.',
        'Tu me donnes une chambre ?',
      ],
      'Je voudrais réserver une chambre pour deux nuits.',
      'Je voudrais is the polite conditional form used in requests.',
      'Je voudrais est la forme conditionnelle polie utilisée dans les demandes.',
    ],
    [
      'conditional-politeness-a2',
      'fill',
      'Complete the polite question: ___ -vous m\'aider, s\'il vous plaît ? (pouvoir)',
      'Complétez la question polie : ___ -vous m\'aider, s\'il vous plaît ? (pourriez)',
      undefined,
      'Pourriez',
      'Pourriez-vous is the polite conditional for could you.',
      'Pourriez-vous est la forme conditionnelle polie pour could you.',
    ],

    // ── RELATIVE PRONOUNS (A2 level qui/que/où) ──────────────────────────────
    [
      'relative-qui-que-ou-a2',
      'multiple-choice',
      'Connect the two ideas: "J\'ai un ami. Il parle six langues." → J\'ai un ami ___.',
      'Reliez les deux idées : « J\'ai un ami. Il parle six langues. » → J\'ai un ami ___.',
      ['que parle six langues.', 'qui parle six langues.', 'où parle six langues.', 'dont parle six langues.'],
      'qui parle six langues.',
      'Qui is the subject of the relative clause: un ami qui parle...',
      'Qui est le sujet de la proposition relative : un ami qui parle...',
    ],
    [
      'relative-qui-que-ou-a2',
      'fill',
      'Complete: Le café ___ tu aimes est fermé le lundi.',
      'Complétez : Le café ___ tu aimes est fermé le lundi.',
      undefined,
      'que',
      'Que is the direct object of aimes in the relative clause.',
      'Que est le COD de aimes dans la proposition relative.',
    ],
    [
      'relative-qui-que-ou-a2',
      'multiple-choice',
      'Choose: "The city ___ I was born is beautiful."',
      'Choisissez : « La ville ___ je suis né est magnifique. »',
      ['que', 'qui', 'dont', 'où'],
      'où',
      'Où refers to a place or time.',
      'Où renvoie à un lieu ou à un moment.',
    ],

    // ── NEGATION VARIED ──────────────────────────────────────────────────────
    [
      'negation-varied-a2',
      'multiple-choice',
      '"I no longer drink coffee." Which sentence is correct?',
      '« Je ne bois plus de café. » Quelle phrase est correcte ?',
      [
        'Je ne bois jamais de café.',
        'Je ne bois plus de café.',
        'Je ne bois rien de café.',
        'Je ne bois personne de café.',
      ],
      'Je ne bois plus de café.',
      'Ne...plus means no longer / no more.',
      'Ne...plus signifie no longer / no more.',
    ],
    [
      'negation-varied-a2',
      'fill',
      'Complete: Il ne mange ___ de viande. (nothing but / only)',
      'Complétez : Il ne mange ___ de viande. (ne...que)',
      undefined,
      'que',
      'Ne...que means only / nothing but.',
      'Ne...que signifie only / nothing but.',
    ],
    [
      'negation-varied-a2',
      'multiple-choice',
      'Transform to negative: Quelqu\'un a appelé. → ___',
      'Transformez à la forme négative : Quelqu\'un a appelé. → ___',
      [
        'Quelqu\'un n\'a pas appelé.',
        'Personne n\'a appelé.',
        'Rien n\'a appelé.',
        'Jamais quelqu\'un a appelé.',
      ],
      'Personne n\'a appelé.',
      'Quelqu\'un (someone) becomes personne (nobody) in the negative.',
      'Quelqu\'un (someone) devient personne (nobody) à la forme négative.',
    ],

    // ── SI CLAUSES (PRESENT + FUTURE) ────────────────────────────────────────
    [
      'si-present-future-a2',
      'multiple-choice',
      '"If it rains, I will stay home." Which is correct?',
      '« Si il pleut, je resterai à la maison. » Quelle phrase est correcte ?',
      [
        'Si il pleuvra, je resterai.',
        'Si il pleut, je resterai.',
        'Si il pleuvrait, je resterai.',
        'Si il pleurait, je resterai.',
      ],
      'Si il pleut, je resterai.',
      'Real conditions: si + present, then future (or imperative).',
      'Conditions réelles : si + présent, puis futur (ou impératif).',
    ],
    [
      'si-present-future-a2',
      'fill',
      'Complete: Si tu ___ fatigué, va dormir ! (être)',
      'Complétez : Si tu ___ fatigué, va dormir ! (être)',
      undefined,
      'es',
      'The si clause uses present tense: si tu es.',
      'La proposition avec si utilise le présent : si tu es.',
    ],

    // ── REPORTED SPEECH (A2) ─────────────────────────────────────────────────
    [
      'reported-speech-a2',
      'multiple-choice',
      'Report what Marie said: Marie: "Je suis malade." → Marie dit ___.',
      'Rapportez ce que Marie a dit : Marie : « Je suis malade. » → Marie dit ___.',
      [
        'qu\'elle est malade.',
        'qu\'elle était malade.',
        'elle est malade.',
        'que je suis malade.',
      ],
      'qu\'elle est malade.',
      'Dire que reports speech; the subject changes from je to elle.',
      'Dire que rapporte un discours ; le sujet change de je à elle.',
    ],

    // ── PAST PARTICIPLE AGREEMENT ────────────────────────────────────────────
    [
      'past-participle-agreement-a2',
      'multiple-choice',
      'Choose: "Les filles ___ parties de bonne heure."',
      'Choisissez : « Les filles ___ parties de bonne heure. »',
      ['ont', 'est', 'sont', 'avez'],
      'sont',
      'Partir uses être; les filles is subject → sont parties.',
      'Partir utilise être ; les filles est le sujet → sont parties.',
    ],
    [
      'past-participle-agreement-a2',
      'fill',
      'Agree the participle: Les résultats ont été ___ hier. (publier)',
      'Accordez le participe : Les résultats ont été ___ hier. (publier)',
      undefined,
      'publiés',
      'Résultats is masculine plural; publiés agrees with it after été.',
      'Résultats est masculin pluriel ; publiés s\'accorde avec lui après été.',
    ],

    // ── STRESSED PRONOUNS ────────────────────────────────────────────────────
    [
      'pronoms-toniques-a2',
      'multiple-choice',
      'Emphasize the subject: "Je suis d\'accord, ___."',
      'Insistez sur le sujet : « Je suis d\'accord, ___ ! »',
      ['me', 'moi', 'je', 'mon'],
      'moi',
      'Moi is the stressed pronoun used for emphasis.',
      'Moi est le pronom tonique utilisé pour l\'insistance.',
    ],
    [
      'pronoms-toniques-a2',
      'fill',
      'Complete: Ce cadeau est pour ___ (them – masculine plural).',
      'Complétez : Ce cadeau est pour ___ (eux).',
      undefined,
      'eux',
      'Eux is the stressed pronoun after a preposition for masculine plural.',
      'Eux est le pronom tonique après une préposition pour le masculin pluriel.',
    ],

    // ── OBLIGATION EXPRESSIONS ────────────────────────────────────────────────
    [
      'obligation-expressions-a2',
      'multiple-choice',
      'Your boss says everyone must attend the meeting. Which sentence does he use?',
      'Votre patron dit que tout le monde doit assister à la réunion. Quelle phrase utilise-t-il ?',
      [
        'Tout le monde veut assister.',
        'Il faut assister à la réunion.',
        'On peut assister à la réunion.',
        'Tout le monde aime assister.',
      ],
      'Il faut assister à la réunion.',
      'Il faut + infinitive is the standard impersonal obligation.',
      'Il faut + infinitif est l\'obligation impersonnelle standard.',
    ],
    [
      'obligation-expressions-a2',
      'fill',
      'Complete: Tu ___ réserver à l\'avance. (devoir)',
      'Complétez : Tu ___ réserver à l\'avance. (devoir)',
      undefined,
      'dois',
      'Devoir expresses personal obligation: tu dois.',
      'Devoir exprime l\'obligation personnelle : tu dois.',
    ],

    // ── PASSÉ RÉCENT ─────────────────────────────────────────────────────────
    [
      'passe-recent-a2',
      'multiple-choice',
      '"The bus just left." Which sentence is correct?',
      '« Le bus vient de partir. » Quelle phrase est correcte ?',
      [
        'Le bus est parti vient.',
        'Le bus vient de partir.',
        'Le bus venait de partir.',
        'Le bus va partir.',
      ],
      'Le bus vient de partir.',
      'Venir de + infinitive = just did (passé récent).',
      'Venir de + infinitif = vient de faire (passé récent).',
    ],

    // ── GÉRONDIF ─────────────────────────────────────────────────────────────
    [
      'gerondif-intro-a2',
      'multiple-choice',
      'Express "while listening to music": ___ de la musique, je révise.',
      'Exprimez « en écoutant de la musique » : ___ de la musique, je révise.',
      ['En écoutant', 'À écouter', 'De écouter', 'Pour écouter'],
      'En écoutant',
      'The gérondif uses en + present participle (écoutant).',
      'Le gérondif utilise en + participe présent (écoutant).',
    ],
    [
      'gerondif-intro-a2',
      'fill',
      'Complete: Il a appris le français ___ des séries françaises. (en regardant)',
      'Complétez : Il a appris le français ___ des séries françaises.',
      undefined,
      'en regardant',
      'En + present participle: en regardant.',
      'En + participe présent : en regardant.',
    ],

    // ── B1: PLUS-QUE-PARFAIT ─────────────────────────────────────────────────
    [
      'plus-que-parfait-b1',
      'multiple-choice',
      '"By the time I arrived, they had already eaten." Choose the correct plus-que-parfait.',
      '« Quand je suis arrivé, ils ___ déjà ___. » (manger)',
      ['avaient déjà mangé', 'ont déjà mangé', 'avaient déjà manger', 'ont déjà manger'],
      'avaient déjà mangé',
      'Plus-que-parfait: imparfait of avoir/être + past participle.',
      'Plus-que-parfait : imparfait de avoir/être + participe passé.',
    ],
    [
      'plus-que-parfait-b1',
      'fill',
      'Complete: Si seulement j\'___ étudié plus ! (avoir)',
      'Complétez : Si seulement j\'___ étudié plus ! (avoir)',
      undefined,
      'avais',
      'Plus-que-parfait with avoir: j\'avais étudié.',
      'Plus-que-parfait avec avoir : j\'avais étudié.',
    ],

    // ── B1: PASSIVE VOICE ────────────────────────────────────────────────────
    [
      'passive-voice-b1',
      'multiple-choice',
      'Transform to passive: "On a réparé la voiture." → ___',
      'Transformez à la voix passive : « On a réparé la voiture. » → ___',
      [
        'La voiture a été réparée.',
        'La voiture est réparée.',
        'La voiture a réparé.',
        'La voiture été réparée.',
      ],
      'La voiture a été réparée.',
      'Passive in passé composé: a été + past participle (agreeing with subject).',
      'Passif au passé composé : a été + participe passé (accordé avec le sujet).',
    ],
    [
      'passive-voice-b1',
      'fill',
      'Complete: Le rapport sera ___ demain matin. (rédiger)',
      'Complétez : Le rapport sera ___ demain matin. (rédiger)',
      undefined,
      'rédigé',
      'Passive future: sera + past participle rédigé.',
      'Passif futur : sera + participe passé rédigé.',
    ],

    // ── B1: SUBJUNCTIVE ──────────────────────────────────────────────────────
    [
      'subjunctive-basic-b1',
      'multiple-choice',
      '"I am glad that you are here." Which is correct?',
      '« Je suis content que tu ___ là. » (être)',
      ['es', 'soit', 'sois', 'étais'],
      'sois',
      'Emotion + que triggers the subjunctive: tu sois.',
      'Une émotion + que déclenche le subjonctif : tu sois.',
    ],
    [
      'subjunctive-basic-b1',
      'fill',
      'Complete: Il faut que vous ___ patient. (être)',
      'Complétez : Il faut que vous ___ patient. (être)',
      undefined,
      'soyez',
      'Vous subjunctive of être is soyez.',
      'Le subjonctif de être avec vous est soyez.',
    ],
    [
      'subjunctive-basic-b1',
      'multiple-choice',
      'Which expression does NOT trigger the subjunctive?',
      'Quelle expression ne déclenche PAS le subjonctif ?',
      ['il est possible que', 'je doute que', 'je suis sûr que', 'il est dommage que'],
      'je suis sûr que',
      'Certainty (je suis sûr que) uses the indicative, not the subjunctive.',
      'La certitude (je suis sûr que) utilise l\'indicatif, pas le subjonctif.',
    ],

    // ── B1: SI + IMPARFAIT / CONDITIONAL ────────────────────────────────────
    [
      'si-imparfait-conditional-b1',
      'multiple-choice',
      '"If I had a car, I would visit my grandparents more often." Which is correct?',
      '« Si j\'___ une voiture, je ___ mes grands-parents plus souvent. »',
      [
        'ai / visiterais',
        'avais / visiterais',
        'aurais / visiterais',
        'avais / visiterai',
      ],
      'avais / visiterais',
      'Si + imparfait (avais) → conditional (visiterais) for unreal present.',
      'Si + imparfait (avais) → conditionnel (visiterais) pour un irréel présent.',
    ],
    [
      'si-imparfait-conditional-b1',
      'fill',
      'Complete: Si tu savais la vérité, tu ___ surpris. (être)',
      'Complétez : Si tu savais la vérité, tu ___ surpris. (être)',
      undefined,
      'serais',
      'Conditional of être with tu: tu serais.',
      'Le conditionnel de être avec tu : tu serais.',
    ],

    // ── B1: CONNECTORS ────────────────────────────────────────────────────────
    [
      'connectors-cause-consequence-b1',
      'multiple-choice',
      'Choose the correct connector: "I stayed home ___ it was raining."',
      'Choisissez le bon connecteur : « Je suis resté chez moi ___ il pleuvait. »',
      ['donc', 'cependant', 'parce que', 'pourtant'],
      'parce que',
      'Parce que introduces a cause / reason.',
      'Parce que introduit une cause / raison.',
    ],
    [
      'connectors-cause-consequence-b1',
      'fill',
      'Complete: Il est cher, ___ il est de bonne qualité. (however)',
      'Complétez : Il est cher, ___ il est de bonne qualité. (cependant)',
      undefined,
      'cependant',
      'Cependant means however / nevertheless.',
      'Cependant signifie however / nevertheless.',
    ],
    [
      'connectors-cause-consequence-b1',
      'multiple-choice',
      'Which connector introduces a consequence?',
      'Quel connecteur introduit une conséquence ?',
      ['parce que', 'car', 'donc', 'bien que'],
      'donc',
      'Donc means therefore / so, introducing a consequence.',
      'Donc signifie therefore / so, introduisant une conséquence.',
    ],

    // ── B1: PAST CONDITIONAL ─────────────────────────────────────────────────
    [
      'conditionnel-passe-b1',
      'multiple-choice',
      '"You should have called me!" Which sentence expresses this regret?',
      '« Tu aurais dû m\'appeler ! » Quelle phrase exprime ce reproche ?',
      [
        'Tu devais m\'appeler.',
        'Tu aurais dû m\'appeler.',
        'Tu devrais m\'appeler.',
        'Tu avais dû m\'appeler.',
      ],
      'Tu aurais dû m\'appeler.',
      'Aurais dû (past conditional of devoir) expresses a reproach about the past.',
      'Aurais dû (conditionnel passé de devoir) exprime un reproche sur le passé.',
    ],
    [
      'conditionnel-passe-b1',
      'fill',
      'Complete: Nous ___ partir plus tôt. (pouvoir – regret)',
      'Complétez : Nous ___ partir plus tôt. (pouvoir – regret)',
      undefined,
      'aurions pu',
      'Aurions pu is the past conditional of pouvoir (we could have).',
      'Aurions pu est le conditionnel passé de pouvoir (we could have).',
    ],

    // ── B1: ADVANCED NEGATION ────────────────────────────────────────────────
    [
      'advanced-negation-b1',
      'multiple-choice',
      '"Neither Paul nor Sophie came." Which is correct?',
      '« Ni Paul ni Sophie ___ venu(e). » Quelle phrase est correcte ?',
      [
        'Ni Paul ni Sophie est venu.',
        'Ni Paul ni Sophie ne sont venus.',
        'Paul ni Sophie n\'est venu.',
        'Ni Paul ni Sophie ne venait.',
      ],
      'Ni Paul ni Sophie ne sont venus.',
      'Ni...ni pairs with ne; the verb agrees with the two subjects.',
      'Ni...ni s\'utilise avec ne ; le verbe s\'accorde avec les deux sujets.',
    ],
    [
      'advanced-negation-b1',
      'fill',
      'Complete: Je n\'ai ___ envie de sortir ce soir. (not at all)',
      'Complétez : Je n\'ai ___ envie de sortir ce soir. (aucune)',
      undefined,
      'aucune',
      'Aucun(e) means not a single / no, and agrees with the noun (envie is feminine).',
      'Aucun(e) signifie not a single / no, et s\'accorde avec le nom (envie est féminin).',
    ],

    // ── B1: REPORTED SPEECH IN THE PAST ──────────────────────────────────────
    [
      'reported-speech-past-b1',
      'multiple-choice',
      'Report what he said: "Je suis fatigué." → Il a dit ___.',
      'Rapportez : « Je suis fatigué. » → Il a dit ___',
      [
        'qu\'il est fatigué.',
        'qu\'il était fatigué.',
        'qu\'il soit fatigué.',
        'qu\'il serait fatigué.',
      ],
      'qu\'il était fatigué.',
      'When the reporting verb is in the past, the present tense shifts to imparfait.',
      'Quand le verbe introducteur est au passé, le présent devient imparfait.',
    ],
    [
      'reported-speech-past-b1',
      'fill',
      'Complete: Elle a expliqué qu\'elle ___ son billet. (perdre – past reported)',
      'Complétez : Elle a expliqué qu\'elle ___ son billet. (perdre)',
      undefined,
      'avait perdu',
      'Reported speech shifts passé composé to plus-que-parfait: avait perdu.',
      'Le discours rapporté transforme le passé composé en plus-que-parfait : avait perdu.',
    ],

    // ── B1: DOUBLE PRONOUNS ──────────────────────────────────────────────────
    [
      'double-pronouns-b1',
      'multiple-choice',
      'Replace "le livre à mon ami": Tu donnes le livre à mon ami. → ___',
      'Remplacez « le livre à mon ami » : Tu donnes le livre à mon ami. → ___',
      [
        'Tu lui le donnes.',
        'Tu le lui donnes.',
        'Tu les lui donnes.',
        'Tu y le donnes.',
      ],
      'Tu le lui donnes.',
      'Direct object (le) comes before indirect object (lui).',
      'Le COD (le) se place avant le COI (lui).',
    ],
    [
      'double-pronouns-b1',
      'fill',
      'Complete: Des nouvelles ? Elle nous ___ donnera demain. (en)',
      'Complétez : Des nouvelles ? Elle nous ___ donnera demain.',
      undefined,
      'en',
      'Nous comes before en: elle nous en donnera.',
      'Nous se place avant en : elle nous en donnera.',
    ],

    // ── B1: FUTUR ANTÉRIEUR ───────────────────────────────────────────────────
    [
      'futur-anterieur-b1',
      'multiple-choice',
      '"When you arrive, I will have already cooked." Choose the futur antérieur.',
      '« Quand tu arriveras, j\'___ déjà ___. » (cuisiner)',
      ['aurai déjà cuisiné', 'aurais déjà cuisiné', 'ai déjà cuisiné', 'avais déjà cuisiné'],
      'aurai déjà cuisiné',
      'Futur antérieur: future of avoir/être + past participle.',
      'Futur antérieur : futur de avoir/être + participe passé.',
    ],
    [
      'futur-anterieur-b1',
      'fill',
      'Complete: Dès qu\'elle ___ (finir), nous partirons.',
      'Complétez : Dès qu\'elle ___ (finir), nous partirons.',
      undefined,
      'aura fini',
      'After dès que with a future clause, use futur antérieur: aura fini.',
      'Après dès que avec une proposition future, on utilise le futur antérieur : aura fini.',
    ],

    // ── B1: DONT, CE QUI, CE QUE ──────────────────────────────────────────────
    [
      'dont-ce-qui-ce-que-b1',
      'multiple-choice',
      '"What I like is travelling." Choose the correct form.',
      '« ___ j\'aime, c\'est voyager. »',
      ['Que', 'Ce que', 'Ce qui', 'Qui'],
      'Ce que',
      'Ce que is the direct object of j\'aime.',
      'Ce que est le COD de j\'aime.',
    ],
    [
      'dont-ce-qui-ce-que-b1',
      'fill',
      'Complete: C\'est un film ___ tout le monde parle.',
      'Complétez : C\'est un film ___ tout le monde parle.',
      undefined,
      'dont',
      'Parler de → dont in the relative clause.',
      'Parler de → dont dans la proposition relative.',
    ],

    // ── B1: CONCESSION ────────────────────────────────────────────────────────
    [
      'concession-b1',
      'multiple-choice',
      '"Although it is expensive, I bought it." Which is correct?',
      '« ___ c\'est cher, je l\'ai acheté. »',
      [
        'Même si c\'était cher,',
        'Bien que c\'est cher,',
        'Bien qu\'il soit cher,',
        'Malgré c\'est cher,',
      ],
      'Bien qu\'il soit cher,',
      'Bien que + subjunctive: bien qu\'il soit cher.',
      'Bien que + subjonctif : bien qu\'il soit cher.',
    ],
    [
      'concession-b1',
      'fill',
      'Complete: ___ ses efforts, il n\'a pas réussi. (malgré)',
      'Complétez : ___ ses efforts, il n\'a pas réussi.',
      undefined,
      'Malgré',
      'Malgré + noun (no verb) expresses despite.',
      'Malgré + nom (sans verbe) exprime despite.',
    ],

    // ── B2: SUBJUNCTIVE ──────────────────────────────────────────────────────
    [
      'subjunctive',
      'multiple-choice',
      '"I want you to come." Which sentence uses the subjunctive correctly?',
      '« Je veux que tu ___ » (venir)',
      ['viens', 'viennes', 'viendrais', 'es venu'],
      'viennes',
      'After vouloir que, use the subjunctive: tu viennes.',
      'Après vouloir que, on utilise le subjonctif : tu viennes.',
    ],
    [
      'subjunctive',
      'fill',
      'Complete: Bien qu\'il ___ malade, il est venu. (être)',
      'Complétez : Bien qu\'il ___ malade, il est venu. (être)',
      undefined,
      'soit',
      'Bien que triggers the subjunctive: il soit.',
      'Bien que déclenche le subjonctif : il soit.',
    ],
    [
      'subjunctive',
      'multiple-choice',
      'Which verb is in the subjunctive?',
      'Quel verbe est au subjonctif ?',
      ['je vais', 'tu fasses', 'nous avons', 'ils mangent'],
      'tu fasses',
      'Fasses is the subjunctive of faire with tu.',
      'Fasses est le subjonctif de faire avec tu.',
    ],

    // ── B2: SI CLAUSES (full range) ──────────────────────────────────────────
    [
      'si-clauses',
      'multiple-choice',
      '"If he had studied more, he would have passed." Choose the correct form.',
      '« S\'il ___ plus, il ___ l\'examen. »',
      [
        'avait étudié / aurait réussi',
        'étudiait / réussirait',
        'a étudié / aura réussi',
        'étudie / réussira',
      ],
      'avait étudié / aurait réussi',
      'Unreal past condition: si + plus-que-parfait → past conditional.',
      'Condition irréelle passée : si + plus-que-parfait → conditionnel passé.',
    ],
    [
      'si-clauses',
      'fill',
      'Complete: Si nous ___ su, nous aurions réagi autrement. (savoir)',
      'Complétez : Si nous ___ su, nous aurions réagi autrement. (savoir)',
      undefined,
      'avions',
      'Si + plus-que-parfait: si nous avions su.',
      'Si + plus-que-parfait : si nous avions su.',
    ],
    [
      'si-clauses',
      'multiple-choice',
      'Which sentence uses the correct tense sequence for a real future condition?',
      'Quelle phrase utilise la bonne séquence de temps pour une condition future réelle ?',
      [
        'Si tu viendrais, on irait au cinéma.',
        'Si tu viens, on ira au cinéma.',
        'Si tu venais, on ira au cinéma.',
        'Si tu viens, on allait au cinéma.',
      ],
      'Si tu viens, on ira au cinéma.',
      'Real future condition: si + present → future.',
      'Condition future réelle : si + présent → futur.',
    ],

    // ── B1: NOMINALIZATION ───────────────────────────────────────────────────
    [
      'nominalization-b1',
      'multiple-choice',
      'What is the noun derived from "développer" (to develop)?',
      'Quel est le nom dérivé de « développer » ?',
      ['le développeur', 'la développation', 'le développement', 'la développure'],
      'le développement',
      'The most common pattern: -er → -ement (développement).',
      'Le modèle le plus courant : -er → -ement (développement).',
    ],
    [
      'nominalization-b1',
      'fill',
      'Nominalize: décider → la ___',
      'Nominalisez : décider → la ___',
      undefined,
      'décision',
      'Décider → la décision (-tion pattern).',
      'Décider → la décision (modèle -tion).',
    ],

    // ── B1: OPINION / ARGUMENT ───────────────────────────────────────────────
    [
      'opinion-argument-b1',
      'multiple-choice',
      'Which phrase introduces a personal opinion in French?',
      'Quelle phrase introduit une opinion personnelle en français ?',
      ['Il est vrai que', 'À mon avis,', 'Il faut que', 'Il semble que'],
      'À mon avis,',
      'À mon avis means in my opinion and introduces a personal view.',
      'À mon avis signifie in my opinion et introduit un point de vue personnel.',
    ],
    [
      'opinion-argument-b1',
      'fill',
      'Complete: ___ une part, c\'est pratique ; d\'autre part, c\'est coûteux. (D\'une)',
      'Complétez : ___ une part, c\'est pratique ; d\'autre part, c\'est coûteux.',
      undefined,
      'D\'une',
      'D\'une part... d\'autre part means on one hand... on the other hand.',
      'D\'une part... d\'autre part signifie on one hand... on the other hand.',
    ],

    // ── FUTUR SIMPLE IRREGULAR B1 ────────────────────────────────────────────
    [
      'futur-simple-irregular-b1',
      'multiple-choice',
      '"She will not be able to come." Choose the correct future form of pouvoir.',
      '« Elle ne ___ pas venir. » Choisissez la forme correcte du futur de pouvoir.',
      ['peut', 'pourra', 'pouvra', 'pouvait'],
      'pourra',
      'Pouvoir → future stem pourr-: elle pourra.',
      'Pouvoir → radical futur pourr- : elle pourra.',
    ],
    [
      'futur-simple-irregular-b1',
      'fill',
      'Complete: Il ___ peut-être un médecin un jour. (vouloir → futur)',
      'Complétez : Il ___ peut-être un médecin un jour. (vouloir → futur)',
      undefined,
      'voudra',
      'Vouloir → future stem voudr-: il voudra.',
      'Vouloir → radical futur voudr- : il voudra.',
    ],

    // ── CAUSE EXPRESSIONS B1 ─────────────────────────────────────────────────
    [
      'cause-expressions-b1',
      'multiple-choice',
      '"Thanks to the internet, I learned French quickly." Choose the correct expression.',
      '« ___ internet, j\'ai appris le français rapidement. »',
      ['À cause d\'', 'Grâce à', 'Car', 'Puisque'],
      'Grâce à',
      'Grâce à is used for a positive cause; à cause de for a negative one.',
      'Grâce à s\'utilise pour une cause positive ; à cause de pour une cause négative.',
    ],
    [
      'cause-expressions-b1',
      'fill',
      'Complete: ___ tu insistes, d\'accord, je viens ! (puisque)',
      'Complétez : ___ tu insistes, d\'accord, je viens !',
      undefined,
      'Puisque',
      'Puisque introduces a known or obvious reason.',
      'Puisque introduit une raison connue ou évidente.',
    ],
  ] satisfies QuestionRow[]
).map((row, index) => ({
  id: `eq-${index + 1}`,
  topicId: row[0],
  type: row[1],
  promptEn: row[2],
  promptFr: row[3],
  choices: row[4],
  correctAnswer: row[5],
  explanationEn: row[6],
  explanationFr: row[7],
}))
