import type { VocabCard, VocabDeck } from './types'

const today = new Date().toISOString()

export const totem3LexiconDeck: VocabDeck = {
  id: 'totem3-lexicon',
  title: 'TOTEM3',
  description: '',
  level: 'B1',
  tags: ['totem', 'lexicon'],
  source: 'totem',
  difficulty: 3,
  estimatedMinutes: 30,
}

const cardRows: Array<[string, string, VocabCard['gender'] | undefined]> = [
  // Page 177
  ['à l\'endroit', 'the right way round', undefined],
  ['à l\'envers', 'inside out', undefined],
  ['à pleine voix', 'loudly (voice)', undefined],
  ['abbaye', 'abbey', 'f'],
  ['accéder à', 'to access (v.)', undefined],
  ['accentuer', 'to accentuate (v.)', undefined],
  ['accueillir', 'to welcome (v.)', undefined],
  ['acte', 'act (noun)', 'm'],
  ['acte citoyen', 'civic deed', 'm'],
  ['actif', 'active person', 'm'],
  ['action sociale', 'social / civic action', 'f'],
  ['actualité', 'current affairs', 'f'],
  ['adhérer à', 'to join (v.)', undefined],
  ['admiratif', 'admiring (adj.)', undefined],
  ['adopter', 'to adopt (v.)', undefined],
  ['adoration', 'adoration', 'f'],
  ['affecter', 'to affect (v.)', undefined],
  ['agence', 'agency', 'f'],
  ['ah la vache !', 'Oh my gosh! (colloquial)', undefined],
  ['alerter', 'to alert (v.)', undefined],
  ['aller à la rencontre de', 'to go and meet', undefined],
  ['allonger (le bras)', 'to stretch out (the arm) (v.)', undefined],
  ['Allez...', 'Come on...', undefined],
  ['alterner', 'to alternate (v.)', undefined],
  ['analyser', 'to analyse (v.)', undefined],
  ['anciens', 'elders', undefined],
  ['anglicisme', 'Anglicism', 'm'],
  ['angoissé', 'anguished (adj.)', undefined],
  ['apôtre', 'apostle', 'm'],
  ['apprentissage', 'learning (noun)', 'm'],
  ['approfondir', 'to go deeper into', undefined],
  ['atmosphère', 'atmosphere', 'f'],
  ['atroce', 'atrocious (adj.)', undefined],
  ['attractivité', 'attractiveness', 'f'],
  ['authenticité', 'authenticity', 'f'],
  ['autorité', 'authority', 'f'],
  ['autres cieux', 'other climes', undefined],
  ['aux quatre coins du monde', 'to the four corners of the earth', undefined],
  ['avantages sociaux', 'fringe benefits', undefined],
  ['avec le temps', 'with time', undefined],
  ['avoir accès à', 'have access to', undefined],
  ['avoir la forme', 'to be on form', undefined],
  ['bain de jouvence', 'rejuvenating experience', 'm'],
  ['bain de mer', 'bathing in the sea', 'm'],
  ['bain de soleil', 'sunbathing (noun)', 'm'],
  ['base de tout', 'the basis of everything', 'f'],

  // Page 178
  ['beau-père', 'father-in-law, stepfather', 'm'],
  ['beauté', 'beauty', 'f'],
  ['belle-mère', 'mother-in-law, stepmother', 'f'],
  ['bikini', 'bikini', 'm'],
  ['blouse', 'overall (clothing)', 'f'],
  ['bois', 'wood', 'm'],
  ['Bon bah...', 'Well, er...', undefined],
  ['bon débarras', 'good riddance', undefined],
  ['Bon écoute...', 'OK, listen...', undefined],
  ['bonheur', 'happiness', 'm'],
  ['bonne volonté', 'good will', 'f'],
  ['bosser', 'to work, to slog (v.)', undefined],
  ['bouddhiste', 'Buddhist', 'm'],
  ['bouffe', 'grub (informal)', 'f'],
  ['bouquiner', 'to read (a book) (v.)', undefined],
  ['bracelet', 'bracelet', 'm'],
  ['bras', 'arm (noun)', 'm'],
  ['bronzer', 'to get a tan', undefined],
  ['brosse à dents', 'toothbrush', 'f'],
  ['brûler des calories', 'to burn off calories', undefined],
  ['c\'est dingue', 'it\'s crazy', undefined],
  ['c\'est fou', 'it\'s mad', undefined],
  ['c\'est génial', 'it\'s great', undefined],
  ['c\'est histoire de', 'it\'s a question of', undefined],
  ['c\'est reparti', 'here we go again', undefined],
  ['c\'est une très bonne chose', 'it\'s a very good thing', undefined],
  ['ça fait des histoires', 'it creates problems', undefined],
  ['ça marque quelque chose', 'that marks something', undefined],
  ['cadre administratif', 'administrative framework', 'm'],
  ['calcium', 'calcium', 'm'],
  ['calculer que', 'calculate that', undefined],
  ['caméras de surveillance', 'CCTV cameras', undefined],
  ['CAP', '"CAP" (vocational training certificate)', 'm'],
  ['capter', 'to pick up, to capture (v.)', undefined],
  ['capteurs', 'sensors', undefined],
  ['caresse', 'caress (noun)', 'f'],
  ['carrière', 'career (noun)', 'f'],
  ['carte du monde', 'map of the world', 'f'],
  ['catalogue', 'catalogue (noun)', 'm'],
  ['cathédrale', 'cathedral', 'f'],
  ['catholique', 'Catholic', 'm'],
  ['cauchemar', 'nightmare', 'm'],
  ['célibataire', 'single (adj.)', undefined],
  ['Cène', 'the Last Supper', 'f'],

  // Page 179
  ['certaine classe', 'a certain excellence', 'f'],
  ['certitude', 'certainty', 'f'],
  ['chagrin', 'grief, sorrow', 'm'],
  ['chambre', 'room, bedroom', 'f'],
  ['chanson', 'song', 'f'],
  ['chapelet', 'rosary', 'm'],
  ['chapelle', 'chapel', 'f'],
  ['charte', 'charter (noun)', 'f'],
  ['chasseur d\'images', 'image hunter', 'm'],
  ['chat', 'cat', 'm'],
  ['chef d\'État', 'head of state', 'm'],
  ['chemin de l\'école', 'way to school', 'm'],
  ['cher / chérie', 'dear, darling (adj.)', undefined],
  ['chercher', 'to look for (v.)', undefined],
  ['chic', 'style (noun)', undefined],
  ['chômage', 'unemployment', 'm'],
  ['chronique', 'column (in newspaper)', 'f'],
  ['clés', 'keys', undefined],
  ['cliché', 'cliché', 'm'],
  ['cligner de l\'œil', 'to wink (v.)', undefined],
  ['clin d\'œil', 'wink (noun)', 'm'],
  ['clocher', 'church tower', 'm'],
  ['cœur', 'heart', 'm'],
  ['cognitif', 'cognitive (adj.)', undefined],
  ['colocataire / coloc', 'housemate, flatmate', 'm/f'],
  ['combattre', 'to fight (v.)', undefined],
  ['comme un fou', 'like a mad person', undefined],
  ['commentaire', 'comment (noun)', 'm'],
  ['commerce', 'commerce', 'm'],
  ['communication', 'communication', 'f'],
  ['communier', 'to receive communion', undefined],
  ['comparer', 'to compare (v.)', undefined],
  ['compliment', 'compliment (noun)', 'm'],
  ['composer son information à la carte', 'key in your à la carte information', undefined],
  ['confiance', 'trust (noun)', 'f'],
  ['congés payés', 'paid holidays', undefined],
  ['connaissance', 'knowledge', 'f'],
  ['connaître', 'to know (v.)', undefined],
  ['connecter', 'to connect (v.)', undefined],
  ['consommer', 'to consume (v.)', undefined],
  ['consultation', 'consultation (medical)', 'f'],
  ['contenir', 'contain (v.)', undefined],
  ['contexte', 'context', 'm'],
  ['continuer sur sa lancée', 'to keep up the momentum', undefined],

  // Page 180
  ['contradiction', 'contradiction', 'f'],
  ['contribuer à', 'to contribute (v.)', undefined],
  ['coque de téléphone', 'phone casing', 'f'],
  ['corbeau', 'crow (noun)', 'm'],
  ['coup de soleil', 'sun stroke', 'm'],
  ['couple', 'couple', 'm'],
  ['création', 'creation', 'f'],
  ['création d\'emploi', 'job creation', 'f'],
  ['crise économique', 'economic crisis', 'f'],
  ['critique', 'criticism', 'f'],
  ['croix', 'cross (noun)', 'f'],
  ['croyance populaire', 'popular belief', 'f'],
  ['culture', 'culture', 'f'],
  ['débat', 'debate (noun)', 'm'],
  ['débattre', 'to debate (v.)', undefined],
  ['décennie', 'decade', 'f'],
  ['déclaration', 'declaration', 'f'],
  ['décor', 'decor', 'm'],
  ['découverte', 'discovery', 'f'],
  ['décrocher', 'to drop out (v.)', undefined],
  ['dédié à', 'dedicated to (adj.)', undefined],
  ['défendre', 'to defend (v.)', undefined],
  ['démonstrateur / démonstratrice', 'demonstrator', 'm/f'],
  ['design', 'designer (adj.)', undefined],
  ['détente', 'relaxation', 'f'],
  ['déterminer', 'to determine (v.)', undefined],
  ['Deuxième Guerre mondiale', 'Second World War', 'f'],
  ['deux-pièces', 'two-piece swimsuit', 'm'],
  ['développement', 'development', 'm'],
  ['développer une amitié', 'to develop a friendship', undefined],
  ['diable', 'the devil', 'm'],
  ['dialogue', 'dialogue', 'm'],
  ['didascalies', 'stage directions', undefined],
  ['Dieu', 'God', 'm'],
  ['diffuser', 'to broadcast (v.)', undefined],
  ['diplômé', 'graduate, qualified (adj.)', undefined],
  ['dirigeant', 'director', 'm'],
  ['dispositif', 'mechanism', 'm'],
  ['dispute', 'dispute (noun)', 'f'],
  ['diversité', 'diversity', 'f'],
  ['divorcer', 'to divorce (v.)', undefined],
  ['domotique', 'home automation', 'f'],
  ['données', 'data', undefined],
  ['donner un sens (à sa vie)', 'to give meaning (to one\'s life)', undefined],
  ['douleur', 'pain (noun)', 'f'],
  ['doute', 'doubt (noun)', 'm'],
  ['du fond du cœur', 'from the bottom of one\'s heart', undefined],

  // Page 181
  ['dur', 'hard', 'm'],
  ['eau salée', 'salt water', 'f'],
  ['écolier', 'school child', 'm'],
  ['écolo', 'environmental (adj.)', undefined],
  ['écran', 'screen (noun)', 'm'],
  ['éditorialiste', 'editorialist', 'm'],
  ['effectifs', 'staff (noun)', undefined],
  ['église', 'church', 'f'],
  ['égoïste', 'selfish (adj.)', undefined],
  ['élever', 'to raise (v.)', undefined],
  ['éloigner', 'to move something away', undefined],
  ['emmener', 'to take (v.)', undefined],
  ['emprunter (un mot)', 'to borrow (a word) (v.)', undefined],
  ['emprunteur', 'borrower', 'm'],
  ['en esprit', 'in spirit', undefined],
  ['en groupe', 'in a group', undefined],
  ['en libre-service', 'self service', undefined],
  ['endorphine', 'endorphin', 'f'],
  ['enfants', 'children', undefined],
  ['engagé', 'committed, taking a stand', undefined],
  ['ennui', 'annui, boredom', 'm'],
  ['enquête', 'survey (noun)', 'f'],
  ['enregistrer', 'to register (v.)', undefined],
  ['enseignement', 'teaching (noun)', 'm'],
  ['ensoleillement', 'sunlight', 'm'],
  ['entraide', 'mutual aid', 'f'],
  ['entre', 'between (prep.)', undefined],
  ['entretenir son corps', 'to look after one\'s body', undefined],
  ['entretenir une culture', 'to maintain a culture', undefined],
  ['envahir', 'to possess (of an emotion) (v.)', undefined],
  ['envie', 'desire (noun)', 'f'],
  ['éprouver', 'to feel (v.)', undefined],
  ['est', 'east', 'm'],
  ['esthétique', 'aesthetics', 'f'],
  ['éthique', 'ethics', 'f'],
  ['éthique (adj.)', 'ethical (adj.)', undefined],
  ['être (très) bon pour', 'to be (very) good for', undefined],
  ['être à l\'aise', 'to be at ease', undefined],
  ['être accro à', 'to be addicted to', undefined],
  ['être banni', 'to be exiled, banished', undefined],
  ['être conditionné(e) en bouteilles', 'to be packaged in bottles', undefined],
  ['être dans le rouge', 'to be in the red', undefined],
  ['être dans tes bras', 'to be in your arms', undefined],

  // Page 182
  ['être en forme', 'to be on form', undefined],
  ['être en pleine mutation', 'to be undergoing a transformation', undefined],
  ['être gêné', 'to be embarrassed, uncomfortable', undefined],
  ['être issu de', 'to come from', undefined],
  ['être naturalisé', 'to be naturalised', undefined],
  ['être qualifié', 'to be qualified', undefined],
  ['être signe de', 'to be a sign of', undefined],
  ['être soutenu', 'to be supported (backed up)', undefined],
  ['étude', 'study (learning)', 'f'],
  ['étude (une)', 'study (noun)', 'f'],
  ['évasion', 'evasion', 'f'],
  ['évoquer', 'to evoke (v.)', undefined],
  ['examiner', 'to examine (v.)', undefined],
  ['expatrié', 'expatriate (adj.)', undefined],
  ['exposition (au soleil)', 'exposure (to the sun)', 'f'],
  ['exposition', 'exhibition', 'f'],
  ['extérieur', 'exterior', 'm'],
  ['facile', 'easy', 'm'],
  ['faire gaffe à', 'to watch out for', undefined],
  ['faire la sieste', 'to have a siesta', undefined],
  ['faire le tour de la Terre', 'to go round the world', undefined],
  ['fait', 'fact', 'm'],
  ['famille biologique', 'biological family', 'f'],
  ['famille monoparentale', 'single-parent family', 'f'],
  ['famille réelle', 'real family', 'f'],
  ['fantôme', 'ghost', 'm'],
  ['fatigant', 'tiring (adj.)', undefined],
  ['favoriser', 'to favour (v.)', undefined],
  ['fée', 'fairy', 'f'],
  ['fer à cheval', 'horseshoe', 'm'],
  ['fête nationale', 'national holiday', 'f'],
  ['fêter', 'to celebrate (v.)', undefined],
  ['fin de la guerre', 'end of the war', 'f'],
  ['finances', 'finances', undefined],
  ['flagship', 'flagship', 'm'],
  ['foie', 'liver', 'm'],
  ['formation', 'training (noun)', 'f'],
  ['forme', 'form (noun)', 'f'],
  ['fourchette', 'fork', 'f'],
  ['francophile', 'Francophile (adj.)', undefined],
  ['francophone', 'French speaker', 'm/f'],
  ['francophonie', 'the French speaking world', 'f'],
  ['franglais', 'franglais', 'm'],

  // Page 183
  ['gagner', 'to earn (v.)', undefined],
  ['gant', 'glove (noun)', 'm'],
  ['garage', 'garage (noun)', 'm'],
  ['garde alternée / en alternance', 'alternating custody', 'f'],
  ['garder dans son cœur', 'to keep in one\'s heart', undefined],
  ['genoux', 'knees', undefined],
  ['glamour', 'glamour', 'm'],
  ['grandir', 'to grow up (v.)', undefined],
  ['grève', 'strike (noun)', 'f'],
  ['gros', 'large (adj.)', undefined],
  ['hanche', 'hip (noun)', 'f'],
  ['hausse', 'rise (noun)', 'f'],
  ['histoires passionnées', 'exciting stories', undefined],
  ['honnête', 'honest (adj.)', undefined],
  ['honneur', 'honor (noun)', 'm'],
  ['honorer', 'to honour (v.)', undefined],
  ['honte', 'shame (noun)', 'f'],
  ['horizon', 'horizon', 'm'],
  ['humanoïdes', 'humanoids', undefined],
  ['humidité', 'humidity', 'f'],
  ['icône', 'icon', 'f'],
  ['idéalisation', 'idealisation', 'f'],
  ['identification', 'identification', 'f'],
  ['idole', 'idol', 'f'],
  ['illusion', 'illusion', 'f'],
  ['image', 'image', 'f'],
  ['imaginaire', 'imaginary things', 'm'],
  ['imagination', 'imagination', 'f'],
  ['impact', 'impact, effect', 'm'],
  ['inaltérable', 'unchangeable (adj.)', undefined],
  ['inconnaissable', 'unknowable (adj.)', undefined],
  ['individuel', 'individual (adj.)', undefined],
  ['inégalité', 'inequality', 'f'],
  ['influence', 'influence (noun)', 'f'],
  ['influencer', 'to influence (v.)', undefined],
  ['innovant', 'innovative (adj.)', undefined],
  ['innovations', 'innovations', undefined],
  ['innover', 'to innovate (v.)', undefined],
  ['inquiétude', 'worry (noun)', 'f'],
  ['insouciance', 'carefree attitude', 'f'],
  ['instruments à vent', 'wind instrument', undefined],
  ['intéressant', 'interesting (adj.)', undefined],
  ['intérêt', 'interest', 'm'],
  ['intuition', 'intuition', 'f'],
  ['investissement', 'investment', 'm'],
  ['invisible', 'invisible', 'm'],
  ['j\'en rêve', 'I dream of it', undefined],
  ['je suis fou de joie', 'I\'m mad with joy', undefined],

  // Page 184
  ['je suis pas trop (histoire)', 'I\'m not that (I don\'t know that much about) (history)', undefined],
  ['je-ne-sais-quoi', 'a certain "je ne sais quoi"', 'm'],
  ['jeter', 'to throw (v.)', undefined],
  ['joie', 'joy', 'f'],
  ['juif', 'Jew', 'm'],
  ['l\'entrée', 'hall', 'f'],
  ['langage', 'language', 'm'],
  ['langue de Molière', 'the language of Molière (i.e. French)', 'f'],
  ['lapin', 'rabbit', 'm'],
  ['lecture en musique', 'reading music', 'f'],
  ['liberté d\'expression', 'freedom of expression', 'f'],
  ['liberté de parole', 'freedom of speech', 'f'],
  ['lingerie', 'lingerie', 'f'],
  ['linguiste', 'linguist', 'm/f'],
  ['localisateur GPS', 'GPS locator', 'm'],
  ['localiser', 'to locate (v.)', undefined],
  ['logistique', 'logistics', 'f'],
  ['lointains voyages', 'distant journeys', undefined],
  ['loup-garou', 'werewolf', 'm'],
  ['ludique', 'playful (adj.)', undefined],
  ['lumières', 'lights', undefined],
  ['luxe', 'luxury', 'm'],
  ['maillot de bain', 'swimming costume', 'm'],
  ['maladresse', 'clumsiness', 'f'],
  ['maman', 'mum', 'f'],
  ['manipuler', 'to manipulate (v.)', undefined],
  ['manque', 'lack (noun)', 'm'],
  ['marché', 'market (noun)', 'm'],
  ['marché du travail', 'labour market', 'm'],
  ['masquer', 'to mask (v.)', undefined],
  ['mécontent', 'unhappy (adj.)', undefined],
  ['médaille', 'medal', 'f'],
  ['méditation', 'meditation', 'f'],
  ['mémoire', 'memory', 'f'],
  ['menace', 'threat', 'f'],
  ['mère', 'mother', 'f'],
  ['métier', 'profession', 'm'],
  ['métiers administratifs', 'administrative jobs', undefined],
  ['mettre en place', 'to put in place', undefined],
  ['micro', 'micro, microphone', 'm'],
  ['minceur', 'thinness', 'f'],
  ['minéraux', 'minerals', undefined],
  ['mobile-home', 'mobile home', 'm'],
  ['modèle', 'model (noun)', 'm'],
  ['modifier', 'to modify (v.)', undefined],
  ['moment de paix', 'a quiet moment', 'm'],
  ['montre', 'watch, wristwatch', 'f'],

  // Page 185
  ['montrer que', 'to show that', undefined],
  ['mort', 'death', 'f'],
  ['mosquée', 'mosque', 'f'],
  ['mot', 'word (noun)', 'm'],
  ['munitions', 'arms, munitions', undefined],
  ['musulman', 'Muslim', 'm'],
  ['mystérieux', 'mysterious (adj.)', undefined],
  ['nager', 'to swim (v.)', undefined],
  ['naissance', 'birth (noun)', 'f'],
  ['naturalisation', 'naturalisation', 'f'],
  ['ne pas sentir (qqch / qqn)', 'not to be able to stand something / somebody', undefined],
  ['néo-solidarité', 'neo-solidarity', 'f'],
  ['neurones', 'neurons', undefined],
  ['niveau', 'level (noun)', 'm'],
  ['nord', 'north', 'm'],
  ['nord-est', 'north-east', 'm'],
  ['nord-ouest', 'north-west', 'm'],
  ['normalité', 'normality', 'f'],
  ['notification', 'notification', 'f'],
  ['numérique', 'digital (adj.)', undefined],
  ['objet culte', 'cult object', 'm'],
  ['objets connectés', 'connected objects', undefined],
  ['objets du quotidien', 'everyday objects', undefined],
  ['objets improbables', 'unlikely objects', undefined],
  ['objets nouveaux', 'new objects', undefined],
  ['objets réinventés', 're-invented objects', undefined],
  ['obtenir un travail', 'to get a job', undefined],
  ['odeur', 'smell (noun)', 'f'],
  ['œuvre', 'work (noun)', 'f'],
  ['ondes', 'waves', undefined],
  ['opportunités', 'opportunities', undefined],
  ['organes', 'organs', undefined],
  ['orthographe', 'spelling', 'f'],
  ['orthographique', 'orthographical (adj.)', undefined],
  ['ouest', 'west', 'm'],
  ['palmarès', 'honours', 'm'],
  ['papa', 'dad', 'm'],
  ['paparazzi', 'paparazzi', 'm'],
  ['paramétrer', 'to configure (v.)', undefined],
  ['paraskevidékatriaphobe', 'phobia of Friday the thirteenth', 'm'],
  ['parcourir', 'to cover (a distance) (v.)', undefined],
  ['parcourir (une distance)', 'to cover (a distance) (v.)', undefined],
  ['parent solo', 'single parent', 'm/f'],
  ['paresse', 'laziness', 'f'],

  // Page 186
  ['paresseux', 'lazy', undefined],
  ['pari', 'bet (noun)', 'm'],
  ['parier', 'to bet (v.)', undefined],
  ['parler d\'un fait', 'to talk about a fact', undefined],
  ['paroles', 'words', undefined],
  ['particuliers', 'particulars', undefined],
  ['partir à l\'aventure', 'to go off on an adventure', undefined],
  ['pas', 'steps', undefined],
  ['passionnant', 'exciting (adj.)', undefined],
  ['pasteurs', 'shepherd', undefined],
  ['pays', 'country', 'm'],
  ['pays natal', 'country of birth', 'm'],
  ['paysage', 'countryside', 'm'],
  ['peau', 'skin', 'f'],
  ['percevoir', 'to perceive (v.)', undefined],
  ['père', 'father', 'm'],
  ['période de crise', 'period of crisis', 'f'],
  ['permettre de', 'to allow (v.)', undefined],
  ['personnel', 'staff (employees)', 'm'],
  ['perspective d\'emploi', 'job prospects', 'f'],
  ['perte de poids', 'weight loss', 'f'],
  ['pèse-personne', 'scales (to weigh people)', 'm'],
  ['petit papa', 'dear Daddy (my)', 'm'],
  ['petite maman', 'dear Mummy (my)', 'f'],
  ['peuple', 'people (noun)', 'm'],
  ['peuple français', 'the French', 'm'],
  ['pharmaceutique', 'pharmaceutical (adj.)', undefined],
  ['phénomène', 'phenomenon', 'm'],
  ['photographie en noir et blanc / en couleurs', 'black and white / colour photograph', 'f'],
  ['pièces de la maison', 'rooms in the house', undefined],
  ['piloter', 'to guide, to manage (v.)', undefined],
  ['plage du débarquement', 'landing beach', 'f'],
  ['plan d\'ensemble', 'overall plan', 'm'],
  ['plébiscité', 'supported by a large majority', undefined],
  ['pluridisciplinaire', 'multidisciplinary (adj.)', undefined],
  ['porte-bonheur', 'lucky charm', 'm'],
  ['porte-malheur', 'unlucky charm', 'm'],
  ['portrait', 'portrait', 'm'],
  ['pot', 'pot (noun)', 'm'],
  ['pouls', 'pulse (noun)', 'm'],
  ['prairie', 'meadow', 'f'],
  ['prendre (qqch) au sérieux', 'to take something seriously', undefined],
  ['prendre des décisions', 'to make decisions', undefined],
  ['prendre en main', 'to take in hand', undefined],
  ['presse', 'press (noun)', 'f'],

  // Page 187
  ['pression artérielle', 'blood pressure', 'f'],
  ['prestataires', '(service) providers', undefined],
  ['prêter', 'to lend (v.)', undefined],
  ['prier', 'to pray (v.)', undefined],
  ['prière', 'prayer', 'f'],
  ['prise de la Bastille', 'storming of the Bastille', 'f'],
  ['prison', 'prison', 'f'],
  ['produits cosmétiques', 'cosmetic products', undefined],
  ['profession', 'profession', 'f'],
  ['profil d\'utilisateur', 'user profile', 'm'],
  ['programmer', 'to program (v.)', undefined],
  ['progrès', 'progress (noun)', 'm'],
  ['progresser', 'to progress (v.)', undefined],
  ['projet d\'aide au développement', 'development aid project', 'm'],
  ['promouvoir', 'to promote, to encourage (v.)', undefined],
  ['propre', 'clean (adj.)', undefined],
  ['propreté', 'cleanliness', 'f'],
  ['propriété médicale', 'medical property', 'f'],
  ['protestant', 'Protestant', 'm'],
  ['proximité', 'proximity', 'f'],
  ['public', 'public (noun)', 'm'],
  ['puissance', 'power (noun)', 'f'],
  ['qualité', 'quality', 'f'],
  ['quitter (qqn)', 'to leave (somebody) (v.)', undefined],
  ['rajeunir', 'to rejuvenate (v.)', undefined],
  ['ramasser', 'to pick up (v.)', undefined],
  ['ramener (les genoux)', 'to bring back (knees) (v.)', undefined],
  ['ramollo', 'soft, misshapen (adj.)', undefined],
  ['rang', 'row (noun)', 'm'],
  ['raplapla', 'pooped (exhausted) (adj.)', undefined],
  ['rapporter', 'to report (v.)', undefined],
  ['rapports', 'relations', undefined],
  ['raquette de tennis', 'tennis racket', 'f'],
  ['rayons ultraviolets (UV)', 'ultraviolet rays', undefined],
  ['recevoir un prix', 'to receive a prize', undefined],
  ['réconciliation', 'reconciliation', 'f'],
  ['recueillir', 'to collect (v.)', undefined],
  ['rédacteur en chef', 'editor in chief', 'm'],
  ['refaire sa vie', 'to change one\'s life', undefined],
  ['référence religieuse', 'religious reference', 'f'],
  ['réfléchir', 'to reflect (v.)', undefined],
  ['réfrigérateur', 'refrigerator', 'm'],
  ['région', 'region', 'f'],
  ['règle', 'rule (noun)', 'f'],

  // Page 188
  ['règle numéro 1 / 2 / ...', 'rule number 1 / 2 / etc.', 'f'],
  ['regret', 'regret (noun)', 'm'],
  ['rein', 'kidney', 'm'],
  ['rémunérer', 'to remunerate (v.)', undefined],
  ['rencontre', 'meeting', 'f'],
  ['rendre', 'to give back (v.)', undefined],
  ['renverser', 'to tip over (v.)', undefined],
  ['reporter', 'reporter', 'm'],
  ['représenter', 'to represent (v.)', undefined],
  ['réputation', 'reputation', 'f'],
  ['respecter une loi', 'to respect a law', undefined],
  ['responsable', 'responsible (adj.)', undefined],
  ['retraite', 'retirement', 'f'],
  ['retrousser', 'to roll up (v.)', undefined],
  ['révéler que', 'to reveal that', undefined],
  ['revenu', 'income', 'm'],
  ['révolution', 'revolution', 'f'],
  ['rivière', 'river', 'f'],
  ['robotique', 'robotics', 'f'],
  ['romantique', 'romantic (adj.)', undefined],
  ['ronfler', 'to snore (v.)', undefined],
  ['rumeur', 'rumour', 'f'],
  ['rythme', 'rhythm', 'm'],
  ['s\'amuser', 'to enjoy oneself (v.)', undefined],
  ['s\'engager', 'to commit, to take a stand (v.)', undefined],
  ['s\'entendre', 'to get on (with someone) (v.)', undefined],
  ['s\'étendre', 'to stretch out (v.)', undefined],
  ['s\'informer', 'to inquire, to find out (v.)', undefined],
  ['s\'installer', 'to settle (v.)', undefined],
  ['s\'intéresser à', 'to be interested in (v.)', undefined],
  ['s\'occuper de', 'to take care of (v.)', undefined],
  ['sable', 'sand (noun)', 'm'],
  ['sacré', 'holy (adj.)', undefined],
  ['salarié', 'employee', 'm'],
  ['sale', 'dirty (adj.)', undefined],
  ['santé', 'health', 'f'],
  ['savoir', 'to know (v.)', undefined],
  ['scène', 'scene', 'f'],
  ['scepticisme', 'scepticism', 'm'],
  ['sculpter son corps', 'to sculpt one\'s body', undefined],
  ['se baigner', 'to bathe (v.)', undefined],
  ['se concentrer', 'to concentrate (v.)', undefined],
  ['se dévêtir', 'to undress (v.)', undefined],
  ['se disperser', 'to disperse (v.)', undefined],
  ['se marier', 'to marry (v.)', undefined],
  ['se parfumer', 'to put perfume on', undefined],
  ['se positionner', 'to position oneself', undefined],
  ['se sentir soutenu', 'to feel supported', undefined],
  ['se vêtir', 'to get dressed', undefined],

  // Page 189
  ['secret professionnel', 'professional secrecy', 'm'],
  ['secteur', 'sector', 'm'],
  ['séduire', 'to charm, to seduce (v.)', undefined],
  ['semaine', 'week', 'f'],
  ['semi-nomade', 'semi-nomadic (adj.)', undefined],
  ['sentir bon', 'to smell good', undefined],
  ['sentir mauvais', 'to smell bad', undefined],
  ['séparation', 'separation', 'f'],
  ['serein', 'calm (adj.)', undefined],
  ['services', 'services', undefined],
  ['s\'exhiber', 'to show oneself in public (provocatively)', undefined],
  ['silencieux', 'quiet (adj.)', undefined],
  ['s\'imposer', 'to be imperative', undefined],
  ['singularité', 'singularity', 'f'],
  ['situer', 'to locate (v.)', undefined],
  ['slogan', 'slogan', 'm'],
  ['solidaire', 'supportive, showing solidarity', undefined],
  ['sonorité des mots', 'the way words sound', 'f'],
  ['source', 'source', 'f'],
  ['spiritualité', 'spirituality', 'f'],
  ['spirituel', 'spiritual (adj.)', undefined],
  ['spirituel (le)', 'that which is spiritual', 'm'],
  ['spot publicitaire', 'commercial break', 'm'],
  ['station thermale', 'spa', 'f'],
  ['stéréotypes', 'stereotypes', undefined],
  ['stéthoscope', 'stethoscope', 'm'],
  ['stockage', 'storage', 'm'],
  ['studio (de télévision)', '(television) studio', 'm'],
  ['supérieur', 'line manager', 'm'],
  ['superstitieux', 'superstitious (adj.)', undefined],
  ['superstitions', 'superstitions', undefined],
  ['supplémentaire', 'additional (adj.)', undefined],
  ['synagogue', 'synagogue', 'f'],
  ['synchronisé', 'synchronised (adj.)', undefined],
  ['synthétiser', 'to summarise (v.)', undefined],
  ['taille', 'waist', 'f'],
  ['température', 'temperature', 'f'],
  ['temple', 'temple', 'm'],
  ['tendance (adj.)', 'fashionable (adj.)', undefined],
  ['tendance (une)', 'trend (noun)', 'f'],
  ['tendresse', 'tenderness', 'f'],
  ['tenue', 'dress (noun)', 'f'],
  ['terre de légende', 'land of legends', 'f'],
  ['terrible', 'terrible (adj.)', undefined],
  ['tertiaire', 'tertiary sector', 'm'],

  // Page 190
  ['thermalisme', 'spa treatments', 'm'],
  ['thermostat', 'thermostat', 'm'],
  ['tige', 'stem (noun)', 'f'],
  ['tirer', 'to pull (v.)', undefined],
  ['titulaire (de)', 'holder (of) (adj.)', undefined],
  ['toucher', 'to touch (v.)', undefined],
  ['touristes', 'tourists', undefined],
  ['tradition', 'tradition', 'f'],
  ['trahison', 'treachery', 'f'],
  ['tranquillité', 'tranquillity', 'f'],
  ['transports', 'transport (noun)', undefined],
  ['travailler', 'to work (v.)', undefined],
  ['traverser (un pays)', 'to cross (a country) (v.)', undefined],
  ['trembler', 'to tremble (v.)', undefined],
  ['tribune', 'forum', 'f'],
  ['trinquer', 'to clink glasses, to drink to something', undefined],
  ['Tu vois ?', 'Do you see?', undefined],
  ['tuer', 'to kill (v.)', undefined],
  ['une-pièce', 'one-piece swimsuit', 'm'],
  ['utilisateurs', 'users', undefined],
  ['vacances', 'holidays', undefined],
  ['valeur', 'value (noun)', 'f'],
  ['valeurs', 'values', undefined],
  ['valorisé', 'valued (adj.)', undefined],
  ['vampire', 'vampire', 'm'],
  ['vaste', 'vast (adj.)', undefined],
  ['vente', 'sale, selling (noun)', 'f'],
  ['ventre', 'belly', 'm'],
  ['vie', 'life', 'f'],
  ['vie en communauté', 'life in a community', 'f'],
  ['village', 'village', 'm'],
  ['violer un principe', 'to violate a principle', undefined],
  ['virtuel', 'virtual (adj.)', undefined],
  ['visiter', 'to visit (v.)', undefined],
  ['vitalité', 'vitality', 'f'],
  ['vitamine', 'vitamin', 'f'],
  ['vivre', 'to live (v.)', undefined],
  ['vivre au rythme de', 'to live in tune with', undefined],
  ['vivre en colocation / en coloc', 'to live in a house-share', undefined],
  ['voie', 'way', 'f'],
  ['voyager', 'to travel (v.)', undefined],
  ['voyageurs', 'travellers', undefined],
  ['voyagistes', 'tour operators', undefined],
]

export const totem3LexiconCards: VocabCard[] = cardRows.map(([frontFr, backEn, gender], index) => ({
  id: `totem3-lexicon-card-${index + 1}`,
  deckId: 'totem3-lexicon',
  frontFr,
  backEn,
  gender,
  exampleFr: `Je révise : ${frontFr}.`,
  exampleEn: `Review card: ${backEn}.`,
  notes: 'From Totem 3 textbook lexicon.',
  tags: ['totem', 'lexicon'],
  confidence: 0,
  dueAt: today,
  intervalDays: 1,
  source: 'totem',
}))
