import type { VocabCard, VocabDeck } from './types'

const today = new Date().toISOString()

export const totem1LexiconDeck: VocabDeck = {
  id: 'totem1-lexicon',
  title: 'TOTEM1',
  description: '',
  level: 'A1',
  tags: ['totem', 'lexicon'],
  source: 'totem',
  difficulty: 1,
  estimatedMinutes: 30,
}

const cardRows: Array<[string, string, VocabCard['gender'] | undefined]> = [
  // Page 112
  ['l\'addition', 'bill', 'f'],
  ['l\'âge', 'age', 'm'],
  ['âgé', 'elderly', undefined],
  ['agréable', 'pleasant', undefined],
  ['l\'ail', 'garlic', 'm'],
  ['aimer', 'to like / to love', undefined],
  ['ajouter', 'to add', undefined],
  ['allemand', 'German', undefined],
  ['allô', 'hello', undefined],
  ['américain', 'American', undefined],
  ['les amis', 'friends', undefined],
  ['l\'amour', 'love', 'm'],
  ['l\'année', 'year', 'f'],
  ['août', 'August', 'm'],
  ['appeler', 'to call', undefined],
  ['apprendre', 'to learn', undefined],
  ['l\'après-midi', 'afternoon', 'm'],
  ['l\'architecte', 'architect', 'm/f'],
  ['l\'arobase', '@ symbol', 'f'],
  ['au revoir', 'goodbye', undefined],
  ['l\'automne', 'autumn', 'm'],
  ['l\'avenue', 'avenue', 'f'],
  ['l\'avion', 'airplane', 'm'],
  ['avril', 'April', 'm'],
  ['la baignade', 'swimming', 'f'],
  ['la banane', 'banana', 'f'],
  ['le bar', 'bar', 'm'],
  ['le bateau', 'boat', 'm'],
  ['beau (belle)', 'handsome / beautiful', undefined],
  ['beaucoup', 'many', undefined],
  ['belge', 'Belgian', undefined],
  ['le besoin', 'need', 'm'],
  ['bête', 'silly', undefined],
  ['blanc (blanche)', 'white', undefined],
  ['blond(e)', 'blonde', undefined],
  ['boire', 'to drink', undefined],
  ['la boisson', 'drink', 'f'],
  ['bonjour', 'hello', undefined],
  ['bonsoir', 'good evening', undefined],
  ['la boucherie', 'butcher shop', 'f'],
  ['la boulangerie', 'bakery', 'f'],
  ['la bouteille', 'bottle', 'f'],
  ['le bras', 'arm', 'm'],
  ['brésilien(ne)', 'Brazilian', undefined],
  ['bronzer', 'to tan', undefined],
  ['brun(e)', 'brown-haired', undefined],
  ['le café', 'cafe', 'm'],

  // Page 113
  ['la campagne', 'countryside', 'f'],
  ['le camping', 'campsite', 'm'],
  ['la carafe', 'carafe', 'f'],
  ['la carotte', 'carrot', 'f'],
  ['la carte', 'menu', 'f'],
  ['célibataire', 'single', undefined],
  ['châtain', 'light brown-haired', undefined],
  ['la chaussure', 'shoe', 'f'],
  ['la chemise', 'shirt', 'f'],
  ['le chèque', 'cheque', 'm'],
  ['les cheveux', 'hair', 'm'],
  ['le chocolat', 'chocolate', 'm'],
  ['la chronologie', 'chronology', 'f'],
  ['le cinéma', 'cinema', 'm'],
  ['le client', 'customer', 'm'],
  ['la cocotte', 'casserole dish', 'f'],
  ['la comédie', 'comedy', 'f'],
  ['commander', 'to order', undefined],
  ['le commentaire', 'comment', 'm'],
  ['compléter', 'to complete', undefined],
  ['comprendre', 'to understand', undefined],
  ['le conseil', 'piece of advice', 'm'],
  ['le contact', 'contact', 'm'],
  ['contacter', 'to contact', undefined],
  ['les coordonnées', 'contact information', 'f'],
  ['le corps', 'body', 'm'],
  ['coucou', 'hi there', undefined],
  ['couper', 'to cut', undefined],
  ['courageux(euse)', 'brave', undefined],
  ['la courgette', 'courgette', 'f'],
  ['le courriel', 'email', 'm'],
  ['le cours', 'class', 'm'],
  ['les courses', 'food shopping', 'f'],
  ['la cravate', 'tie', 'f'],
  ['la cuillère', 'spoon', 'f'],
  ['cuire', 'to cook', undefined],
  ['la cuisine', 'cooking', 'f'],
  ['la cuisson', 'cooking technique', 'f'],
  ['d\'abord', 'first', undefined],
  ['la date', 'date', 'f'],
  ['décembre', 'December', 'm'],
  ['découvrir', 'to discover', undefined],
  ['décrire', 'to describe', undefined],
  ['le déjeuner', 'lunch', 'm'],
  ['désagréable', 'unpleasant', undefined],

  // Page 114
  ['la description', 'description', 'f'],
  ['le dessert', 'dessert', 'm'],
  ['devoir', 'to have to', undefined],
  ['le dictionnaire', 'dictionary', 'm'],
  ['dimanche', 'Sunday', 'm'],
  ['le dîner', 'dinner', 'm'],
  ['la discipline', 'subject', 'f'],
  ['le drame', 'drama', 'm'],
  ['la durée', 'length', 'f'],
  ['l\'eau', 'water', 'f'],
  ['écouter', 'to listen', undefined],
  ['écrire', 'to write', undefined],
  ['élégant(e)', 'elegant', undefined],
  ['enchanté(e)', 'nice to meet you', undefined],
  ['les enfants', 'children', 'm'],
  ['enfin', 'finally', undefined],
  ['ennuyeux(euse)', 'boring', undefined],
  ['l\'entrée', 'starter', 'f'],
  ['envoyer', 'to send', undefined],
  ['éplucher', 'to peel', undefined],
  ['l\'escargot', 'snail', 'm'],
  ['espagnol(e)', 'Spanish', undefined],
  ['essayer', 'to try', undefined],
  ['l\'été', 'summer', 'm'],
  ['les études', 'studies', 'f'],
  ['l\'étudiant(e)', 'student', 'm/f'],
  ['l\'événement', 'event', 'm'],
  ['l\'examen', 'exam', 'm'],
  ['la faculté', 'university', 'f'],
  ['la famille', 'family', 'f'],
  ['la femme', 'wife', 'f'],
  ['les fesses', 'buttocks', 'f'],
  ['la fête', 'party', 'f'],
  ['février', 'February', 'm'],
  ['la fille', 'daughter', 'f'],
  ['le film', 'film', 'm'],
  ['le fils', 'son', 'm'],
  ['le fixe', 'landline', 'm'],
  ['le fleuve', 'river', 'm'],
  ['le formulaire', 'form', 'm'],
  ['le four', 'oven', 'm'],
  ['la fraise', 'strawberry', 'f'],
  ['français(e)', 'French', undefined],
  ['la fréquence', 'frequency', 'f'],
  ['le frère', 'brother', 'm'],
  ['la frite', 'chip', 'f'],
  ['le fromager', 'cheesemonger', 'm'],

  // Page 115
  ['le gîte', 'bed / lodging', 'm'],
  ['la gousse', 'clove', 'f'],
  ['le goût', 'taste', 'm'],
  ['le gramme', 'gram', 'm'],
  ['grand(e)', 'tall', undefined],
  ['gris(e)', 'gray', undefined],
  ['le haricot vert', 'string bean', 'm'],
  ['l\'hébergement', 'accommodation', 'm'],
  ['l\'herbe', 'herb', 'f'],
  ['heureux(euse)', 'happy', undefined],
  ['l\'histoire', 'story', 'f'],
  ['l\'hiver', 'winter', 'm'],
  ['l\'hôpital', 'hospital', 'm'],
  ['l\'hôtel', 'hotel', 'm'],
  ['l\'identité', 'identity', 'f'],
  ['il faut', 'You must', undefined],
  ['l\'ingénieur(e)', 'engineer', 'm/f'],
  ['l\'ingrédient', 'ingredient', 'm'],
  ['l\'inscription', 'enrolment', 'f'],
  ['l\'instruction', 'instructions', 'f'],
  ['intelligent(e)', 'intelligent', undefined],
  ['l\'intensité', 'intensity', 'f'],
  ['italien(ne)', 'Italian', undefined],
  ['la jambe', 'leg', 'f'],
  ['janvier', 'January', 'm'],
  ['japonais(e)', 'Japanese', undefined],
  ['le jardin', 'garden', 'm'],
  ['le jean', 'jeans', 'm'],
  ['jeudi', 'Thursday', 'm'],
  ['jeune', 'young', undefined],
  ['le/la journaliste', 'journalist', 'm/f'],
  ['joyeux(euse)', 'joyful', undefined],
  ['juillet', 'July', 'm'],
  ['juin', 'June', 'm'],
  ['le jus de fruit', 'fruit juice', 'm'],
  ['le kilo', 'kilo', 'm'],
  ['laid(e)', 'ugly', undefined],
  ['le lait', 'milk', 'm'],
  ['la langue', 'language', 'f'],
  ['la Licence', 'Bachelor\'s degree', 'f'],
  ['le liquide', 'cash', 'm'],
  ['la location', 'rental', 'f'],
  ['le loisir', 'leisure activity', 'm'],
  ['lundi', 'Monday', 'm'],

  // Page 116
  ['le lycée', 'secondary school', 'm'],
  ['le magasin', 'shop', 'm'],
  ['mai', 'May', 'm'],
  ['le mail', 'email', 'm'],
  ['la main', 'hand', 'f'],
  ['la marche', 'walking', 'f'],
  ['le marché', 'market', 'm'],
  ['marcher', 'to walk', undefined],
  ['mardi', 'Tuesday', 'm'],
  ['le mari', 'husband', 'm'],
  ['marié(e) (avec)', 'married (to)', undefined],
  ['mars', 'March', 'm'],
  ['le Master', 'Master\'s degree', 'm'],
  ['la matière', 'subject', 'f'],
  ['le matin', 'morning', 'm'],
  ['le/la médecin', 'doctor', 'm/f'],
  ['le menu', 'set menu', 'm'],
  ['la mer', 'sea', 'f'],
  ['merci', 'thank you', undefined],
  ['mercredi', 'Wednesday', 'm'],
  ['la mère', 'mother', 'f'],
  ['la météo', 'weather forecast', 'f'],
  ['mexicain(e)', 'Mexican', undefined],
  ['mince', 'thin', undefined],
  ['modeste', 'modest', undefined],
  ['le mois', 'month', 'm'],
  ['la montagne', 'mountain', 'f'],
  ['le morceau', 'piece', 'm'],
  ['le moule', 'pan', 'm'],
  ['la mousse', 'mousse', 'f'],
  ['le moyen de transport', 'means of transport', 'm'],
  ['la moyenne', 'average', 'f'],
  ['le musée', 'museum', 'm'],
  ['la musique', 'music', 'f'],
  ['la nationalité', 'nationality', 'f'],
  ['négatif(ve)', 'negative', undefined],
  ['le niveau', 'level', 'm'],
  ['le nom', 'name', 'm'],
  ['noter', 'to note', undefined],
  ['novembre', 'November', 'm'],
  ['la nuit', 'night', 'f'],
  ['le numéro', 'number', 'm'],
  ['octobre', 'October', 'm'],
  ['l\'œil [les yeux]', 'eye [eyes]', 'm'],
  ['l\'œuf', 'egg', 'm'],
  ['l\'oignon', 'onion', 'm'],

  // Page 117
  ['l\'orange', 'orange', 'f'],
  ['le pain', 'bread', 'm'],
  ['le pantalon', 'trousers', 'm'],
  ['passer un examen', 'to take an exam', undefined],
  ['la pâtisserie', 'Pastry shop', 'f'],
  ['payer', 'to pay', undefined],
  ['le père', 'father', 'm'],
  ['petit(e)', 'small', undefined],
  ['la pharmacie', 'pharmacy', 'f'],
  ['philippin(e)', 'Filipino (Filipina)', undefined],
  ['le/la photographe', 'photographer', 'm/f'],
  ['le pied', 'foot', 'm'],
  ['pique-niquer', 'to have a picnic', undefined],
  ['la place', 'square', 'f'],
  ['le plat', 'dish', 'm'],
  ['pleuvoir', 'to rain', undefined],
  ['la poêle', 'pan', 'f'],
  ['le point', 'full stop', 'm'],
  ['le point d\'exclamation', 'exclamation mark', 'm'],
  ['le point d\'interrogation', 'question mark', 'm'],
  ['le poireau', 'leek', 'm'],
  ['le poisson', 'fish', 'm'],
  ['la poissonnerie', 'fishmonger\'s', 'f'],
  ['la poitrine', 'chest', 'f'],
  ['la politesse', 'manners', 'f'],
  ['polonais(e)', 'Polish', undefined],
  ['la pomme', 'apple', 'f'],
  ['la pomme de terre', 'potato', 'f'],
  ['la ponctuation', 'punctuation', 'f'],
  ['le pont', 'bridge', 'm'],
  ['le portable', 'mobile phone', 'm'],
  ['porter', 'to wear', undefined],
  ['positif(ve)', 'positive', undefined],
  ['la Poste', 'Post office', 'f'],
  ['le potiron', 'pumpkin', 'm'],
  ['le poulet', 'chicken', 'm'],
  ['préférer', 'to prefer', undefined],
  ['le prénom', 'first name', 'm'],
  ['le primeur', 'greengrocer', 'm'],
  ['le printemps', 'spring', 'm'],
  ['le/la professeur(e)', 'teacher / professor', 'm/f'],
  ['la profession', 'profession', 'f'],

  // Page 118
  ['la promenade', 'walk', 'f'],
  ['puis', 'then', undefined],
  ['le quai', 'embankment', 'm'],
  ['la quantité', 'quantity', 'f'],
  ['le raisin', 'grape', 'm'],
  ['rater', 'to fail', undefined],
  ['regarder', 'to watch / to look', undefined],
  ['la relation', 'relative', 'f'],
  ['le relevé de notes', 'transcript of results', 'm'],
  ['remplir', 'to fill up', undefined],
  ['le rendez-vous', 'meeting', 'm'],
  ['le restaurant', 'restaurant', 'm'],
  ['la restauration', 'restaurant industry', 'f'],
  ['retrouver', 'to meet', undefined],
  ['réussir', 'to succeed', undefined],
  ['réviser', 'to revise', undefined],
  ['la rive', 'bank', 'f'],
  ['la robe', 'dress', 'f'],
  ['rond(e)', 'round', undefined],
  ['la rue', 'street', 'f'],
  ['s\'il vous plaît', 'please', undefined],
  ['s\'aimer', 'to love each other', undefined],
  ['la salade', 'salad', 'f'],
  ['salut', 'hey', undefined],
  ['samedi', 'Saturday', 'm'],
  ['s\'appeler', 'to call one another', undefined],
  ['le saumon', 'salmon', 'm'],
  ['se baigner', 'to swim', undefined],
  ['se coucher', 'to go to bed', undefined],
  ['se lever', 'to get up', undefined],
  ['se marier', 'to get married', undefined],
  ['se présenter', 'to introduce yourself', undefined],
  ['se promener', 'to take a walk', undefined],
  ['se quitter', 'to part ways', undefined],
  ['se rencontrer', 'to meet', undefined],
  ['se retrouver', 'to meet up', undefined],
  ['la séance', 'showing', 'f'],
  ['le/la secrétaire', 'secretary', 'm/f'],
  ['le semestre', 'semester', 'm'],
  ['septembre', 'September', 'm'],
  ['sérieux(euse)', 'serious', undefined],
  ['le/la serveur(euse)', 'waiter / waitress', 'm/f'],
  ['servir', 'to serve', undefined],

  // Page 119
  ['la signature', 'signature', 'f'],
  ['signer', 'to sign', undefined],
  ['s\'inscrire', 'to enrol', undefined],
  ['la sœur', 'sister', 'f'],
  ['le soir', 'evening', 'm'],
  ['la sortie', 'exit', 'f'],
  ['le souvenir', 'memory', 'm'],
  ['le steak', 'steak', 'm'],
  ['stupide', 'stupid', undefined],
  ['suisse', 'Swiss', undefined],
  ['suivre', 'to take', undefined],
  ['la surprise', 'surprise', 'f'],
  ['sympa(thique)', 'nice', undefined],
  ['la taille', 'size', 'f'],
  ['la tarte', 'tart', 'f'],
  ['le téléphone', 'telephone', 'm'],
  ['téléphoner', 'to call', undefined],
  ['le temps', 'weather', 'm'],
  ['la tête', 'head', 'f'],
  ['le théâtre', 'theatre', 'm'],
  ['la tomate', 'tomato', 'f'],
  ['le train', 'train', 'm'],
  ['travailler', 'to work', undefined],
  ['très', 'very', undefined],
  ['triste', 'sad', undefined],
  ['trop', 'too much', undefined],
  ['un peu', 'a little', undefined],
  ['l\'ustensile', 'utensil', 'm'],
  ['le vélo', 'bike', 'm'],
  ['le/la vendeur(euse)', 'salesperson', 'm/f'],
  ['vendredi', 'Friday', 'm'],
  ['le ventre', 'stomach', 'm'],
  ['le verre', 'glass', 'm'],
  ['verser', 'to pour', undefined],
  ['la veste', 'jacket', 'f'],
  ['le vêtement', 'piece of clothing', 'm'],
  ['la viande', 'meat', 'f'],
  ['la ville', 'city', 'f'],
  ['le vin', 'wine', 'm'],
  ['la virgule', 'comma', 'f'],
  ['visiter', 'to visit', undefined],
  ['voir', 'to see', undefined],
  ['la voiture', 'car', 'f'],
]

export const totem1LexiconCards: VocabCard[] = cardRows.map(([frontFr, backEn, gender], index) => ({
  id: `totem1-lexicon-card-${index + 1}`,
  deckId: 'totem1-lexicon',
  frontFr,
  backEn,
  gender,
  exampleFr: `Je révise : ${frontFr}.`,
  exampleEn: `Review card: ${backEn}.`,
  notes: 'From Totem 1 textbook lexicon.',
  tags: ['totem', 'lexicon'],
  confidence: 0,
  dueAt: today,
  intervalDays: 1,
  source: 'totem',
}))
