import type { VocabCard, VocabDeck } from './types'

const today = new Date().toISOString()

export const totem2LexiconDeck: VocabDeck = {
  id: 'totem2-lexicon',
  title: 'TOTEM2',
  description: '',
  level: 'A2',
  tags: ['totem', 'lexicon'],
  source: 'totem',
  difficulty: 2,
  estimatedMinutes: 30,
}

const cardRows: Array<[string, string, VocabCard['gender'] | undefined]> = [
  // Page 136
  ['à pied', 'on foot', undefined],
  ['à temps partiel', 'part-time', undefined],
  ['absolument', 'absolutely', undefined],
  ['l\'accès', 'entrance', 'm'],
  ['les accessoires', 'accessories', 'm'],
  ['l\'acquiescement', 'acquiescence', 'm'],
  ['les activités domestiques', 'household chores', 'f'],
  ['actuel(le)', 'current', undefined],
  ['agréable', 'pleasant', undefined],
  ['l\'aïkido', 'aikido', 'm'],
  ['l\'alcool', 'alcohol', 'm'],
  ['alerter', 'to alert', undefined],
  ['l\'aménagement', 'layout', 'm'],
  ['aménager', 'to lay out', undefined],
  ['amusant(e)', 'amusing', undefined],
  ['les animaux', 'animals', 'm'],
  ['les animaux domestiques', 'pets', 'm'],
  ['les animaux sauvages', 'wild animals', 'm'],
  ['l\'année prochaine', 'next year', 'f'],
  ['annoncer (une nouvelle)', 'to announce (a piece of news)', undefined],
  ['l\'appareil', 'appliance', 'm'],
  ['l\'appareil photo', 'camera', 'm'],
  ['l\'appartement', 'flat', 'm'],
  ['l\'application', 'application', 'f'],
  ['l\'arbre', 'tree', 'm'],
  ['l\'architecture', 'architecture', 'f'],
  ['l\'argent', 'money', 'm'],
  ['arriver en retard', 'to arrive late', undefined],
  ['l\'art', 'art', 'm'],
  ['l\'artiste', 'artist', 'm/f'],
  ['artistique', 'artistic', undefined],
  ['l\'ascenseur', 'lift', 'm'],
  ['l\'aspirateur', 'vacuum cleaner', 'm'],
  ['assez', 'enough', undefined],
  ['l\'assiette', 'plate', 'f'],
  ['l\'association', 'association', 'f'],
  ['l\'atelier', 'workshop', 'm'],
  ['l\'attitude', 'attitude', 'f'],
  ['l\'avenue', 'avenue', 'f'],
  ['avoir l\'air', 'to seem', undefined],
  ['avoir mal à', 'to have a sore...', undefined],
  ['la baignoire', 'bathtub', 'f'],
  ['le balcon', 'balcony', 'm'],
  ['basique', 'basic', undefined],
  ['bénéficier de', 'to benefit from', undefined],
  ['le bénévolat', 'volunteering', 'm'],
  ['le/la berger(ère)', 'shepherd(ess)', 'm/f'],
  ['le bien-être', 'well-being', 'm'],
  ['la biodiversité', 'biodiversity', 'f'],
  ['le bloc', 'block', 'm'],
  ['le boulevard', 'boulevard', 'm'],
  ['le boulot', 'job', 'm'],
  ['le bouquetin', 'mountain goat', 'm'],

  // Page 137
  ['la brebis', 'ewe', 'f'],
  ['la brioche', 'brioche', 'f'],
  ['le bruit', 'noise', 'm'],
  ['le bureau', 'desk', 'm'],
  ['le cabinet d\'avocats', 'a law firm', 'm'],
  ['le cadre de vie', 'living environment', 'm'],
  ['calme', 'calm', undefined],
  ['la campagne', 'countryside', 'f'],
  ['le canapé', 'sofa', 'm'],
  ['le canapé-lit', 'sofa bed', 'm'],
  ['le/la candidat(e)', 'job applicant', 'm/f'],
  ['carré(e)', 'square', undefined],
  ['la carrière', 'career', 'f'],
  ['la case', 'box', 'f'],
  ['le CDD', 'fixed-term contract', 'm'],
  ['le CDI', 'open-ended contract', 'm'],
  ['le centre-ville', 'town centre', 'm'],
  ['le cerf', 'deer', 'm'],
  ['la certitude', 'certainty', 'f'],
  ['la chaise', 'chair', 'f'],
  ['la chaise longue', 'chaise-longue', 'f'],
  ['la chambre', 'room', 'f'],
  ['le chamois', 'chamois', 'm'],
  ['le changement', 'change', 'm'],
  ['changer', 'to change', undefined],
  ['le chantier', 'worksite', 'm'],
  ['le chat', 'cat', 'm'],
  ['la cheminée', 'fireplace', 'f'],
  ['chercher (un emploi)', 'to look for (a job)', undefined],
  ['le chien', 'dog', 'm'],
  ['le choix', 'choice', 'm'],
  ['le chômage', 'unemployment', 'm'],
  ['le/la chômeur(euse)', 'unemployed person', 'm/f'],
  ['la chronologie', 'chronology', 'f'],
  ['citoyen(ne)', 'civic', undefined],
  ['le/la citoyen(ne)', 'citizen', 'm/f'],
  ['clair(e)', 'clear', undefined],
  ['le climat', 'climate', 'm'],
  ['la climatisation', 'air conditioning', 'f'],
  ['cliquer sur', 'to click on', undefined],
  ['la coiffure', 'hairstyle', 'f'],
  ['le/la colocataire', 'flatmate', 'm/f'],
  ['combattre', 'to fight', undefined],
  ['le commentaire', 'comment', 'm'],
  ['le commerce', 'shop', 'm'],
  ['la compétence', 'skill', 'f'],
  ['compléter', 'to complete', undefined],
  ['compliqué(e)', 'complicated', undefined],
  ['le comportement', 'behaviour', 'm'],
  ['le confort', 'comfort', 'm'],
  ['le congélateur', 'freezer', 'm'],
  ['la connexion', 'connection', 'f'],

  // Page 138
  ['le conseil', 'piece of advice', 'm'],
  ['la consommation d\'énergie', 'energy consumption', 'f'],
  ['contemporain(e)', 'contemporary', undefined],
  ['content(e)', 'happy', undefined],
  ['continuer', 'to continue', undefined],
  ['correctement', 'correctly', undefined],
  ['couramment', 'fluently', undefined],
  ['les couverts', 'cutlery', 'm'],
  ['la création', 'creation', 'f'],
  ['créer', 'to create', undefined],
  ['la crise', 'crisis', 'f'],
  ['croire', 'to believe', undefined],
  ['croiser (les bras / les jambes)', 'to cross (one\'s arms/legs)', undefined],
  ['la cuisine', 'kitchen', 'f'],
  ['la cuisine équipée', 'fully-equipped kitchen', 'f'],
  ['la cuisine indépendante', 'separate kitchen', 'f'],
  ['la cuisinière', 'stove', 'f'],
  ['le CV', 'CV', 'm'],
  ['de bonne humeur', 'in a good mood', undefined],
  ['de mauvaise humeur', 'in a bad mood', undefined],
  ['décider de', 'to decide to', undefined],
  ['la décoration', 'decor', 'f'],
  ['la découverte', 'discovery', 'f'],
  ['découvrir', 'to discover', undefined],
  ['décrocher (un job)', 'to get (a job)', undefined],
  ['dehors', 'outside', undefined],
  ['délirant(e)', 'crazy', undefined],
  ['demander', 'to ask', undefined],
  ['le/la demandeur(euse) d\'emploi', 'jobseeker', 'm/f'],
  ['le départ', 'departure', 'm'],
  ['la description', 'description', 'f'],
  ['design', 'stylish', undefined],
  ['désigner', 'to design', undefined],
  ['le désordre', 'mess', 'm'],
  ['devenir fou (folle)', 'to go mad', undefined],
  ['devoir', 'to have to', undefined],
  ['le dialogue social', 'labour negotiations', 'm'],
  ['la digue', 'dyke', 'f'],
  ['diminuer', 'to diminish', undefined],
  ['discipliné(e)', 'disciplined', undefined],
  ['le discours', 'message', 'm'],
  ['discuter', 'to discuss', undefined],
  ['donner', 'to give', undefined],
  ['donner son avis', 'to give one\'s opinion', undefined],
  ['doucement', 'gently', undefined],
  ['la douche', 'shower', 'f'],
  ['le droit', 'right', 'm'],

  // Page 139
  ['le droit du travail', 'labour law', 'm'],
  ['les droits de l\'homme', 'human rights', 'm'],
  ['le écart de salaire', 'salary difference', 'm'],
  ['l\'écologie', 'ecology', 'f'],
  ['économiser l\'énergie', 'to save energy', undefined],
  ['l\'écosystème', 'ecosystem', 'm'],
  ['l\'écran tactile', 'touch screen', 'm'],
  ['l\'écrit', 'writing', 'm'],
  ['le/la écrivain(e)', 'writer', 'm/f'],
  ['l\'éducation', 'education', 'f'],
  ['égal(e)', 'equal', undefined],
  ['l\'égalité', 'equality', 'f'],
  ['électrique', 'electric', undefined],
  ['l\'électroménager', 'electrical appliances', 'm'],
  ['électronique', 'electronic', undefined],
  ['l\'éléphant', 'elephant', 'm'],
  ['l\'éleveur', 'livestock farmer', 'm'],
  ['l\'emploi', 'employment', 'm'],
  ['l\'emploi précaire', 'precarious work', 'm'],
  ['en métal', 'made of metal', undefined],
  ['en plastique', 'made of plastic', undefined],
  ['en profiter', 'to take advantage of', undefined],
  ['en verre', 'made of glass', undefined],
  ['l\'endroit', 'place', 'm'],
  ['l\'énergie', 'energy', 'f'],
  ['les énergies fossiles', 'fossil fuels', 'f'],
  ['les énergies renouvelables', 'renewable energies', 'f'],
  ['l\'engagement', 'commitment', 'm'],
  ['enregistrer', 'to save', undefined],
  ['la entreprise', 'company', 'f'],
  ['le entretien d\'embauche', 'job interview', 'm'],
  ['l\'environnement', 'environment', 'm'],
  ['l\'équipement', 'fitting', 'm'],
  ['l\'équitation', 'horse riding', 'f'],
  ['les escaliers', 'stairs', 'm'],
  ['l\'espace', 'space', 'm'],
  ['l\'est', 'East', 'm'],
  ['l\'étage', 'floor', 'm'],
  ['l\'étagère', 'shelf', 'f'],
  ['étonnant(e)', 'astonishing', undefined],
  ['être à l\'aise', 'to be at ease', undefined],
  ['être à l\'écoute', 'to be listening', undefined],
  ['être certain(e) que', 'to be certain that', undefined],
  ['être constitué(e) de', 'to be made up of', undefined],
  ['être équipé(e) de', 'to be equipped with', undefined],
  ['être / ne pas être bien', 'to be/not be in good form', undefined],
  ['être / ne pas être en forme', 'to be/not be in good shape', undefined],
  ['être responsable', 'to be responsible', undefined],

  // Page 140
  ['être sûr(e) que', 'to be sure that', undefined],
  ['les êtres humains', 'human beings', 'm'],
  ['l\'événement', 'event', 'm'],
  ['éviter', 'to avoid', undefined],
  ['évoluer', 'to evolve', undefined],
  ['évolutif(tive)', 'progressive / scalable', undefined],
  ['la évolution', 'change', 'f'],
  ['évoquer', 'to evoke', undefined],
  ['excusez-moi', 'excuse me', undefined],
  ['exiger', 'to demand', undefined],
  ['exposer', 'to exhibit', undefined],
  ['la exposition', 'exhibition', 'f'],
  ['la expulsion', 'expulsion', 'f'],
  ['extraordinaire', 'extraordinaire', undefined],
  ['faire des efforts', 'to make an effort', undefined],
  ['faire le ménage', 'to do the cleaning', undefined],
  ['faire un régime', 'to diet', undefined],
  ['faire une recherche', 'to search', undefined],
  ['falloir', 'to have to', undefined],
  ['fantastique', 'fantastic', undefined],
  ['la fatalité', 'destiny', 'f'],
  ['la faune', 'fauna', 'f'],
  ['le fauteuil', 'armchair', 'm'],
  ['le fitness', 'fitness', 'm'],
  ['la fleur', 'flower', 'f'],
  ['la flore', 'flora', 'f'],
  ['la folie', 'madness', 'f'],
  ['la fonction', 'function', 'f'],
  ['la fonctionnalité', 'functionality', 'f'],
  ['le foot', 'football', 'm'],
  ['les formes', 'shapes', 'f'],
  ['fou (folle)', 'mad', undefined],
  ['le four', 'oven', 'm'],
  ['la fraternité', 'brotherhood', 'f'],
  ['la fréquence', 'frequency', 'f'],
  ['le fric', 'cash', 'm'],
  ['le frigo', 'fridge', 'm'],
  ['froid(e)', 'cold', undefined],
  ['gagner (un salaire)', 'to earn (a salary)', undefined],
  ['les gamins', 'kids', 'm'],
  ['le gaz à effet de serre', 'greenhouse gas', 'm'],
  ['géant(e)', 'huge', undefined],
  ['génial(e)', 'great', undefined],
  ['gentil (gentille)', 'kind', undefined],
  ['gigantesque', 'gigantic', undefined],
  ['le golf', 'golf', 'm'],
  ['les gosses', 'children', 'm'],
  ['gratuit(e)', 'free', undefined],
  ['gros (grosse)', 'fat', undefined],
  ['le hôpital psychiatrique', 'psychiatric hospital', 'm'],
  ['la île', 'island', 'f'],
  ['le îlot', 'small island', 'm'],
  ['l\'image', 'image', 'f'],

  // Page 141
  ['l\'immeuble', 'building', 'm'],
  ['l\'immobilier', 'real estate', 'm'],
  ['important(e)', 'important', undefined],
  ['la imprimante', 'printer', 'f'],
  ['indiscipliné(e)', 'undisciplined', undefined],
  ['la inégalité', 'inequality', 'f'],
  ['innover', 'to innovate', undefined],
  ['l\'insecte', 'insect', 'm'],
  ['installer', 'to install', undefined],
  ['intellectuel(le)', 'intellectual', undefined],
  ['intime', 'intimate / private', undefined],
  ['le itinéraire', 'itinerary', 'm'],
  ['jamais', 'never', undefined],
  ['le jardin', 'garden', 'm'],
  ['je vous en prie', 'you\'re welcome', undefined],
  ['le jeu vidéo', 'computer game', 'm'],
  ['le job', 'job', 'm'],
  ['le jogging', 'jogging', 'm'],
  ['jouer (une situation)', 'to play out (a situation)', undefined],
  ['la langue', 'language', 'f'],
  ['le large', 'open sea', 'm'],
  ['le lave-linge', 'washing machine', 'm'],
  ['le lave-vaisselle', 'dishwasher', 'm'],
  ['la lettre de motivation', 'covering letter', 'f'],
  ['la liberté', 'freedom', 'f'],
  ['libre', 'free', undefined],
  ['lire', 'to read', undefined],
  ['le lit simple / double', 'single/double bed', 'm'],
  ['la littérature', 'literature', 'f'],
  ['le logement', 'lodging', 'm'],
  ['louer (un appartement)', 'to rent (a flat)', undefined],
  ['le loup', 'wolf', 'm'],
  ['lumineux (euse)', 'light', undefined],
  ['lutter contre', 'to fight against', undefined],
  ['le luxe', 'luxury', 'm'],
  ['magique', 'magical', undefined],
  ['magnifique', 'magnificent', undefined],
  ['maigrir', 'to lose weight', undefined],
  ['maintenant', 'now', undefined],
  ['la maison', 'house', 'f'],
  ['les mal-logé(e)s', 'inadequately-housed people', 'm'],
  ['le mammifère', 'mammal', 'm'],
  ['la manifestation', 'protest', 'f'],
  ['manifester', 'to protest', undefined],
  ['la marche', 'walking', 'f'],
  ['la marche (protestation)', 'protest march', 'f'],
  ['marcher', 'to walk', undefined],

  // Page 142
  ['la marionnette', 'puppet', 'f'],
  ['la marmotte', 'marmot', 'f'],
  ['marrant(e)', 'funny', undefined],
  ['la matière', 'subject', 'f'],
  ['le mégapixel', 'megapixel', 'm'],
  ['les mentalités', 'mentalities', 'f'],
  ['les mesures', 'measures / steps', 'f'],
  ['les mesures sociales', 'social policies', 'f'],
  ['le micro-ondes', 'microwave', 'm'],
  ['le/la ministre', 'minister', 'm/f'],
  ['le mobilier', 'furniture', 'm'],
  ['moche', 'ugly', undefined],
  ['le modèle', 'model', 'm'],
  ['monumental(e)', 'monumental', undefined],
  ['le mouton', 'sheep', 'm'],
  ['le multimédia', 'multimedia', 'm'],
  ['le mur', 'wall', 'm'],
  ['la musique', 'music', 'f'],
  ['la nature', 'nature', 'f'],
  ['la navette', 'shuttle', 'f'],
  ['nécessaire', 'necessary', undefined],
  ['négligé(e)', 'unkempt', undefined],
  ['la négociation', 'negotiation', 'f'],
  ['négocier', 'to negotiate', undefined],
  ['le nord', 'North', 'm'],
  ['nul(le)', 'rubbish', undefined],
  ['la nutrition', 'nutrition', 'f'],
  ['le objectif', 'lens', 'm'],
  ['la œuvre', 'work', 'f'],
  ['l\'oiseau', 'bird', 'm'],
  ['la opinion', 'opinion', 'f'],
  ['la opportunité', 'opportunity', 'f'],
  ['l\'oral', 'oral exam/expression', 'm'],
  ['l\'ordinateur', 'computer', 'm'],
  ['organiser', 'to organise', undefined],
  ['original(e)', 'original', undefined],
  ['l\'ouest', 'West', 'm'],
  ['l\'ours', 'bear', 'm'],
  ['la page d\'accueil', 'homepage', 'f'],
  ['le panorama', 'panorama', 'm'],
  ['la paranoia', 'paranoia', 'f'],
  ['paranoïaque', 'paranoid', undefined],
  ['le parcours', 'career path', 'm'],
  ['parfaitement', 'perfectly', undefined],
  ['parfois', 'sometimes', undefined],
  ['la parité', 'parity', 'f'],
  ['le partage', 'sharing', 'm'],
  ['passer l\'aspirateur', 'to do the vacuuming', undefined],
  ['payant(e)', 'charged', undefined],
  ['peindre', 'to paint', undefined],
  ['la pièce', 'room', 'f'],
  ['pique-niquer', 'to picnic', undefined],
  ['le placard', 'cupboard', 'm'],
  ['la place', 'square', 'f'],

  // Page 143
  ['la planète', 'planet', 'f'],
  ['les plantations', 'plantations', 'f'],
  ['la plante', 'plant', 'f'],
  ['les plaques', 'hot plates', 'f'],
  ['poétique', 'poetic', undefined],
  ['la poignée de main', 'handshake', 'f'],
  ['le point de vue', 'viewpoint', 'm'],
  ['les points cardinaux', 'cardinal points', 'm'],
  ['le poisson', 'fish', 'm'],
  ['poli(e)', 'polite', undefined],
  ['polluer', 'to pollute', undefined],
  ['la pollution', 'pollution', 'f'],
  ['le port', 'port', 'm'],
  ['le portable', 'mobile', 'm'],
  ['le pc portable', 'laptop', 'm'],
  ['le poste', 'position', 'm'],
  ['pratique', 'practical', undefined],
  ['pratiquer (un sport)', 'to do (a sport)', undefined],
  ['la précarité', 'precariousness', 'f'],
  ['pressé(e)', 'rushed', undefined],
  ['le presse-agrumes', 'lemon squeezer', 'm'],
  ['la prise de vue', 'shot', 'f'],
  ['le processeur', 'processor', 'm'],
  ['proche', 'near', undefined],
  ['programmable', 'programmable', undefined],
  ['le projet', 'project', 'm'],
  ['la promenade', 'walk', 'f'],
  ['la promo', 'promotional campaign', 'f'],
  ['la promotion', 'promotion', 'f'],
  ['proposer', 'to propose', undefined],
  ['la propriété', 'property', 'f'],
  ['la protection', 'protection', 'f'],
  ['la qualité', 'quality', 'f'],
  ['râleur(euse)', 'complainer', undefined],
  ['rangé(e)', 'tidy', undefined],
  ['ranger', 'to tidy', undefined],
  ['réaliser', 'to make', undefined],
  ['le réchauffement climatique', 'climate change', 'm'],
  ['réclamer', 'to claim', undefined],
  ['le recruteur', 'recruiter', 'm'],
  ['la réduction', 'reduction', 'f'],
  ['la réduction du temps de travail', 'reduced working week', 'f'],
  ['le réfrigérateur', 'refrigerator', 'm'],
  ['refuser', 'to refuse', undefined],
  ['le régime', 'regime', 'm'],
  ['la régularisation', 'regularisation', 'f'],
  ['régulariser', 'to regularise', undefined],
  ['la religion', 'religion', 'f'],
  ['remercier', 'to thank', undefined],
  ['remplir', 'to fill', undefined],
  ['la répétition', 'rehearsal', 'f'],

  // Page 144
  ['le réseau social', 'social network', 'm'],
  ['les responsabilités', 'responsibilities', 'f'],
  ['rester poli(e)', 'to remain polite', undefined],
  ['la revendication', 'claim', 'f'],
  ['revendiquer', 'to make demands', undefined],
  ['le rez-de-chaussée', 'ground floor', 'm'],
  ['le robot ménager', 'blender', 'm'],
  ['le rôle social', 'social role', 'm'],
  ['rond(e)', 'round', undefined],
  ['la rue', 'street', 'f'],
  ['s\'asseoir', 'to sit down', undefined],
  ['s\'enfermer', 'to shut oneself in', undefined],
  ['s\'engager', 'to commit oneself', undefined],
  ['s\'investir', 'to put a lot into', undefined],
  ['saisonnier(ère)', 'seasonal', undefined],
  ['le/la salarié(e)', 'employee', 'm/f'],
  ['la salle d\'eau', 'shower room', 'f'],
  ['la salle de bains', 'bathroom', 'f'],
  ['le salon', 'living room', 'm'],
  ['saluer', 'to greet', undefined],
  ['sans distinction', 'without distinction', undefined],
  ['les sans-logis', 'homeless', 'm'],
  ['les sans-papiers', 'undocumented immigrants', 'm'],
  ['la santé', 'health', 'f'],
  ['le savoir-vivre', 'etiquette', 'm'],
  ['le scanner', 'scanner', 'm'],
  ['sculpter', 'to sculpt', undefined],
  ['le sculpteur', 'sculptor', 'm'],
  ['la sculpture', 'sculpture', 'f'],
  ['se mobiliser', 'to take action', undefined],
  ['se moquer', 'to make fun of', undefined],
  ['se promener', 'to walk', undefined],
  ['se régaler', 'to enjoy', undefined],
  ['se reposer', 'to rest', undefined],
  ['se sentir bien', 'to feel good', undefined],
  ['se sentir mal', 'to feel bad', undefined],
  ['se sentir utile', 'to feel useful', undefined],
  ['se trouver en forme', 'to consider oneself in good shape', undefined],
  ['le sexe', 'gender', 'm'],
  ['simple', 'simple', undefined],
  ['la simulation', 'simulation', 'f'],
  ['simuler', 'to simulate', undefined],
  ['le site de rencontres', 'dating site', 'm'],
  ['la situation', 'location', 'f'],
  ['situer', 'to place', undefined],
  ['le smartphone', 'smartphone', 'm'],
  ['social(e)', 'social', undefined],
  ['solidaire', 'united', undefined],
  ['la solidarité', 'solidarity', 'f'],
  ['la solution', 'solution', 'f'],

  // Page 145
  ['le son', 'sound', 'm'],
  ['le souhait', 'wish', 'm'],
  ['souhaiter', 'to wish', undefined],
  ['souriant(e)', 'smiley', undefined],
  ['sourire', 'to smile', undefined],
  ['souvent', 'often', undefined],
  ['le spectacle', 'show', 'm'],
  ['stressé(e)', 'stressed', undefined],
  ['le studio', 'studio', 'm'],
  ['sublime', 'sublime', undefined],
  ['le sud', 'South', 'm'],
  ['le surf', 'surfing', 'm'],
  ['surfer', 'to surf the Internet', undefined],
  ['surprenant(e)', 'surprising', undefined],
  ['surtout', 'especially', undefined],
  ['la table', 'table', 'f'],
  ['le tableau', 'painting', 'm'],
  ['les tâches ménagères', 'household chores', 'f'],
  ['taper', 'to type', undefined],
  ['le tapis', 'rug', 'm'],
  ['le tennis', 'tennis', 'm'],
  ['la tenue', 'outfit', 'f'],
  ['la terrasse', 'terrace', 'f'],
  ['la terre', 'Earth', 'f'],
  ['le texte', 'text', 'm'],
  ['les toilettes', 'toilet', 'f'],
  ['toujours', 'always', undefined],
  ['tourner à droite / à gauche', 'to turn right/left', undefined],
  ['le traducteur', 'translator', 'm'],
  ['traverser', 'to cross', undefined],
  ['trouver (un emploi)', 'to find (a job)', undefined],
  ['le truc', 'thing', 'm'],
  ['l\'ultrabook', 'ultrabook', 'm'],
  ['unique', 'unique', undefined],
  ['l\'urbanisme', 'city planning', 'm'],
  ['utile', 'useful', undefined],
  ['la vache', 'cow', 'f'],
  ['la vaisselle', 'crockery', 'f'],
  ['valider', 'to confirm', undefined],
  ['vanter', 'to boast', undefined],
  ['vendre', 'to sell', undefined],
  ['le verre', 'glass', 'm'],
  ['les voies sur berges', 'towpaths', 'f'],
  ['la voile', 'sailing', 'f'],
  ['la voix', 'voice', 'f'],
  ['la vue', 'view', 'f'],
  ['zen', 'zen', undefined],
]

export const totem2LexiconCards: VocabCard[] = cardRows.map(([frontFr, backEn, gender], index) => ({
  id: `totem2-lexicon-card-${index + 1}`,
  deckId: 'totem2-lexicon',
  frontFr,
  backEn,
  gender,
  exampleFr: `Je révise : ${frontFr}.`,
  exampleEn: `Review card: ${backEn}.`,
  notes: 'From Totem 2 textbook lexicon.',
  tags: ['totem', 'lexicon'],
  confidence: 0,
  dueAt: today,
  intervalDays: 1,
  source: 'totem',
}))
